import { escapeHtml } from './ui.js';
import type {
  AffiliateComplianceDocumentView,
  AffiliateComplianceGateView,
  AffiliateComplianceSubjectView,
  AffiliateComplianceView,
  AffiliatePermissionView,
} from './affiliate-compliance-presenter.js';

const STYLE = `
  .ac{--ac-bg:#07090b;--ac-panel:#0d1115;--ac-soft:#11171c;--ac-line:#232d35;--ac-strong:#384650;--ac-ink:#f3f7f8;--ac-muted:#9aa8af;--ac-faint:#718087;--ac-teal:#00e5cc;--ac-amber:#f0b752;--ac-red:#ff7068;--ac-green:#4fdda7;background:var(--ac-bg);border:1px solid var(--ac-line);color:var(--ac-ink);font-family:var(--sans);box-shadow:0 20px 70px rgba(0,0,0,.2)}
  .ac *{box-sizing:border-box}.ac code,.ac .mono{font-family:var(--mono)}.ac-subnav{position:sticky;top:70px;z-index:10;display:flex;gap:4px;overflow-x:auto;padding:7px;border-bottom:1px solid var(--ac-line);background:rgba(7,9,11,.96);scrollbar-width:thin}.ac-subnav a{display:inline-flex;min-height:46px;align-items:center;padding:8px 13px;border:1px solid transparent;color:var(--ac-muted);font-size:12px;font-weight:800;white-space:nowrap}.ac-subnav a:first-child,.ac-subnav a:hover{border-color:var(--ac-strong);background:var(--ac-soft);color:var(--ac-ink)}
  .ac-hero{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(280px,.55fr);gap:24px;padding:36px 32px 30px;border-bottom:1px solid var(--ac-line);background:radial-gradient(circle at 88% 0,rgba(0,229,204,.13),transparent 31%),linear-gradient(135deg,#0b1013,#07090b)}.ac-kicker{color:var(--ac-teal);font:850 12px var(--mono);letter-spacing:.14em;text-transform:uppercase}.ac-hero h1{margin:9px 0 12px;font:600 clamp(2.7rem,6vw,5.5rem)/.88 var(--display);letter-spacing:-.045em}.ac-hero h1 em{display:block;color:var(--ac-teal);font-style:normal}.ac-hero p{max-width:780px;margin:0;color:var(--ac-muted);font-size:14px;line-height:1.7}.ac-lock{align-self:stretch;border:1px solid #693d3a;background:rgba(35,11,10,.66);padding:18px}.ac-lock small{display:block;color:var(--ac-red);font:900 11px var(--mono);letter-spacing:.12em;text-transform:uppercase}.ac-lock strong{display:block;margin:9px 0 7px;font:900 24px/1 var(--mono)}.ac-lock p{font-size:11px;color:#d4b8b6;line-height:1.55}
  .ac-truth{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:14px;padding:12px 30px;border-bottom:1px solid var(--ac-line);background:#090c0e}.ac-demo{border:1px solid var(--ac-amber);padding:5px 8px;color:var(--ac-amber);font:900 11px var(--mono);letter-spacing:.08em;text-transform:uppercase}.ac-truth p{margin:0;color:var(--ac-muted);font-size:12px}.ac-truth p strong{color:var(--ac-ink)}.ac-provenance{color:var(--ac-faint);font:750 11px var(--mono);white-space:nowrap}
  .ac-metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));border-bottom:1px solid var(--ac-line)}.ac-metric{padding:16px 18px;border-right:1px solid var(--ac-line)}.ac-metric:last-child{border-right:0}.ac-metric small{display:block;color:var(--ac-faint);font:800 10px var(--mono);letter-spacing:.06em;text-transform:uppercase}.ac-metric strong{display:block;margin:7px 0 3px;font:900 24px var(--mono)}.ac-metric span{color:var(--ac-muted);font-size:10px;line-height:1.45}.ac-metric.blocked strong{color:var(--ac-red)}
  .ac-gates,.ac-section{scroll-margin-top:132px;padding:21px;border-bottom:1px solid var(--ac-line)}.ac-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:14px}.ac-heading h2{margin:0;font-size:18px}.ac-heading p{margin:5px 0 0;color:var(--ac-muted);font-size:11px}.ac-chip{display:inline-flex;min-height:26px;align-items:center;border:1px solid var(--ac-strong);padding:4px 8px;color:var(--ac-muted);font:850 10px var(--mono);letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}.ac-chip.pass{border-color:#276e59;color:var(--ac-green);background:#0b2019}.ac-chip.wait{border-color:#705c32;color:var(--ac-amber);background:#1e180b}.ac-chip.blocked{border-color:#6a3b38;color:var(--ac-red);background:#210e0d}
  .ac-gate-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.ac-gate{min-height:132px;border:1px solid var(--ac-line);border-top:3px solid var(--ac-faint);background:var(--ac-panel);padding:13px}.ac-gate.pass{border-top-color:var(--ac-green)}.ac-gate.wait{border-top-color:var(--ac-amber)}.ac-gate.blocked{border-top-color:var(--ac-red)}.ac-gate small{color:var(--ac-faint);font:800 10px var(--mono);letter-spacing:.05em;text-transform:uppercase}.ac-gate strong{display:block;margin:8px 0 6px;font-size:13px}.ac-gate.pass strong{color:var(--ac-green)}.ac-gate.wait strong{color:var(--ac-amber)}.ac-gate.blocked strong{color:var(--ac-red)}.ac-gate p{margin:0;color:var(--ac-muted);font-size:10px;line-height:1.55}
  .ac-flow{display:grid;grid-template-columns:repeat(7,minmax(118px,1fr));gap:0;overflow-x:auto;border:1px solid var(--ac-line)}.ac-step{position:relative;min-width:118px;padding:14px;border-right:1px solid var(--ac-line);background:var(--ac-panel)}.ac-step:last-child{border-right:0}.ac-step::after{content:"→";position:absolute;right:-8px;top:19px;z-index:1;color:var(--ac-faint);background:var(--ac-bg);padding:1px}.ac-step:last-child::after{display:none}.ac-step small{color:var(--ac-faint);font:800 10px var(--mono)}.ac-step strong{display:block;margin:7px 0 5px;font-size:11px}.ac-step p{margin:0;color:var(--ac-muted);font-size:9px;line-height:1.5}.ac-step.current{box-shadow:inset 0 3px var(--ac-teal)}.ac-step.blocked{box-shadow:inset 0 3px var(--ac-red)}
  .ac-roster{display:grid;gap:12px}.ac-person{border:1px solid var(--ac-line);background:var(--ac-panel)}.ac-person-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;align-items:center;padding:15px 16px;border-bottom:1px solid var(--ac-line)}.ac-person h3{margin:0;font-size:14px}.ac-person-head p{margin:4px 0 0;color:var(--ac-muted);font-size:10px}.ac-person-body{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:0}.ac-permissions{padding:13px 16px;border-right:1px solid var(--ac-line)}.ac-permission-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.ac-permission{min-height:54px;border:1px solid var(--ac-line);background:var(--ac-soft);padding:8px 10px}.ac-permission strong{display:flex;justify-content:space-between;gap:8px;font-size:10px}.ac-permission strong span{color:var(--ac-red);font:850 9px var(--mono);text-transform:uppercase}.ac-permission p{margin:4px 0 0;color:var(--ac-faint);font-size:9px;line-height:1.4}.ac-link-denial{margin-top:10px;border:1px solid #6a3b38;background:#1a0d0c;padding:10px;color:#d6b5b2;font-size:10px}.ac-link-denial strong{color:var(--ac-red)}
  .ac-why{padding:15px;background:#0a0d10}.ac-why h4{margin:0 0 11px;font-size:12px}.ac-why-grid{display:grid;gap:9px}.ac-why-grid div{border-left:2px solid var(--ac-line);padding-left:9px}.ac-why-grid small{display:block;color:var(--ac-faint);font:800 9px var(--mono);text-transform:uppercase}.ac-why-grid strong,.ac-why-grid p{display:block;margin:3px 0 0;color:var(--ac-ink);font-size:10px;line-height:1.45}.ac-why-grid p{color:var(--ac-muted)}.ac-no-override{margin-top:11px;padding:9px;border:1px solid #6a3b38;color:#d4b8b6;font-size:9px;line-height:1.5}
  .ac-evidence{border-top:1px solid var(--ac-line)}.ac-evidence summary{min-height:46px;cursor:pointer;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 16px;color:var(--ac-muted);font-size:10px;font-weight:800}.ac-evidence summary:hover{background:var(--ac-soft);color:var(--ac-ink)}.ac-evidence-list{list-style:none;margin:0;padding:0 16px 13px}.ac-evidence-list li{display:grid;grid-template-columns:145px minmax(0,1fr) auto;gap:10px;padding:9px 0;border-top:1px solid var(--ac-line);font-size:9px}.ac-evidence-list time,.ac-evidence-list code{color:var(--ac-faint)}
  .ac-docs{border:1px solid var(--ac-line);overflow:auto}.ac-doc-row{display:grid;grid-template-columns:minmax(210px,1.3fr) 105px repeat(3,125px) 130px;min-width:890px;border-bottom:1px solid var(--ac-line)}.ac-doc-row:last-child{border-bottom:0}.ac-doc-row>div{padding:11px;border-right:1px solid var(--ac-line);font-size:10px}.ac-doc-row>div:last-child{border-right:0}.ac-doc-row.head{background:var(--ac-soft);color:var(--ac-faint);font:800 9px var(--mono);letter-spacing:.04em;text-transform:uppercase}.ac-doc-row strong{display:block;font-size:11px}.ac-doc-row code{display:block;margin-top:4px;color:var(--ac-faint);font-size:8px}.ac-status-pass{color:var(--ac-green)}.ac-status-wait{color:var(--ac-amber)}.ac-status-blocked{color:var(--ac-red)}
  .ac-two{display:grid;grid-template-columns:1fr 1fr;gap:13px}.ac-panel{border:1px solid var(--ac-line);background:var(--ac-panel)}.ac-panel-head{padding:14px 15px;border-bottom:1px solid var(--ac-line)}.ac-panel-head h3{margin:0;font-size:13px}.ac-panel-head p{margin:4px 0 0;color:var(--ac-muted);font-size:10px}.ac-list{list-style:none;margin:0;padding:7px 15px}.ac-list li{padding:10px 0;border-bottom:1px solid var(--ac-line);color:var(--ac-muted);font-size:10px;line-height:1.5}.ac-list li:last-child{border-bottom:0}.ac-list li strong{display:block;color:var(--ac-ink);font-size:11px}.ac-case{border-left:3px solid var(--ac-red);padding-left:10px}.ac-case code{color:var(--ac-faint);font-size:9px}.ac-empty{padding:16px;color:var(--ac-muted);font-size:10px}
  .ac-footer{display:flex;justify-content:space-between;gap:12px;padding:14px 21px;color:var(--ac-faint);font-size:10px}.ac-footer strong{color:var(--ac-muted)}
  @media(max-width:1050px){.ac-hero{grid-template-columns:1fr}.ac-metrics{grid-template-columns:repeat(3,1fr)}.ac-metric:nth-child(3){border-right:0}.ac-gate-grid{grid-template-columns:repeat(2,1fr)}.ac-person-body{grid-template-columns:1fr}.ac-permissions{border-right:0;border-bottom:1px solid var(--ac-line)}}
  @media(max-width:720px){.ac-subnav{top:62px}.ac-hero{padding:27px 20px}.ac-truth{grid-template-columns:1fr;padding:12px 20px}.ac-provenance{white-space:normal}.ac-metrics{grid-template-columns:repeat(2,1fr)}.ac-metric:nth-child(3){border-right:1px solid var(--ac-line)}.ac-metric:nth-child(even){border-right:0}.ac-gates,.ac-section{padding:15px}.ac-gate-grid,.ac-two,.ac-permission-grid{grid-template-columns:1fr}.ac-heading,.ac-person-head,.ac-footer{align-items:stretch;grid-template-columns:1fr;flex-direction:column}.ac-evidence-list li{grid-template-columns:1fr}.ac-hero h1{font-size:3rem}}
  @media(max-width:430px){.ac-metrics{grid-template-columns:1fr}.ac-metric{border-right:0!important}.ac-hero h1{font-size:2.55rem}.ac-gates,.ac-section{padding:10px}}
  @media(forced-colors:active){.ac,.ac-panel,.ac-person,.ac-gate,.ac-chip,.ac-lock,.ac-demo{forced-color-adjust:auto}.ac-gate{border-top-width:5px}}
  @media(prefers-reduced-motion:reduce){.ac *{scroll-behavior:auto!important;transition:none!important}}
`;

function time(value: string): string {
  const date = new Date(value);
  if (!Number.isFinite(date.getTime())) return 'Not recorded';
  const label = new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' }).format(date);
  return `<time datetime="${escapeHtml(date.toISOString())}">${escapeHtml(label)} UTC</time>`;
}

function gate(entry: AffiliateComplianceGateView, index: number): string {
  return `<article class="ac-gate ${entry.tone}"><small>${String(index + 1).padStart(2, '0')} · ${escapeHtml(entry.label)}</small><strong>${escapeHtml(entry.stateLabel)}</strong><p>${escapeHtml(entry.detail)}</p></article>`;
}

function documentRow(entry: AffiliateComplianceDocumentView): string {
  return `<div class="ac-doc-row"><div><strong>${escapeHtml(entry.title)}</strong><code>${escapeHtml(entry.documentType)} · ${escapeHtml(entry.digestLabel)}</code></div><div>${escapeHtml(entry.version)}</div><div class="ac-status-pass">${escapeHtml(entry.draftingLabel)}</div><div class="ac-status-blocked">${escapeHtml(entry.legalLabel)}</div><div class="ac-status-wait">${escapeHtml(entry.commercialLabel)}</div><div class="ac-status-blocked">${escapeHtml(entry.publicationLabel)}</div></div>`;
}

function permission(entry: AffiliatePermissionView): string {
  const reasons = entry.reasonLabels.length ? entry.reasonLabels.join(' · ') : 'No blocking evidence';
  return `<div class="ac-permission"><strong>${escapeHtml(entry.label)}<span>${escapeHtml(entry.stateLabel)}</span></strong><p>${escapeHtml(reasons)}</p></div>`;
}

function person(entry: AffiliateComplianceSubjectView): string {
  const timeline = entry.timeline.length ? entry.timeline.map((event) => `<li><time datetime="${escapeHtml(event.occurredAt)}">${escapeHtml(new Date(event.occurredAt).toISOString().slice(0, 16).replace('T', ' '))} UTC</time><span>${escapeHtml(event.label)}</span><code>${escapeHtml(event.evidenceSha256)}</code></li>`).join('') : '<li>No illustrative evidence events.</li>';
  return `<article class="ac-person"><header class="ac-person-head"><div><h3>${escapeHtml(entry.displayLabel)}</h3><p>${escapeHtml(entry.lifecycleLabel)} · fictional test record</p></div><span class="ac-chip blocked">${escapeHtml(entry.overallLabel)}</span></header><div class="ac-person-body"><div class="ac-permissions"><div class="ac-permission-grid">${entry.permissions.map(permission).join('')}</div><div class="ac-link-denial"><strong>No affiliate link is shown or copyable.</strong> The exact server-side <code>affiliate_link.issue</code> decision is denied.</div></div><aside class="ac-why" aria-label="Why ${escapeHtml(entry.displayLabel)} is blocked"><h4>Why blocked</h4><div class="ac-why-grid"><div><small>Evidence gap</small><strong>${escapeHtml(entry.whyBlocked.evidenceGap)}</strong></div><div><small>Remediation</small><p>${escapeHtml(entry.whyBlocked.remediation)}</p></div><div><small>Owner</small><strong>${escapeHtml(entry.whyBlocked.owner)}</strong></div></div><div class="ac-no-override"><strong>No override:</strong> ${escapeHtml(entry.whyBlocked.noOverride)}</div></aside></div><details class="ac-evidence"><summary><span>Evidence trail</span><span>${entry.timeline.length} immutable fixture event${entry.timeline.length === 1 ? '' : 's'}</span></summary><ul class="ac-evidence-list">${timeline}</ul></details></article>`;
}

export function renderAffiliateComplianceBody(view: AffiliateComplianceView): string {
  const cases = view.subjects.flatMap((subject) => subject.cases.map((entry) => ({ subject: subject.displayLabel, ...entry })));
  const caseRows = cases.length ? cases.map((entry) => `<li class="ac-case"><strong>${escapeHtml(entry.reasonLabel)}</strong><code>${escapeHtml(entry.caseReference)} · ${escapeHtml(entry.subject)} · ${escapeHtml(entry.state.replaceAll('_', ' '))}</code><br>${time(entry.openedAt)} · owner ${escapeHtml(entry.ownerRole)} · ${entry.blocksPermissions ? 'permissions blocked' : 'no permission block'}</li>`).join('') : '<li>No open illustrative cases.</li>';
  const decisionRows = view.openDecisions.map((entry, index) => `<li><strong>${String(index + 1).padStart(2, '0')}</strong>${escapeHtml(entry)}</li>`).join('');
  return `<style>${STYLE}</style><section class="ac" aria-labelledby="ac-title">
    <nav class="ac-subnav" aria-label="Affiliate compliance"><a href="#overview" aria-current="page">Overview</a><a href="#people">People</a><a href="#legal-bundle">Legal bundle</a><a href="#training">Training</a><a href="#channels">Channels</a><a href="#breaches">Breaches</a></nav>
    <header class="ac-hero" id="overview"><div><div class="ac-kicker">Property Predator · affiliate control</div><h1 id="ac-title">Grow the network.<em>Prove every permission.</em></h1><p>A calm, evidence-led operating view for contracts, training, declarations, channel authority, cases and last-moment eligibility. An account, commission row or CRM label can never grant permission.</p></div><aside class="ac-lock"><small>Runtime boundary</small><strong>EXTERNAL EFFECTS OFF</strong><p>No link generation, message, post, DM, tracking write, payout or provider call can start from this fixture-only page.</p></aside></header>
    <div class="ac-truth"><span class="ac-demo">Fictional demo</span><p><strong>No real affiliates or customer data.</strong> All people, events, cases and decisions below are synthetic fixtures.</p><span class="ac-provenance">${escapeHtml(view.sourceCommit)} · ${escapeHtml(view.sourceCommitLabel)}</span></div>
    <section class="ac-metrics" aria-label="Compliance facts"><div class="ac-metric"><small>Draft documents</small><strong>${view.metrics.documentCount}</strong><span>Exact versions prepared</span></div><div class="ac-metric blocked"><small>Solicitor approved</small><strong>${view.metrics.solicitorApprovedCount}</strong><span>Approval cannot be inferred</span></div><div class="ac-metric blocked"><small>Published</small><strong>${view.metrics.publishedCount}</strong><span>No effective bundle</span></div><div class="ac-metric"><small>Fictional people</small><strong>${view.metrics.fictionalSubjectCount}</strong><span>Test evidence only</span></div><div class="ac-metric blocked"><small>Open cases</small><strong>${view.metrics.openCaseCount}</strong><span>Illustrative enforcement</span></div></section>
    <section class="ac-gates" aria-labelledby="ac-gates-title"><div class="ac-heading"><div><h2 id="ac-gates-title">One readiness truth</h2><p>Independent facts stay independent. There is deliberately no misleading overall compliance score.</p></div><span class="ac-chip blocked">All live permissions denied</span></div><div class="ac-gate-grid">${view.gates.map(gate).join('')}</div></section>
    <section class="ac-section" aria-labelledby="ac-flow-title"><div class="ac-heading"><div><h2 id="ac-flow-title">The controlled route to eligibility</h2><p>Every arrow is a gate, not a progress animation.</p></div><span class="ac-chip wait">At solicitor review</span></div><div class="ac-flow">${view.workflow.map((step, index) => `<article class="ac-step ${step.state}"><small>${String(index + 1).padStart(2, '0')}</small><strong>${escapeHtml(step.label)}</strong><p>${escapeHtml(step.detail)}</p></article>`).join('')}</div></section>
    <section class="ac-section" id="people" aria-labelledby="ac-people-title"><div class="ac-heading"><div><h2 id="ac-people-title">Affiliate people</h2><p>Fictional roster. Each permission is scoped and evaluated separately.</p></div><span class="ac-chip blocked">${view.metrics.blockedSubjectCount} blocked</span></div><div class="ac-roster">${view.subjects.map(person).join('')}</div></section>
    <section class="ac-section" id="legal-bundle" aria-labelledby="ac-legal-title"><div class="ac-heading"><div><h2 id="ac-legal-title">Legal bundle truth</h2><p>Drafting, legal, commercial and publication states are never collapsed.</p></div><span class="ac-chip blocked">Not approved for use</span></div><div class="ac-docs"><div class="ac-doc-row head"><div>Document</div><div>Version</div><div>Drafting</div><div>Legal</div><div>Commercial</div><div>Publication</div></div>${view.documents.map(documentRow).join('')}</div></section>
    <section class="ac-section" id="training" aria-labelledby="ac-training-title"><div class="ac-heading"><div><h2 id="ac-training-title">Training and declarations</h2><p>Exact module versions, pass evidence, expiry and attestations will remain separate.</p></div><span class="ac-chip wait">Fixture evidence</span></div><div class="ac-two">${view.subjects.map((subject) => `<article class="ac-panel"><header class="ac-panel-head"><h3>${escapeHtml(subject.displayLabel)}</h3><p>${escapeHtml(subject.lifecycleLabel)}</p></header><ul class="ac-list"><li><strong>Acceptance</strong>${escapeHtml(subject.acceptanceLabel)}</li><li><strong>Training</strong>${escapeHtml(subject.trainingLabel)}</li><li><strong>Declarations</strong>${escapeHtml(subject.declarationLabel)}</li></ul></article>`).join('')}</div></section>
    <section class="ac-section" id="channels" aria-labelledby="ac-channels-title"><div class="ac-heading"><div><h2 id="ac-channels-title">Scoped channels — never toggles</h2><p>Channel, purpose, territory, sender, audience, PECR parties and specialist decisions are evidence rows.</p></div><span class="ac-chip blocked">Effects off</span></div><div class="ac-two">${view.subjects.map((subject) => `<article class="ac-panel"><header class="ac-panel-head"><h3>${escapeHtml(subject.displayLabel)}</h3><p>Recorded illustrative authority does not bypass the legal-pack gate.</p></header>${subject.currentChannelLabels.length ? `<ul class="ac-list">${subject.currentChannelLabels.map((channel) => `<li><strong>${escapeHtml(channel)}</strong>Illustrative scoped authority only · no provider effect</li>`).join('')}</ul>` : '<div class="ac-empty">No current channel authority.</div>'}</article>`).join('')}</div></section>
    <section class="ac-section" id="breaches" aria-labelledby="ac-breaches-title"><div class="ac-heading"><div><h2 id="ac-breaches-title">Breaches, takedowns and suspension</h2><p>Cases create append-only evidence and permission holds. They never silently erase earned commission.</p></div><span class="ac-chip ${cases.length ? 'blocked' : 'pass'}">${cases.length} open fixture case${cases.length === 1 ? '' : 's'}</span></div><div class="ac-two"><article class="ac-panel"><header class="ac-panel-head"><h3>Case queue</h3><p>Fictional examples only.</p></header><ul class="ac-list">${caseRows}</ul></article><article class="ac-panel"><header class="ac-panel-head"><h3>Solicitor and specialist decisions</h3><p>Blocked product decisions before publication or activation.</p></header><ul class="ac-list">${decisionRows}</ul></article></div></section>
    <footer class="ac-footer"><span><strong>${escapeHtml(view.workspaceName)}</strong> · snapshot ${time(view.asOf)}</span><span>Fictional demo · external effects off · no link exposed</span></footer>
  </section>`;
}
