/**
 * Pure server-rendered CRM body fragments for the first durable portal loop.
 *
 * Integration contract:
 * - Insert one renderer's output into `appShell` as its `body`.
 * - The controller supplies a request-bound CSRF token and stable command keys.
 * - The POST handlers must re-check workspace scope, permission, input, command
 *   idempotency and `expected_version`; these views are presentation only.
 * - Every customer-controlled value is escaped here. Route paths are fixed and
 *   object identifiers are URL encoded before entering a form action.
 *
 * Each body includes the small CRM extension stylesheet so it can be integrated
 * without editing the shared design system first. It can be moved into the page
 * head later without changing the renderer contract.
 */

import { escapeHtml, icon } from './ui.js';

export type CrmLifecycle = 'lead' | 'prospect' | 'customer' | 'archived' | 'other';
export type CrmTaskStatus = 'open' | 'completed' | 'cancelled';
export type CrmTaskFilter = 'open' | 'all' | 'completed';
export type CrmNoticeKind = 'success' | 'info' | 'error' | 'conflict';

export interface CrmWorkspaceView {
  id: string;
  name: string;
  timezone: string;
  snapshotAt: string;
  /** Derived from the active workspace membership, never from a form field. */
  canWrite: boolean;
}

export interface CrmContactView {
  id: string;
  displayName: string;
  companyName?: string | null;
  primaryEmail?: string | null;
  primaryPhone?: string | null;
  lifecycle: CrmLifecycle;
  openOpportunityCount: number;
  nextTaskAt?: string | null;
  lastActivityAt?: string | null;
  createdAt: string;
}

export interface CrmStageView {
  id: string;
  name: string;
  position: number;
  isClosed: boolean;
}

export interface CrmOpportunityView {
  id: string;
  contactId: string;
  contactName: string;
  companyName?: string | null;
  title: string;
  stageId: string;
  valueMinor?: number | null;
  currency?: string | null;
  ownerName?: string | null;
  expectedCloseDate?: string | null;
  nextTaskAt?: string | null;
  updatedAt: string;
  rowVersion: number;
  /** Stable for this rendered command; generated by the controller, not here. */
  moveCommandKey: string;
}

export interface CrmTaskView {
  id: string;
  title: string;
  status: CrmTaskStatus;
  contactName?: string | null;
  opportunityTitle?: string | null;
  assigneeName?: string | null;
  dueAt?: string | null;
  completedAt?: string | null;
  rowVersion: number;
  /** Stable for this rendered command; generated by the controller, not here. */
  completeCommandKey: string;
}

export interface CrmTimelineItemView {
  id: string;
  kind: 'lead_created' | 'stage_moved' | 'task_completed' | 'task_created' | 'note' | 'other';
  summary: string;
  actorName?: string | null;
  occurredAt: string;
}

export interface CrmWorkspaceSnapshot {
  workspace: CrmWorkspaceView;
  contacts: readonly CrmContactView[];
  stages: readonly CrmStageView[];
  opportunities: readonly CrmOpportunityView[];
  tasks: readonly CrmTaskView[];
  timeline: readonly CrmTimelineItemView[];
}

export type CreateLeadField = 'display_name' | 'company_name' | 'email' | 'phone' |
  'opportunity_title' | 'stage_id' | 'task_title' | 'task_due_at';

export interface CreateLeadValues {
  displayName?: string;
  companyName?: string;
  email?: string;
  phone?: string;
  opportunityTitle?: string;
  stageId?: string;
  taskTitle?: string;
  taskDueAt?: string;
}

export interface CreateLeadFormState {
  values?: CreateLeadValues;
  fieldErrors?: Partial<Record<CreateLeadField, readonly string[]>>;
}

export interface CrmNotice {
  kind: CrmNoticeKind;
  title: string;
  message: string;
}

export interface CrmMutationContext {
  /** A request-bound token produced by the portal CSRF helper. */
  csrfToken: string;
}

export interface ContactsPageOptions extends CrmMutationContext {
  createLeadCommandKey: string;
  form?: CreateLeadFormState;
  notice?: CrmNotice;
}

export interface PipelinePageOptions extends CrmMutationContext {
  notice?: CrmNotice;
}

export interface TasksPageOptions extends CrmMutationContext {
  filter?: CrmTaskFilter;
  notice?: CrmNotice;
}

export const CRM_PORTAL_STYLE = `
  .crm-page{display:grid;gap:20px}.crm-page-heading{margin-bottom:0}.crm-page-heading .crm-heading-meta{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:10px;color:var(--faint);font:700 .64rem var(--mono)}
  .crm-subnav{display:flex;align-items:center;gap:5px;padding:5px;border:1px solid var(--line);border-radius:13px;background:var(--panel);box-shadow:var(--shadow-sm);overflow-x:auto;scrollbar-width:thin}.crm-subnav a{min-height:38px;display:inline-flex;align-items:center;gap:7px;padding:8px 12px;border-radius:9px;color:var(--muted);font-size:.76rem;font-weight:740;white-space:nowrap}.crm-subnav a:hover{background:var(--panel-subtle);color:var(--ink)}.crm-subnav a[aria-current="page"]{background:var(--nav);color:#fff}.crm-subnav .icon{width:15px;height:15px}
  .crm-notice{display:flex;align-items:flex-start;gap:11px;border:1px solid var(--line);border-radius:12px;background:var(--panel);padding:13px 14px;box-shadow:var(--shadow-sm)}.crm-notice .icon{width:17px;height:17px;margin-top:2px}.crm-notice strong{display:block;font-size:.78rem;margin-bottom:2px}.crm-notice p{margin:0;color:var(--muted);font-size:.73rem}.crm-notice.success{border-color:#b9dfd1;background:var(--success-soft);color:var(--success)}.crm-notice.success p{color:var(--success)}.crm-notice.error,.crm-notice.conflict{border-color:#edc1be;background:var(--danger-soft);color:var(--danger)}.crm-notice.error p,.crm-notice.conflict p{color:#8f3636}.crm-notice.info{border-color:#c8d9f5;background:var(--info-soft);color:var(--info)}.crm-notice.info p{color:#294f8f}
  .crm-layout{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(330px,.7fr);gap:18px;align-items:start}.crm-stack{display:grid;gap:18px}.crm-panel{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow-sm);overflow:hidden}.crm-panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;padding:18px 19px 14px}.crm-panel-head h2{font-size:.94rem;margin:0}.crm-panel-head p{margin:4px 0 0;color:var(--muted);font-size:.72rem}.crm-panel-body{padding:0 19px 19px}.crm-count{display:inline-flex;align-items:center;justify-content:center;min-width:28px;height:28px;padding:0 8px;border-radius:999px;background:var(--panel-strong);color:var(--muted);font:800 .66rem var(--mono)}
  .crm-table-wrap{overflow-x:auto}.crm-table{width:100%;border-collapse:collapse;font-size:.76rem}.crm-table caption{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.crm-table th{text-align:left;color:var(--faint);font:750 .58rem var(--mono);letter-spacing:.065em;text-transform:uppercase;padding:10px 8px;border-bottom:1px solid var(--line);white-space:nowrap}.crm-table td{padding:13px 8px;border-bottom:1px solid var(--line);vertical-align:middle}.crm-table tbody tr:last-child td{border-bottom:0}.crm-contact-name{font-weight:780;color:var(--ink)}.crm-contact-company,.crm-secondary{display:block;margin-top:2px;color:var(--muted);font-size:.68rem}.crm-reach{font:650 .66rem var(--mono);color:var(--muted);overflow-wrap:anywhere}.crm-number{font:780 .7rem var(--mono);font-variant-numeric:tabular-nums}.crm-date{font-size:.68rem;color:var(--muted);white-space:nowrap}.crm-lifecycle{display:inline-flex;border:1px solid var(--line);border-radius:999px;background:var(--panel-subtle);padding:3px 8px;color:var(--muted);font:750 .56rem var(--mono);letter-spacing:.035em;text-transform:capitalize}
  .crm-form{display:grid;gap:14px}.crm-fieldset{border:0;margin:0;padding:0;display:grid;gap:12px}.crm-fieldset+ .crm-fieldset{padding-top:14px;border-top:1px solid var(--line)}.crm-legend{font-size:.76rem;font-weight:800;margin-bottom:1px}.crm-field-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.crm-field{min-width:0}.crm-field.full{grid-column:1/-1}.crm-field label{display:block;margin:0 0 6px;color:var(--ink);font-size:.69rem;font-weight:740}.crm-field label span{color:var(--faint);font-weight:600}.crm-field input,.crm-field select{width:100%;min-height:43px;border:1px solid var(--line-strong);border-radius:10px;background:#fff;color:var(--ink);padding:8px 11px;font-size:.78rem}.crm-field input:hover,.crm-field select:hover{border-color:#aeb8c6}.crm-field input:focus,.crm-field select:focus{border-color:var(--accent);box-shadow:0 0 0 4px rgba(237,156,36,.11)}.crm-field [aria-invalid="true"]{border-color:var(--danger);background:var(--danger-soft)}.crm-field-hint{margin:5px 0 0;color:var(--faint);font-size:.64rem;line-height:1.45}.crm-field-hint.full{grid-column:1/-1}.crm-field-error{margin:5px 0 0;color:var(--danger);font-size:.65rem;font-weight:700}.crm-form-foot{display:grid;gap:8px;padding-top:2px}.crm-form-foot .button{width:100%}.crm-effect-note{display:flex;align-items:flex-start;gap:7px;color:var(--faint);font-size:.64rem;line-height:1.45}.crm-effect-note .icon{width:13px;height:13px;margin-top:2px}.crm-error-summary{border:1px solid #edc1be;border-radius:11px;background:var(--danger-soft);padding:12px;color:var(--danger)}.crm-error-summary strong{display:block;font-size:.73rem}.crm-error-summary ul{margin:6px 0 0;padding-left:18px;font-size:.68rem}.crm-error-summary a{text-decoration:underline;text-underline-offset:2px}
  .crm-empty{border:1px dashed var(--line-strong);border-radius:12px;background:var(--panel-subtle);padding:25px 18px;text-align:center}.crm-empty .icon{width:24px;height:24px;color:var(--faint);margin-bottom:8px}.crm-empty strong{display:block;font-size:.79rem}.crm-empty p{max-width:440px;margin:5px auto 0;color:var(--muted);font-size:.7rem}.crm-unavailable{border:1px solid #efd09a;border-radius:11px;background:var(--accent-soft);padding:13px;color:#71430d;font-size:.72rem}
  .crm-board-intro{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.crm-board-help{max-width:640px;color:var(--muted);font-size:.71rem;margin:0}.crm-board{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(286px,1fr);gap:12px;overflow-x:auto;padding:2px 2px 13px;scroll-snap-type:x proximity;scrollbar-color:var(--line-strong) transparent}.crm-stage-column{scroll-snap-align:start;border:1px solid var(--line);border-radius:14px;background:var(--panel-subtle);padding:10px;min-height:220px}.crm-stage-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:4px 3px 11px;border-bottom:3px solid var(--stage-tone,var(--line-strong))}.crm-stage-head h2{font-size:.78rem;margin:0}.crm-stage-total{font:800 .62rem var(--mono);color:var(--muted)}.crm-stage-cards{display:grid;gap:9px;padding-top:10px}.crm-stage-tone-0{--stage-tone:#4d7fbd}.crm-stage-tone-1{--stage-tone:#9b70b7}.crm-stage-tone-2{--stage-tone:#d18b2f}.crm-stage-tone-3{--stage-tone:#158063}.crm-stage-tone-4{--stage-tone:#b45555}.crm-stage-tone-5{--stage-tone:#657187}.crm-opportunity{border:1px solid var(--line);border-radius:11px;background:var(--panel);padding:12px;box-shadow:0 1px 3px rgba(16,24,39,.04)}.crm-opportunity h3{font-size:.78rem;line-height:1.4;margin:0 0 5px}.crm-opportunity-contact{font-size:.69rem;color:var(--muted);margin-bottom:10px}.crm-opportunity-meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin-bottom:11px}.crm-meta-item{border-radius:8px;background:var(--panel-subtle);padding:7px}.crm-meta-item span{display:block;color:var(--faint);font:700 .52rem var(--mono);letter-spacing:.04em;text-transform:uppercase}.crm-meta-item strong{display:block;margin-top:3px;font-size:.64rem;font-weight:730;overflow-wrap:anywhere}.crm-move-form{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;align-items:end;padding-top:10px;border-top:1px solid var(--line)}.crm-move-field label{display:block;color:var(--faint);font:700 .56rem var(--mono);letter-spacing:.04em;text-transform:uppercase;margin-bottom:5px}.crm-move-field select{width:100%;height:36px;border:1px solid var(--line-strong);border-radius:9px;background:#fff;color:var(--ink);padding:5px 8px;font-size:.69rem}.crm-move-form .button{min-height:36px;padding:7px 10px;font-size:.69rem}.crm-card-note{margin:9px 0 0;color:var(--faint);font-size:.6rem}.crm-stage-empty{padding:20px 8px;text-align:center;color:var(--faint);font-size:.67rem}.crm-board-empty{padding:34px 18px}
  .crm-filterbar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.crm-filterlinks{display:flex;gap:5px;padding:4px;border:1px solid var(--line);border-radius:11px;background:var(--panel-subtle)}.crm-filterlinks a{min-height:32px;display:inline-flex;align-items:center;padding:6px 10px;border-radius:8px;color:var(--muted);font-size:.67rem;font-weight:740}.crm-filterlinks a[aria-current="page"]{background:var(--panel);color:var(--ink);box-shadow:var(--shadow-sm)}.crm-task-list,.crm-timeline{list-style:none;margin:0;padding:0;display:grid;gap:9px}.crm-task{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;align-items:center;border:1px solid var(--line);border-radius:11px;background:var(--panel-subtle);padding:12px}.crm-task h3{font-size:.77rem;margin:0 0 4px}.crm-task-context{color:var(--muted);font-size:.67rem;margin:0}.crm-task-meta{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-top:8px}.crm-task-status,.crm-due-state{display:inline-flex;border:1px solid var(--line);border-radius:999px;background:var(--panel);padding:3px 7px;color:var(--muted);font:750 .54rem var(--mono);letter-spacing:.035em;text-transform:uppercase}.crm-task-status.completed{border-color:#b9dfd1;background:var(--success-soft);color:var(--success)}.crm-due-state.overdue{border-color:#edc1be;background:var(--danger-soft);color:var(--danger)}.crm-complete-form{text-align:right}.crm-complete-form .button{white-space:nowrap}.crm-complete-form p{max-width:180px;margin:6px 0 0;color:var(--faint);font-size:.58rem;text-align:right}
  .crm-timeline-item{display:grid;grid-template-columns:30px minmax(0,1fr);gap:9px;position:relative}.crm-timeline-item:not(:last-child)::after{content:"";position:absolute;left:14px;top:30px;bottom:-9px;border-left:1px solid var(--line)}.crm-timeline-mark{position:relative;z-index:1;width:30px;height:30px;border:1px solid var(--line);border-radius:9px;background:var(--panel-subtle);display:grid;place-items:center;color:var(--muted);font:800 .68rem var(--mono)}.crm-timeline-copy{padding:4px 0 8px}.crm-timeline-copy p{font-size:.69rem;margin:0 0 3px}.crm-timeline-copy small{display:block;color:var(--faint);font-size:.61rem}.crm-visually-hidden{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
  @media(max-width:1080px){.crm-layout{grid-template-columns:minmax(0,1.25fr) minmax(300px,.75fr)}.crm-table .crm-optional-column{display:none}}
  @media(max-width:820px){.crm-layout{grid-template-columns:1fr}.crm-create-panel{order:-1}.crm-board{grid-auto-flow:row;grid-auto-columns:auto;grid-template-columns:1fr;overflow:visible;scroll-snap-type:none}.crm-stage-column{min-height:0}.crm-board-intro{display:block}.crm-board-help{margin-top:7px}.crm-task{grid-template-columns:1fr}.crm-complete-form{text-align:left}.crm-complete-form p{text-align:left;max-width:none}}
  @media(max-width:640px){.crm-page{gap:15px}.crm-panel-head{padding:15px 14px 11px}.crm-panel-body{padding:0 14px 14px}.crm-field-grid{grid-template-columns:1fr}.crm-field.full{grid-column:auto}.crm-table thead{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.crm-table,.crm-table tbody,.crm-table tr,.crm-table td{display:block;width:100%}.crm-table tr{padding:10px 0;border-bottom:1px solid var(--line)}.crm-table tr:last-child{border-bottom:0}.crm-table td{display:grid;grid-template-columns:94px 1fr;gap:9px;border:0;padding:4px 0}.crm-table td::before{content:attr(data-label);color:var(--faint);font:700 .54rem var(--mono);letter-spacing:.05em;text-transform:uppercase}.crm-table .crm-optional-column{display:grid}.crm-move-form{grid-template-columns:1fr}.crm-move-form .button{width:100%}.crm-subnav a{padding-inline:10px}.crm-filterbar{align-items:stretch}.crm-filterlinks{width:100%;display:grid;grid-template-columns:repeat(3,1fr)}.crm-filterlinks a{justify-content:center}}
  @media(forced-colors:active){.crm-subnav a[aria-current="page"],.crm-notice,.crm-stage-column,.crm-opportunity,.crm-task{border:1px solid CanvasText}.crm-stage-head{border-bottom-color:CanvasText}.crm-field [aria-invalid="true"]{outline:2px solid Mark}}
`;

/** Route contract consumed by the portal router when these fragments are wired. */
export const CRM_PORTAL_ROUTES = {
  contacts: '/portal/crm/contacts',
  createLead: '/portal/crm/leads',
  pipeline: '/portal/crm/opportunities',
  tasks: '/portal/crm/tasks',
} as const;

const LEAD_FIELD_IDS: Record<CreateLeadField, string> = {
  display_name: 'crm-lead-display-name',
  company_name: 'crm-lead-company-name',
  email: 'crm-lead-email',
  phone: 'crm-lead-phone',
  opportunity_title: 'crm-lead-opportunity-title',
  stage_id: 'crm-lead-stage',
  task_title: 'crm-lead-task-title',
  task_due_at: 'crm-lead-task-due-at',
};

const LEAD_FIELD_LABELS: Record<CreateLeadField, string> = {
  display_name: 'Contact name',
  company_name: 'Company',
  email: 'Email address',
  phone: 'Phone number',
  opportunity_title: 'Opportunity name',
  stage_id: 'Starting stage',
  task_title: 'First task',
  task_due_at: 'Task due date',
};

function styleElement(): string {
  return `<style data-relaunch72-crm>${CRM_PORTAL_STYLE}</style>`;
}

function count(value: unknown): string {
  return Number.isSafeInteger(value) && Number(value) >= 0
    ? new Intl.NumberFormat('en-GB').format(Number(value))
    : '—';
}

function safeDate(value: unknown): Date | null {
  if (typeof value !== 'string' || value.trim() === '') return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

function formatDateTime(value: unknown, timezone: string): { datetime: string; label: string } | null {
  const date = safeDate(value);
  if (!date) return null;
  const datetime = date.toISOString();
  const options: Intl.DateTimeFormatOptions = {
    dateStyle: 'medium', timeStyle: 'short', timeZone: timezone,
  };
  try {
    return { datetime, label: new Intl.DateTimeFormat('en-GB', options).format(date) };
  } catch {
    return {
      datetime,
      label: `${new Intl.DateTimeFormat('en-GB', { ...options, timeZone: 'UTC' }).format(date)} UTC`,
    };
  }
}

function dateTime(value: unknown, timezone: string, fallback = 'Not set'): string {
  const formatted = formatDateTime(value, timezone);
  return formatted
    ? `<time datetime="${escapeHtml(formatted.datetime)}">${escapeHtml(formatted.label)}</time>`
    : escapeHtml(fallback);
}

function calendarDate(value: unknown, fallback = 'Not set'): string {
  if (typeof value !== 'string') return escapeHtml(fallback);
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (!match) return escapeHtml(fallback);
  const date = new Date(Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3])));
  if (date.getUTCFullYear() !== Number(match[1]) || date.getUTCMonth() !== Number(match[2]) - 1
      || date.getUTCDate() !== Number(match[3])) return escapeHtml(fallback);
  const label = new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeZone: 'UTC' }).format(date);
  return `<time datetime="${escapeHtml(value)}">${escapeHtml(label)}</time>`;
}

function isOverdue(dueAt: unknown, snapshotAt: unknown): boolean {
  const due = safeDate(dueAt);
  const snapshot = safeDate(snapshotAt);
  return !!due && !!snapshot && due.getTime() < snapshot.getTime();
}

function formatMoney(valueMinor: unknown, currency: unknown): string {
  if (typeof valueMinor !== 'number' || !Number.isSafeInteger(valueMinor)) return 'Value not set';
  if (typeof currency !== 'string' || !/^[A-Z]{3}$/.test(currency)) return 'Value unavailable';
  try {
    return new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(valueMinor / 100);
  } catch {
    return 'Value unavailable';
  }
}

function validVersion(value: unknown): value is number {
  return typeof value === 'number' && Number.isSafeInteger(value) && value >= 1;
}

function validCommandKey(value: unknown): value is string {
  return typeof value === 'string' && /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(value);
}

function validCsrfToken(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0 && value.length <= 4096;
}

function hiddenMutationFields(csrfToken: string, commandKey: string, expectedVersion?: number): string {
  const version = expectedVersion === undefined
    ? ''
    : `<input type="hidden" name="expected_version" value="${escapeHtml(expectedVersion)}">`;
  return `<input type="hidden" name="_csrf" value="${escapeHtml(csrfToken)}"><input type="hidden" name="command_key" value="${escapeHtml(commandKey)}">${version}`;
}

function crmNav(active: 'contacts' | 'pipeline' | 'tasks'): string {
  const item = (id: typeof active, href: string, label: string, iconName: 'contacts' | 'pipeline' | 'calendar'): string =>
    `<a href="${href}"${active === id ? ' aria-current="page"' : ''}>${icon(iconName)}${label}</a>`;
  return `<nav class="crm-subnav" aria-label="CRM sections">${item('contacts', CRM_PORTAL_ROUTES.contacts, 'Contacts', 'contacts')}${item('pipeline', CRM_PORTAL_ROUTES.pipeline, 'Pipeline', 'pipeline')}${item('tasks', CRM_PORTAL_ROUTES.tasks, 'Tasks', 'calendar')}</nav>`;
}

function pageHeading(workspace: CrmWorkspaceView, active: 'contacts' | 'pipeline' | 'tasks', title: string, summary: string): string {
  const snapshot = formatDateTime(workspace.snapshotAt, workspace.timezone);
  return `<header class="page-heading crm-page-heading"><div><div class="eyebrow">${icon(active === 'contacts' ? 'contacts' : active === 'pipeline' ? 'pipeline' : 'calendar')}CRM · saved workspace records</div><h1>${escapeHtml(title)}</h1><p>${escapeHtml(summary)}</p><div class="crm-heading-meta"><span>${escapeHtml(workspace.name)}</span>${snapshot ? `<span aria-hidden="true">·</span><span>Viewed ${escapeHtml(snapshot.label)}</span>` : ''}</div></div></header>`;
}

function notice(view: CrmNotice | undefined): string {
  if (!view) return '';
  const role = view.kind === 'error' || view.kind === 'conflict' ? 'alert' : 'status';
  const symbol = view.kind === 'success' ? 'activity' : view.kind === 'info' ? 'activity' : 'lock';
  return `<div class="crm-notice ${view.kind}" role="${role}">${icon(symbol)}<div><strong>${escapeHtml(view.title)}</strong><p>${escapeHtml(view.message)}</p></div></div>`;
}

function emptyState(iconName: 'contacts' | 'pipeline' | 'calendar' | 'activity', title: string, message: string, extraClass = ''): string {
  return `<div class="crm-empty${extraClass ? ` ${extraClass}` : ''}" role="status">${icon(iconName)}<strong>${escapeHtml(title)}</strong><p>${escapeHtml(message)}</p></div>`;
}

function primaryReach(contact: CrmContactView): string {
  const email = contact.primaryEmail?.trim();
  const phone = contact.primaryPhone?.trim();
  if (email && phone) return `${escapeHtml(email)}<span class="crm-secondary">${escapeHtml(phone)}</span>`;
  return escapeHtml(email || phone || 'Not supplied');
}

function contactsTable(snapshot: CrmWorkspaceSnapshot): string {
  if (snapshot.contacts.length === 0) {
    return emptyState('contacts', 'No leads in this workspace yet', 'Use the create lead form to add the first private CRM record. No message will be sent.');
  }
  const rows = snapshot.contacts.map((contact) => `<tr>
    <td data-label="Contact"><span class="crm-contact-name">${escapeHtml(contact.displayName)}</span>${contact.companyName ? `<span class="crm-contact-company">${escapeHtml(contact.companyName)}</span>` : ''}</td>
    <td data-label="Primary reach"><span class="crm-reach">${primaryReach(contact)}</span></td>
    <td data-label="Lifecycle"><span class="crm-lifecycle">${escapeHtml(contact.lifecycle)}</span></td>
    <td data-label="Open deals"><span class="crm-number">${count(contact.openOpportunityCount)}</span></td>
    <td class="crm-optional-column" data-label="Next task"><span class="crm-date">${dateTime(contact.nextTaskAt, snapshot.workspace.timezone, 'None')}</span></td>
    <td class="crm-optional-column" data-label="Last activity"><span class="crm-date">${dateTime(contact.lastActivityAt, snapshot.workspace.timezone, 'No activity')}</span></td>
  </tr>`).join('');
  return `<div class="crm-table-wrap"><table class="crm-table"><caption>Contacts saved in ${escapeHtml(snapshot.workspace.name)}</caption><thead><tr><th scope="col">Contact</th><th scope="col">Primary reach</th><th scope="col">Lifecycle</th><th scope="col">Open deals</th><th class="crm-optional-column" scope="col">Next task</th><th class="crm-optional-column" scope="col">Last activity</th></tr></thead><tbody>${rows}</tbody></table></div>`;
}

function fieldErrors(state: CreateLeadFormState | undefined, field: CreateLeadField): readonly string[] {
  const errors = state?.fieldErrors?.[field];
  return Array.isArray(errors) ? errors.filter((error): error is string => typeof error === 'string' && error.trim() !== '') : [];
}

function errorAttributes(state: CreateLeadFormState | undefined, field: CreateLeadField): string {
  const errors = fieldErrors(state, field);
  return errors.length > 0
    ? ` aria-invalid="true" aria-describedby="${LEAD_FIELD_IDS[field]}-error"`
    : '';
}

function inlineErrors(state: CreateLeadFormState | undefined, field: CreateLeadField): string {
  const errors = fieldErrors(state, field);
  return errors.length > 0
    ? `<p class="crm-field-error" id="${LEAD_FIELD_IDS[field]}-error">${errors.map(escapeHtml).join(' ')}</p>`
    : '';
}

function leadErrorSummary(state: CreateLeadFormState | undefined): string {
  const entries = (Object.keys(LEAD_FIELD_IDS) as CreateLeadField[]).flatMap((field) =>
    fieldErrors(state, field).map((error) => ({ field, error })));
  if (entries.length === 0) return '';
  return `<div class="crm-error-summary" role="alert" tabindex="-1"><strong>Check the lead details</strong><ul>${entries.map(({ field, error }) => `<li><a href="#${LEAD_FIELD_IDS[field]}">${escapeHtml(LEAD_FIELD_LABELS[field])}: ${escapeHtml(error)}</a></li>`).join('')}</ul></div>`;
}

function createLeadForm(snapshot: CrmWorkspaceSnapshot, options: ContactsPageOptions): string {
  const stages = snapshot.stages.filter((stage) => !stage.isClosed)
    .sort((left, right) => left.position - right.position);
  if (!snapshot.workspace.canWrite) {
    return `<div class="crm-unavailable" role="status"><strong>Read-only CRM access.</strong><br>Your workspace role can review contacts, opportunities and tasks but cannot create or change records.</div>`;
  }
  if (stages.length === 0) {
    return `<div class="crm-unavailable" role="status"><strong>Lead creation is not available yet.</strong><br>The workspace needs at least one open pipeline stage before an opportunity can be created.</div>`;
  }
  if (!validCsrfToken(options.csrfToken) || !validCommandKey(options.createLeadCommandKey)) {
    return `<div class="crm-unavailable" role="status"><strong>Refresh needed.</strong><br>A secure form token is missing or a new command key is required before this form can safely save a lead.</div>`;
  }
  const values = options.form?.values ?? {};
  const selectedStage = stages.some((stage) => stage.id === values.stageId) ? values.stageId : stages[0]!.id;
  return `<form class="crm-form" method="post" action="${CRM_PORTAL_ROUTES.createLead}">
    ${hiddenMutationFields(options.csrfToken, options.createLeadCommandKey)}
    ${leadErrorSummary(options.form)}
    <fieldset class="crm-fieldset"><legend class="crm-legend">Contact</legend><div class="crm-field-grid">
      <div class="crm-field full"><label for="${LEAD_FIELD_IDS.display_name}">Contact name</label><input id="${LEAD_FIELD_IDS.display_name}" name="display_name" type="text" autocomplete="name" maxlength="160" value="${escapeHtml(values.displayName)}" required${errorAttributes(options.form, 'display_name')}>${inlineErrors(options.form, 'display_name')}</div>
      <div class="crm-field full"><label for="${LEAD_FIELD_IDS.company_name}">Company <span>optional</span></label><input id="${LEAD_FIELD_IDS.company_name}" name="company_name" type="text" autocomplete="organization" maxlength="160" value="${escapeHtml(values.companyName)}"${errorAttributes(options.form, 'company_name')}>${inlineErrors(options.form, 'company_name')}</div>
      <div class="crm-field"><label for="${LEAD_FIELD_IDS.email}">Email address <span>optional</span></label><input id="${LEAD_FIELD_IDS.email}" name="email" type="email" inputmode="email" autocomplete="email" autocapitalize="none" spellcheck="false" maxlength="254" value="${escapeHtml(values.email)}"${errorAttributes(options.form, 'email')}>${inlineErrors(options.form, 'email')}</div>
      <div class="crm-field"><label for="${LEAD_FIELD_IDS.phone}">Phone number <span>optional</span></label><input id="${LEAD_FIELD_IDS.phone}" name="phone" type="tel" inputmode="tel" autocomplete="tel" maxlength="40" value="${escapeHtml(values.phone)}"${errorAttributes(options.form, 'phone')}>${inlineErrors(options.form, 'phone')}</div>
      <p class="crm-field-hint full">Add an email address, phone number, or both. Saving the record does not contact the person.</p>
    </div></fieldset>
    <fieldset class="crm-fieldset"><legend class="crm-legend">Opportunity</legend><div class="crm-field-grid">
      <div class="crm-field full"><label for="${LEAD_FIELD_IDS.opportunity_title}">Opportunity name</label><input id="${LEAD_FIELD_IDS.opportunity_title}" name="opportunity_title" type="text" maxlength="180" value="${escapeHtml(values.opportunityTitle)}" required${errorAttributes(options.form, 'opportunity_title')}>${inlineErrors(options.form, 'opportunity_title')}</div>
      <div class="crm-field full"><label for="${LEAD_FIELD_IDS.stage_id}">Starting stage</label><select id="${LEAD_FIELD_IDS.stage_id}" name="stage_id" required${errorAttributes(options.form, 'stage_id')}>${stages.map((stage) => `<option value="${escapeHtml(stage.id)}"${stage.id === selectedStage ? ' selected' : ''}>${escapeHtml(stage.name)}</option>`).join('')}</select>${inlineErrors(options.form, 'stage_id')}</div>
    </div></fieldset>
    <fieldset class="crm-fieldset"><legend class="crm-legend">First task <span class="crm-secondary">optional</span></legend><div class="crm-field-grid">
      <div class="crm-field full"><label for="${LEAD_FIELD_IDS.task_title}">Task</label><input id="${LEAD_FIELD_IDS.task_title}" name="task_title" type="text" maxlength="180" value="${escapeHtml(values.taskTitle)}"${errorAttributes(options.form, 'task_title')}>${inlineErrors(options.form, 'task_title')}</div>
      <div class="crm-field full"><label for="${LEAD_FIELD_IDS.task_due_at}">Due date and time <span>workspace time</span></label><input id="${LEAD_FIELD_IDS.task_due_at}" name="task_due_at" type="datetime-local" value="${escapeHtml(values.taskDueAt)}"${errorAttributes(options.form, 'task_due_at')}>${inlineErrors(options.form, 'task_due_at')}</div>
    </div></fieldset>
    <div class="crm-form-foot"><button class="button" type="submit">${icon('contacts')}Create lead in CRM</button><div class="crm-effect-note">${icon('lock')}<span>Creates private contact, opportunity and optional task records only. It does not send a message, schedule content or notify the contact.</span></div></div>
  </form>`;
}

function timelinePanel(snapshot: CrmWorkspaceSnapshot): string {
  const items = snapshot.timeline.slice(0, 12);
  const body = items.length === 0
    ? emptyState('activity', 'No CRM activity recorded yet', 'Saved lead, stage and task actions will appear here. This is not a message-delivery log.')
    : `<ol class="crm-timeline">${items.map((item) => {
      const marker = item.kind === 'lead_created' ? '+' : item.kind === 'stage_moved' ? '→' : item.kind === 'task_completed' ? '✓' : '•';
      const actor = item.actorName?.trim() ? ` · ${escapeHtml(item.actorName)}` : '';
      return `<li class="crm-timeline-item"><span class="crm-timeline-mark" aria-hidden="true">${marker}</span><div class="crm-timeline-copy"><p>${escapeHtml(item.summary)}</p><small>${dateTime(item.occurredAt, snapshot.workspace.timezone, 'Time unavailable')}${actor}</small></div></li>`;
    }).join('')}</ol>`;
  return `<section class="crm-panel" aria-labelledby="crm-timeline-title"><div class="crm-panel-head"><div><h2 id="crm-timeline-title">Recent CRM activity</h2><p>Recorded workspace changes · newest first</p></div>${icon('activity')}</div><div class="crm-panel-body">${body}</div></section>`;
}

/** Renders the Contacts + Create lead body fragment for the shared portal shell. */
export function renderCrmContactsBody(snapshot: CrmWorkspaceSnapshot, options: ContactsPageOptions): string {
  return `${styleElement()}<div class="crm-page" data-crm-page="contacts">
    ${pageHeading(snapshot.workspace, 'contacts', 'Contacts', 'Create and review the people and companies held inside this private workspace.')}
    ${crmNav('contacts')}
    ${notice(options.notice)}
    <div class="crm-layout"><div class="crm-stack">
      <section class="crm-panel" aria-labelledby="crm-contacts-title"><div class="crm-panel-head"><div><h2 id="crm-contacts-title">All contacts</h2><p>Saved CRM records · no outreach is triggered from this list</p></div><span class="crm-count" aria-label="${count(snapshot.contacts.length)} contacts">${count(snapshot.contacts.length)}</span></div><div class="crm-panel-body">${contactsTable(snapshot)}</div></section>
      ${timelinePanel(snapshot)}
    </div><aside class="crm-panel crm-create-panel" aria-labelledby="crm-create-lead-title"><div class="crm-panel-head"><div><h2 id="crm-create-lead-title">Create a lead</h2><p>Contact + opportunity + optional first task</p></div>${icon('contacts')}</div><div class="crm-panel-body">${createLeadForm(snapshot, options)}</div></aside></div>
  </div>`;
}

function opportunityMoveForm(opportunity: CrmOpportunityView, stages: readonly CrmStageView[], csrfToken: string, formIndex: number, canWrite: boolean): string {
  if (!canWrite) return '<p class="crm-card-note" role="status">Read-only access · stage changes are unavailable for your workspace role.</p>';
  const alternatives = stages.filter((stage) => stage.id !== opportunity.stageId);
  if (alternatives.length === 0) return '<p class="crm-card-note">No other saved stage is available.</p>';
  if (!validCsrfToken(csrfToken) || !validVersion(opportunity.rowVersion) || !validCommandKey(opportunity.moveCommandKey)) {
    return '<p class="crm-card-note" role="status">Refresh this page before moving this opportunity.</p>';
  }
  const selectId = `crm-move-stage-${formIndex}`;
  return `<form class="crm-move-form" method="post" action="${CRM_PORTAL_ROUTES.pipeline}/${encodeURIComponent(opportunity.id)}/stage" aria-label="Move ${escapeHtml(opportunity.title)} to another stage">
    ${hiddenMutationFields(csrfToken, opportunity.moveCommandKey, opportunity.rowVersion)}
    <div class="crm-move-field"><label for="${selectId}">Move to</label><select id="${selectId}" name="target_stage_id" required>${alternatives.map((stage) => `<option value="${escapeHtml(stage.id)}">${escapeHtml(stage.name)}</option>`).join('')}</select></div>
    <button class="button secondary" type="submit">Move stage</button>
  </form><p class="crm-card-note">Saves the CRM stage and activity only · no contact is notified.</p>`;
}

function pipelineBoard(snapshot: CrmWorkspaceSnapshot, csrfToken: string): string {
  const stages = [...snapshot.stages].sort((left, right) => left.position - right.position);
  if (stages.length === 0) {
    return emptyState('pipeline', 'No pipeline stages have been saved', 'Create the workspace pipeline before adding or moving opportunities.', 'crm-board-empty');
  }
  let cardIndex = 0;
  const columns = stages.map((stage, stageIndex) => {
    const opportunities = snapshot.opportunities.filter((opportunity) => opportunity.stageId === stage.id);
    const cards = opportunities.length === 0
      ? '<p class="crm-stage-empty">No opportunities in this stage.</p>'
      : opportunities.map((opportunity) => {
        const index = cardIndex++;
        return opportunityCardWithToken(opportunity, stages, snapshot, csrfToken, index);
      }).join('');
    return `<section class="crm-stage-column crm-stage-tone-${stageIndex % 6}" aria-labelledby="crm-stage-${stageIndex}-title"><div class="crm-stage-head"><h2 id="crm-stage-${stageIndex}-title">${escapeHtml(stage.name)}</h2><span class="crm-stage-total">${count(opportunities.length)}</span></div><div class="crm-stage-cards">${cards}</div></section>`;
  });
  const orphaned = snapshot.opportunities.filter((opportunity) => !stages.some((stage) => stage.id === opportunity.stageId));
  if (orphaned.length > 0) {
    const cards = orphaned.map((opportunity) => opportunityCardWithToken(opportunity, stages, snapshot, csrfToken, cardIndex++)).join('');
    columns.push(`<section class="crm-stage-column crm-stage-tone-4" aria-labelledby="crm-stage-needs-review"><div class="crm-stage-head"><h2 id="crm-stage-needs-review">Stage needs review</h2><span class="crm-stage-total">${count(orphaned.length)}</span></div><p class="crm-card-note">These records reference a stage that is no longer available. Move each one to a saved stage.</p><div class="crm-stage-cards">${cards}</div></section>`);
  }
  return `<div class="crm-board" aria-label="Opportunity stages">${columns.join('')}</div>`;
}

function opportunityCardWithToken(opportunity: CrmOpportunityView, stages: readonly CrmStageView[], snapshot: CrmWorkspaceSnapshot, csrfToken: string, index: number): string {
  const nextTask = opportunity.nextTaskAt
    ? `${isOverdue(opportunity.nextTaskAt, snapshot.workspace.snapshotAt) ? '<span class="crm-visually-hidden">Overdue: </span>' : ''}${dateTime(opportunity.nextTaskAt, snapshot.workspace.timezone)}`
    : 'No next task';
  return `<article class="crm-opportunity" aria-labelledby="crm-opportunity-${index}-title"><h3 id="crm-opportunity-${index}-title">${escapeHtml(opportunity.title)}</h3><p class="crm-opportunity-contact">${escapeHtml(opportunity.contactName)}${opportunity.companyName ? ` · ${escapeHtml(opportunity.companyName)}` : ''}</p><div class="crm-opportunity-meta">
    <div class="crm-meta-item"><span>Value</span><strong>${escapeHtml(formatMoney(opportunity.valueMinor, opportunity.currency))}</strong></div>
    <div class="crm-meta-item"><span>Owner</span><strong>${escapeHtml(opportunity.ownerName?.trim() || 'Unassigned')}</strong></div>
    <div class="crm-meta-item"><span>Expected close</span><strong>${calendarDate(opportunity.expectedCloseDate)}</strong></div>
    <div class="crm-meta-item"><span>Next task</span><strong>${nextTask}</strong></div>
  </div>${opportunityMoveForm(opportunity, stages, csrfToken, index, snapshot.workspace.canWrite)}</article>`;
}

/** Renders the accessible, form-driven Opportunity pipeline body fragment. */
export function renderCrmPipelineBody(snapshot: CrmWorkspaceSnapshot, options: PipelinePageOptions): string {
  return `${styleElement()}<div class="crm-page" data-crm-page="pipeline">
    ${pageHeading(snapshot.workspace, 'pipeline', 'Opportunity pipeline', 'Move saved opportunities through the pipeline with explicit, reviewable form submissions.')}
    ${crmNav('pipeline')}
    ${notice(options.notice)}
    <section class="crm-panel" aria-labelledby="crm-board-title"><div class="crm-panel-head crm-board-intro"><div><h2 id="crm-board-title">Pipeline board</h2><p>${count(snapshot.opportunities.length)} saved opportunities across ${count(snapshot.stages.length)} stages</p></div><p class="crm-board-help">Use the labelled “Move to” form on a card. The change is saved only after submission; this board does not pretend to support drag and drop.</p></div><div class="crm-panel-body">${pipelineBoard(snapshot, options.csrfToken)}</div></section>
    ${timelinePanel(snapshot)}
  </div>`;
}

function taskFilterNav(active: CrmTaskFilter, tasks: readonly CrmTaskView[]): string {
  const openCount = tasks.filter((task) => task.status === 'open').length;
  const completeCount = tasks.filter((task) => task.status === 'completed').length;
  const filter = (id: CrmTaskFilter, href: string, label: string, itemCount: number): string =>
    `<a href="${href}"${active === id ? ' aria-current="page"' : ''}>${label} <span class="crm-visually-hidden">tasks: </span>${count(itemCount)}</a>`;
  return `<nav class="crm-filterlinks" aria-label="Task status filter">${filter('open', `${CRM_PORTAL_ROUTES.tasks}?status=open`, 'Open', openCount)}${filter('all', `${CRM_PORTAL_ROUTES.tasks}?status=all`, 'All', tasks.length)}${filter('completed', `${CRM_PORTAL_ROUTES.tasks}?status=completed`, 'Completed', completeCount)}</nav>`;
}

function taskCompleteForm(task: CrmTaskView, csrfToken: string, canWrite: boolean): string {
  if (!canWrite) return '<p class="crm-card-note" role="status">Read-only access · task changes are unavailable for your workspace role.</p>';
  if (!validCsrfToken(csrfToken) || !validVersion(task.rowVersion) || !validCommandKey(task.completeCommandKey)) {
    return '<p class="crm-card-note" role="status">Refresh this page before completing this task.</p>';
  }
  return `<form class="crm-complete-form" method="post" action="${CRM_PORTAL_ROUTES.tasks}/${encodeURIComponent(task.id)}/complete" aria-label="Mark ${escapeHtml(task.title)} complete">${hiddenMutationFields(csrfToken, task.completeCommandKey, task.rowVersion)}<button class="button secondary compact" type="submit">Mark complete</button><p>Updates this CRM task only · no message is sent.</p></form>`;
}

function taskList(snapshot: CrmWorkspaceSnapshot, filter: CrmTaskFilter, csrfToken: string): string {
  const tasks = filter === 'all' ? snapshot.tasks : snapshot.tasks.filter((task) => task.status === filter);
  if (tasks.length === 0) {
    const message = filter === 'open'
      ? 'There are no open tasks in this workspace.'
      : filter === 'completed'
        ? 'No tasks have been marked complete yet.'
        : 'Tasks created with leads will appear here.';
    return emptyState('calendar', `No ${filter === 'all' ? '' : `${filter} `}tasks`, message);
  }
  return `<ol class="crm-task-list">${tasks.map((task, index) => {
    const context = [task.contactName, task.opportunityTitle].filter((value): value is string => typeof value === 'string' && value.trim() !== '');
    const due = task.status === 'completed' ? task.completedAt : task.dueAt;
    const overdue = task.status === 'open' && isOverdue(task.dueAt, snapshot.workspace.snapshotAt);
    const statusLabel = task.status === 'completed' ? 'Completed' : task.status === 'cancelled' ? 'Cancelled' : 'Open';
    return `<li class="crm-task"><div><h3 id="crm-task-${index}-title">${escapeHtml(task.title)}</h3><p class="crm-task-context">${context.length ? context.map(escapeHtml).join(' · ') : 'Workspace task'}${task.assigneeName ? ` · ${escapeHtml(task.assigneeName)}` : ''}</p><div class="crm-task-meta"><span class="crm-task-status${task.status === 'completed' ? ' completed' : ''}">${statusLabel}</span>${due ? `<span class="crm-due-state${overdue ? ' overdue' : ''}">${overdue ? 'Overdue · ' : task.status === 'completed' ? 'Completed · ' : 'Due · '}${dateTime(due, snapshot.workspace.timezone, 'Time unavailable')}</span>` : ''}</div></div>${task.status === 'open' ? taskCompleteForm(task, csrfToken, snapshot.workspace.canWrite) : ''}</li>`;
  }).join('')}</ol>`;
}

/** Renders the Tasks body fragment with real status-filter links and POST forms. */
export function renderCrmTasksBody(snapshot: CrmWorkspaceSnapshot, options: TasksPageOptions): string {
  const filter = options.filter === 'all' || options.filter === 'completed' ? options.filter : 'open';
  return `${styleElement()}<div class="crm-page" data-crm-page="tasks">
    ${pageHeading(snapshot.workspace, 'tasks', 'Tasks', 'See the next CRM actions and record completion without triggering external messages.')}
    ${crmNav('tasks')}
    ${notice(options.notice)}
    <div class="crm-layout"><section class="crm-panel" aria-labelledby="crm-tasks-title"><div class="crm-panel-head crm-filterbar"><div><h2 id="crm-tasks-title">${filter === 'all' ? 'All tasks' : filter === 'completed' ? 'Completed tasks' : 'Open tasks'}</h2><p>Saved workspace tasks · task changes are recorded in CRM activity</p></div>${taskFilterNav(filter, snapshot.tasks)}</div><div class="crm-panel-body">${taskList(snapshot, filter, options.csrfToken)}</div></section><aside>${timelinePanel(snapshot)}</aside></div>
  </div>`;
}
