/** Server-rendered, read-only Property Predator Growth Analytics UI. */

import { escapeHtml } from './ui.js';
import type {
  AnalyticsCohortView,
  AnalyticsContentAttributionView,
  AnalyticsFunnelMilestoneView,
  AnalyticsQualitySignalView,
  AnalyticsSourceAttributionView,
  AnalyticsTruthView,
  AnalyticsWebinarContributionView,
  GrowthAnalyticsView,
} from './growth-analytics-presenter.js';

const GROWTH_ANALYTICS_STYLE = `
  .pga{--night:#07090a;--night2:#0a0e10;--panel:#101518;--lift:#151c20;--soft:#1a2327;--line:#253238;--line2:#37474e;--ink:#f3f6f5;--muted:#a4b0b3;--faint:#74838a;--acid:#00e5cc;--acid2:#7cffe9;--amber:#ffc85b;--red:#ff756d;--blue:#8fb9ff;--violet:#c29cff;--mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace;position:relative;isolation:isolate;min-width:0;color:var(--ink);background:var(--night);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;border:1px solid #030404;overflow:hidden}.pga *{box-sizing:border-box}.pga h1,.pga h2,.pga h3,.pga p{overflow-wrap:anywhere}.pga code{font-family:var(--mono);overflow-wrap:anywhere}.pga-visually-hidden{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
  .pga-hero{position:relative;display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,360px);gap:34px;align-items:end;padding:36px 38px 30px;border-bottom:1px solid var(--line);background:radial-gradient(circle at 82% 14%,rgba(0,229,204,.16),transparent 29%),radial-gradient(circle at 8% 110%,rgba(143,185,255,.08),transparent 29%),linear-gradient(135deg,#12191c,#07090a 68%);overflow:hidden}.pga-hero:before{content:"";position:absolute;right:26%;top:-174px;width:265px;height:265px;border:1px solid rgba(0,229,204,.13);transform:rotate(45deg)}.pga-kicker{position:relative;display:flex;align-items:center;gap:10px;color:var(--acid);font:900 11px/1.2 var(--mono);letter-spacing:.14em;text-transform:uppercase}.pga-kicker:before{content:"";width:29px;height:1px;background:var(--acid)}.pga-hero h1{position:relative;max-width:830px;margin:13px 0 13px;font-size:clamp(2.6rem,5.1vw,5.2rem);font-weight:610;line-height:.89;letter-spacing:-.058em}.pga-hero h1 em{color:var(--acid);font-style:normal}.pga-hero-copy>p{position:relative;max-width:790px;margin:0;color:var(--muted);font-size:14px;line-height:1.7}.pga-dataset{position:relative;border:1px solid rgba(0,229,204,.3);background:rgba(5,9,10,.76);padding:17px 18px;box-shadow:0 20px 60px rgba(0,0,0,.28)}.pga-dataset:before{content:"EVIDENCE SNAPSHOT";position:absolute;right:12px;top:9px;color:rgba(0,229,204,.35);font:900 8px var(--mono);letter-spacing:.1em}.pga-dataset>span{display:block;color:var(--faint);font:850 9px var(--mono);letter-spacing:.08em;text-transform:uppercase}.pga-dataset strong{display:block;margin:8px 0 6px;font-size:15px;line-height:1.35}.pga-dataset p{margin:0;color:var(--muted);font-size:10px;line-height:1.5}.pga-dataset-meta{display:flex;gap:7px;flex-wrap:wrap;margin-top:13px}.pga-chip{display:inline-flex;align-items:center;gap:6px;min-height:26px;border:1px solid var(--line2);border-radius:999px;padding:4px 8px;color:var(--muted);font:850 9px var(--mono);letter-spacing:.04em}.pga-chip.env{border-color:#775a2a;color:var(--amber)}.pga-chip.good{border-color:#28786e;color:var(--acid2)}.pga-chip.bad{border-color:#784440;color:var(--red)}
  .pga-boundary{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:15px;align-items:center;padding:12px 38px;border-bottom:1px solid var(--line);background:#090d0f}.pga-boundary-mark{color:var(--acid);font:900 10px var(--mono);letter-spacing:.1em;text-transform:uppercase}.pga-boundary p{margin:0;color:var(--muted);font-size:11px;line-height:1.55}.pga-boundary p strong{color:var(--ink)}.pga-safety{border:1px solid var(--line2);padding:5px 9px;color:var(--faint);font:850 9px var(--mono);letter-spacing:.05em;text-transform:uppercase;white-space:nowrap}
  .pga-headlines{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-bottom:1px solid var(--line);background:var(--panel)}.pga-headline{position:relative;min-width:0;padding:18px 20px;border-right:1px solid var(--line)}.pga-headline:last-child{border-right:0}.pga-headline span{display:block;color:var(--faint);font:850 9px var(--mono);letter-spacing:.07em;text-transform:uppercase}.pga-headline strong{display:block;margin:7px 0 4px;font:900 24px var(--mono);letter-spacing:-.04em}.pga-headline small{color:var(--muted);font-size:10px;line-height:1.4}.pga-headline strong b{color:var(--acid);font:inherit}.pga-integrity{display:inline-flex;align-items:center;gap:6px;color:var(--acid);font:900 10px var(--mono);letter-spacing:.04em}.pga-integrity:before{content:"";width:7px;height:7px;border-radius:50%;background:currentColor}.pga-integrity.bad{color:var(--red)}
  .pga-section{padding:20px 24px 0}.pga-section-head{display:flex;justify-content:space-between;align-items:flex-end;gap:18px;margin:0 0 12px}.pga-section-head span{display:block;color:var(--acid);font:900 9px var(--mono);letter-spacing:.09em;text-transform:uppercase}.pga-section-head h2{margin:5px 0 0;font-size:17px}.pga-section-head p{max-width:590px;margin:0;color:var(--faint);font-size:10px;line-height:1.5;text-align:right}
  .pga-funnel{display:grid;grid-template-columns:repeat(6,minmax(125px,1fr));gap:7px}.pga-stage{position:relative;min-width:0;border:1px solid var(--line);border-top:3px solid var(--acid);background:var(--panel);padding:14px 13px;overflow:hidden}.pga-stage:not(:last-child):after{content:"→";position:absolute;right:-7px;top:50%;z-index:2;color:var(--acid);font:900 11px var(--mono)}.pga-stage.incoherent{border-top-color:var(--red)}.pga-stage-index{display:flex;justify-content:space-between;gap:7px;color:var(--faint);font:850 8px var(--mono);letter-spacing:.06em}.pga-stage h3{min-height:34px;margin:9px 0 5px;font-size:12px;line-height:1.35}.pga-stage-count{display:block;font:900 22px var(--mono);letter-spacing:-.04em}.pga-stage-rate{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:11px;padding-top:9px;border-top:1px solid var(--line)}.pga-stage-rate span{color:var(--faint);font:750 8px var(--mono);text-transform:uppercase}.pga-stage-rate b{display:block;margin-top:3px;color:var(--muted);font:850 10px var(--mono)}.pga-stage-track{height:3px;margin-top:11px;background:var(--soft)}.pga-stage-fill{display:block;height:100%;width:var(--fill);background:var(--acid)}.pga-stage p{margin:9px 0 0;color:var(--faint);font-size:9px;line-height:1.45}
  .pga-grid{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(315px,.8fr);gap:14px;padding:16px 24px 24px}.pga-main,.pga-side{display:grid;gap:14px;align-content:start;min-width:0}.pga-panel{min-width:0;border:1px solid var(--line);background:var(--panel);overflow:hidden}.pga-panel-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;padding:15px 17px 13px;border-bottom:1px solid var(--line)}.pga-panel-head h2{margin:0;font-size:15px}.pga-panel-head p{margin:4px 0 0;color:var(--muted);font-size:10px;line-height:1.45}.pga-count{border:1px solid var(--line2);padding:4px 7px;color:var(--muted);font:850 9px var(--mono);white-space:nowrap}
  .pga-table-wrap{overflow-x:auto}.pga-table{width:100%;border-collapse:collapse;min-width:680px}.pga-table th{padding:9px 12px;border-bottom:1px solid var(--line);color:var(--faint);font:850 8px var(--mono);letter-spacing:.07em;text-align:left;text-transform:uppercase}.pga-table td{padding:11px 12px;border-bottom:1px solid var(--line);color:var(--muted);font-size:10px;vertical-align:middle}.pga-table tr:last-child td{border-bottom:0}.pga-table strong{display:block;color:var(--ink);font-size:10px;line-height:1.35}.pga-table small{display:block;margin-top:3px;color:var(--faint);font-size:8px;line-height:1.4}.pga-table .numeric{text-align:right;font-family:var(--mono);white-space:nowrap}.pga-revenue-cell{min-width:125px}.pga-mini-track{height:3px;margin-top:5px;background:var(--soft)}.pga-mini-fill{display:block;width:var(--fill);height:100%;background:linear-gradient(90deg,var(--acid),#357e76)}
  .pga-truth{display:inline-flex;align-items:center;gap:5px;border:1px solid var(--line2);border-radius:999px;padding:4px 6px;color:var(--faint);font:900 7px var(--mono);letter-spacing:.04em;white-space:nowrap}.pga-truth:before{content:"";width:5px;height:5px;border-radius:50%;background:currentColor}.pga-truth.measured{border-color:#27796e;color:var(--acid)}.pga-truth.simulated{border-color:#765f2c;color:var(--amber)}.pga-truth.unavailable{border-color:#68423f;color:var(--red)}
  .pga-source-affiliate{display:inline-flex;margin-top:4px;border:1px solid #4c405d;border-radius:999px;padding:2px 6px;color:var(--violet);font:800 7px var(--mono)}.pga-confidence{display:inline-flex;align-items:center;gap:5px;color:var(--muted);font:800 8px var(--mono)}.pga-confidence:before{content:"";width:5px;height:5px;border-radius:50%;background:var(--amber)}.pga-confidence.high:before{background:var(--acid)}.pga-confidence.low:before,.pga-confidence.unknown:before{background:var(--red)}
  .pga-webinars{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;padding:10px}.pga-webinar{min-width:0;border:1px solid var(--line);border-top:3px solid var(--blue);background:var(--lift);padding:14px}.pga-webinar-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.pga-webinar h3{margin:0;font-size:12px;line-height:1.4}.pga-webinar-sub{margin:5px 0 12px;color:var(--faint);font-size:9px}.pga-webinar-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}.pga-webinar-metrics span{min-width:0;padding:7px;border:1px solid var(--line);background:var(--panel)}.pga-webinar-metrics small{display:block;color:var(--faint);font:750 7px var(--mono);text-transform:uppercase}.pga-webinar-metrics b{display:block;margin-top:4px;color:var(--ink);font:900 11px var(--mono)}.pga-webinar-foot{display:flex;justify-content:space-between;gap:9px;margin-top:11px;padding-top:9px;border-top:1px solid var(--line);color:var(--muted);font:800 9px var(--mono)}.pga-webinar-foot strong{color:var(--acid2)}
  .pga-cohorts{display:grid;grid-template-columns:repeat(5,minmax(105px,1fr));gap:6px;padding:11px}.pga-cohort{min-width:0;border:1px solid var(--line);background:var(--lift);padding:10px}.pga-cohort .pga-truth{margin-top:8px}.pga-cohort h3{margin:0;color:var(--muted);font:850 9px var(--mono)}.pga-cohort-bookings{display:block;margin:8px 0 2px;font:900 19px var(--mono)}.pga-cohort small{display:block;color:var(--faint);font-size:8px}.pga-cohort-track{display:flex;align-items:flex-end;height:54px;margin:10px 0 8px;border-bottom:1px solid var(--line)}.pga-cohort-bar{display:block;width:100%;height:var(--fill);min-height:3px;background:linear-gradient(180deg,var(--acid),#26665f)}.pga-cohort-foot{display:flex;justify-content:space-between;gap:4px;color:var(--muted);font:800 8px var(--mono)}
  .pga-identity{padding:16px}.pga-identity-main{display:grid;grid-template-columns:94px minmax(0,1fr);gap:15px;align-items:center}.pga-identity-ring{--score:0deg;position:relative;width:92px;height:92px;display:grid;place-items:center;border-radius:50%;background:conic-gradient(var(--acid) var(--score),var(--soft) 0)}.pga-identity-ring:before{content:"";position:absolute;inset:7px;border-radius:50%;background:var(--panel)}.pga-identity-ring strong{position:relative;font:900 16px var(--mono)}.pga-identity-copy span{color:var(--acid);font:900 8px var(--mono);letter-spacing:.08em;text-transform:uppercase}.pga-identity-copy h3{margin:6px 0 5px;font-size:15px}.pga-identity-copy p{margin:0;color:var(--muted);font-size:9px;line-height:1.5}.pga-identity-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:14px}.pga-identity-grid span{padding:8px;border:1px solid var(--line);background:var(--lift)}.pga-identity-grid small{display:block;color:var(--faint);font:750 7px var(--mono);text-transform:uppercase}.pga-identity-grid b{display:block;margin-top:4px;font:900 11px var(--mono)}
  .pga-quality{list-style:none;margin:0;padding:4px 14px}.pga-quality li{display:grid;grid-template-columns:minmax(0,1fr) 54px;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid var(--line)}.pga-quality li:last-child{border-bottom:0}.pga-quality strong{display:block;font-size:10px}.pga-quality p{margin:3px 0 0;color:var(--faint);font-size:8px;line-height:1.4}.pga-quality-score{text-align:right;color:var(--amber);font:900 11px var(--mono)}.pga-quality-score.strong{color:var(--acid)}.pga-quality-score.weak,.pga-quality-score.unknown{color:var(--red)}
  .pga-ledger{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;padding:14px}.pga-ledger span{border:1px solid var(--line);background:var(--lift);padding:10px;text-align:center}.pga-ledger small{display:block;color:var(--faint);font:750 7px var(--mono);text-transform:uppercase}.pga-ledger b{display:block;margin-top:5px;font:900 17px var(--mono)}.pga-ledger .measured b{color:var(--acid)}.pga-ledger .simulated b{color:var(--amber)}.pga-ledger .unavailable b{color:var(--red)}.pga-ledger-note{margin:0;padding:0 14px 14px;color:var(--muted);font-size:9px;line-height:1.5}.pga-truncation{margin:0 24px 22px;border:1px solid #765f2c;background:rgba(255,200,91,.05);padding:11px 13px;color:var(--amber);font-size:10px;line-height:1.5}
  .pga-footer{display:flex;justify-content:space-between;gap:18px;padding:13px 24px;border-top:1px solid var(--line);background:#090d0f;color:var(--faint);font-size:9px;line-height:1.5}.pga-footer strong{color:var(--muted)}
  @media(max-width:1100px){.pga-funnel{grid-template-columns:repeat(3,minmax(0,1fr))}.pga-stage:not(:last-child):after{display:none}.pga-grid{grid-template-columns:1fr}.pga-side{grid-template-columns:repeat(2,minmax(0,1fr))}.pga-side .pga-panel:last-child{grid-column:1/-1}.pga-cohorts{grid-template-columns:repeat(5,minmax(90px,1fr))}}
  @media(max-width:760px){.pga-hero{grid-template-columns:1fr;padding:28px 20px 23px}.pga-hero h1{font-size:clamp(2.45rem,13vw,4.1rem)}.pga-boundary{grid-template-columns:1fr;padding:12px 20px}.pga-safety{justify-self:start}.pga-headlines{grid-template-columns:repeat(2,1fr)}.pga-headline:nth-child(2){border-right:0}.pga-headline:nth-child(-n+2){border-bottom:1px solid var(--line)}.pga-section{padding:17px 14px 0}.pga-section-head{align-items:flex-start;flex-direction:column}.pga-section-head p{text-align:left}.pga-grid{padding:14px}.pga-webinars{grid-template-columns:1fr}.pga-cohorts{grid-template-columns:repeat(3,minmax(0,1fr))}.pga-side{grid-template-columns:1fr}.pga-side .pga-panel:last-child{grid-column:auto}.pga-footer{flex-direction:column;padding:13px 14px}}
  @media(max-width:480px){.pga-hero{padding-inline:16px}.pga-hero h1{letter-spacing:-.05em}.pga-headlines{grid-template-columns:1fr}.pga-headline{border-right:0!important;border-bottom:1px solid var(--line)}.pga-headline:last-child{border-bottom:0}.pga-funnel{grid-template-columns:1fr}.pga-stage{min-height:150px}.pga-webinar-metrics{grid-template-columns:repeat(2,1fr)}.pga-cohorts{grid-template-columns:repeat(2,1fr)}.pga-identity-main{grid-template-columns:1fr}.pga-identity-ring{margin:auto}.pga-identity-copy{text-align:center}.pga-footer{font-size:8px}}
  @media(forced-colors:active){.pga,.pga-panel,.pga-stage,.pga-webinar,.pga-cohort,.pga-dataset{border-color:CanvasText}.pga-stage-fill,.pga-mini-fill,.pga-cohort-bar,.pga-truth:before,.pga-integrity:before{background:Highlight}.pga-truth{border:1px solid CanvasText}}
  @media(prefers-reduced-motion:reduce){.pga *{scroll-behavior:auto!important;animation:none!important;transition:none!important}}
`;

function safeCount(value: number): string {
  return new Intl.NumberFormat('en-GB').format(Math.max(0, Math.round(value)));
}

function fill(value: number): string {
  return `${Math.max(0, Math.min(100, Number.isFinite(value) ? value : 0)).toFixed(1)}%`;
}

function degrees(value: number): string {
  const percent = Math.max(0, Math.min(100, Number.isFinite(value) ? value : 0));
  return `${(percent * 3.6).toFixed(1)}deg`;
}

function truthBadge(row: AnalyticsTruthView): string {
  const evidence = row.evidenceRef ? ` · ${row.evidenceRef}` : '';
  return `<span class="pga-truth ${escapeHtml(row.truth)}" title="${escapeHtml(`${row.truthDetail}${evidence}`)}">${escapeHtml(row.truthLabel)}</span>`;
}

function funnelStage(row: AnalyticsFunnelMilestoneView): string {
  return `<article class="pga-stage${row.coherent ? '' : ' incoherent'}" aria-label="${escapeHtml(row.label)}: ${escapeHtml(row.peopleLabel)} people">
    <div class="pga-stage-index"><span>${escapeHtml(row.indexLabel)}</span>${truthBadge(row)}</div><h3>${escapeHtml(row.label)}</h3><strong class="pga-stage-count">${escapeHtml(row.peopleLabel)}</strong>
    <div class="pga-stage-rate"><span>From prior<b>${escapeHtml(row.stepConversionLabel)}</b></span><span>From entry<b>${escapeHtml(row.totalConversionLabel)}</b></span></div>
    <div class="pga-stage-track" aria-hidden="true"><span class="pga-stage-fill" style="--fill:${fill(row.widthPercent)}"></span></div><p>${escapeHtml(row.operatorMeaning)}</p>
  </article>`;
}

function contentRow(row: AnalyticsContentAttributionView): string {
  return `<tr><td><strong>${escapeHtml(row.title)}</strong><small>${escapeHtml(row.format)} · <code>${escapeHtml(row.contentVersionId)}</code></small></td><td>${escapeHtml(row.attributionModelLabel)}</td><td class="numeric">${escapeHtml(row.influencedPeopleLabel)}</td><td class="numeric">${escapeHtml(row.bookedConversionsLabel)}</td><td class="numeric pga-revenue-cell"><strong>${escapeHtml(row.revenueLabel)}</strong><div class="pga-mini-track" aria-hidden="true"><span class="pga-mini-fill" style="--fill:${fill(row.revenueWidthPercent)}"></span></div></td><td>${truthBadge(row)}</td></tr>`;
}

function sourceRow(row: AnalyticsSourceAttributionView): string {
  const affiliate = row.affiliateLabel ? `<span class="pga-source-affiliate">Affiliate · ${escapeHtml(row.affiliateLabel)}</span>` : '';
  return `<tr><td><strong>${escapeHtml(row.channelLabel)}</strong><small>${escapeHtml(row.sourceLabel)}</small>${affiliate}</td><td class="numeric">${escapeHtml(row.leadsLabel)}</td><td class="numeric">${escapeHtml(row.qualifiedLabel)}</td><td class="numeric">${escapeHtml(row.bookingsLabel)}</td><td class="numeric"><strong>${escapeHtml(row.revenueLabel)}</strong></td><td><span class="pga-confidence ${escapeHtml(row.identityConfidence)}">${escapeHtml(row.identityConfidenceLabel)}</span></td><td>${truthBadge(row)}</td></tr>`;
}

function webinarCard(row: AnalyticsWebinarContributionView): string {
  return `<article class="pga-webinar"><header class="pga-webinar-head"><h3>${escapeHtml(row.title)}</h3>${truthBadge(row)}</header><p class="pga-webinar-sub">${escapeHtml(row.sessionLabel)}</p><div class="pga-webinar-metrics"><span><small>Registered</small><b>${escapeHtml(row.registrationsLabel)}</b></span><span><small>Attended</small><b>${escapeHtml(row.attendedLabel)}</b></span><span><small>Replay</small><b>${escapeHtml(row.replayConsumersLabel)}</b></span><span><small>Bookings</small><b>${escapeHtml(row.bookingsLabel)}</b></span></div><footer class="pga-webinar-foot"><span>Attendance ${escapeHtml(row.attendanceRateLabel)}</span><strong>${escapeHtml(row.revenueLabel)}</strong></footer></article>`;
}

function cohortCard(row: AnalyticsCohortView): string {
  return `<article class="pga-cohort"><h3>${escapeHtml(row.label)}</h3><strong class="pga-cohort-bookings">${escapeHtml(row.bookingsLabel)}</strong><small>bookings · ${escapeHtml(row.conversionLabel)} of leads</small><div class="pga-cohort-track" aria-hidden="true"><span class="pga-cohort-bar" style="--fill:${fill(row.widthPercent)}"></span></div><div class="pga-cohort-foot"><span>${escapeHtml(row.leadsLabel)} leads</span><span>${escapeHtml(row.revenueLabel)}</span></div>${truthBadge(row)}</article>`;
}

function qualityRow(row: AnalyticsQualitySignalView): string {
  return `<li><div><strong>${escapeHtml(row.label)}</strong><p>${escapeHtml(row.detail)} · ${escapeHtml(row.truthLabel)}</p></div><span class="pga-quality-score ${escapeHtml(row.tone)}">${escapeHtml(row.scoreLabel)}</span></li>`;
}

export function renderGrowthAnalyticsBody(view: GrowthAnalyticsView): string {
  const stages = view.funnel.map(funnelStage).join('');
  const content = view.content.map(contentRow).join('');
  const sources = view.sources.map(sourceRow).join('');
  const webinars = view.webinars.map(webinarCard).join('');
  const cohorts = view.cohorts.map(cohortCard).join('');
  const quality = view.qualitySignals.map(qualityRow).join('');
  const integrityTone = view.integrity.coherent ? '' : ' bad';
  const truncation = view.inputTruncated
    ? '<p class="pga-truncation"><strong>Safe display bound reached.</strong> Some rows are omitted and the integrity state requires review; no totals should be treated as complete.</p>'
    : '';
  return `<style data-property-predator-growth-analytics>${GROWTH_ANALYTICS_STYLE}</style><article class="pga" aria-labelledby="pga-title" data-environment="${escapeHtml(view.environment)}" data-dataset-kind="${escapeHtml(view.datasetKind)}" data-read-only="true" data-provider-effects="none">
    <header class="pga-hero"><div class="pga-hero-copy"><div class="pga-kicker">Growth HQ · Analytics & attribution</div><h1 id="pga-title">Know what moved. <em>Prove what paid.</em></h1><p>One evidence-led view from first touch to revenue: milestone conversion, exact content versions, channels, affiliates, webinars and the identity confidence beneath every claim.</p></div><aside class="pga-dataset" aria-label="Analytics dataset boundary"><span>${escapeHtml(view.periodLabel)}</span><strong>${escapeHtml(view.datasetLabel)}</strong><p>${escapeHtml(view.workspaceName)} · snapshot ${escapeHtml(view.asOf)}</p><div class="pga-dataset-meta"><span class="pga-chip env">${escapeHtml(view.environmentLabel)}</span><span class="pga-chip${view.integrity.coherent ? ' good' : ' bad'}">${escapeHtml(view.integrity.label)}</span><span class="pga-chip">READ ONLY</span></div></aside></header>
    <section class="pga-boundary" aria-label="Analytics truth boundary"><span class="pga-boundary-mark">Truth boundary</span><p><strong>Measured is not a synonym for live.</strong> ${escapeHtml(view.datasetBoundary)}</p><span class="pga-safety">No send · publish · spend</span></section>
    <section class="pga-headlines" aria-label="Measured TEST headline metrics"><div class="pga-headline"><span>People entering funnel</span><strong><b>${escapeHtml(view.headline.peopleLabel)}</b></strong><small>Entry milestone in this bounded snapshot</small></div><div class="pga-headline"><span>Attributed bookings</span><strong>${escapeHtml(view.headline.bookingsLabel)}</strong><small>Measured source rows only</small></div><div class="pga-headline"><span>Attributed revenue</span><strong>${escapeHtml(view.headline.revenueLabel)}</strong><small>Measured source rows · attribution is not causation</small></div><div class="pga-headline"><span>Evidence integrity</span><strong class="pga-integrity${integrityTone}">${escapeHtml(view.integrity.label)}</strong><small>${escapeHtml(view.integrity.detail)}</small></div></section>
    <section class="pga-section" aria-labelledby="pga-funnel-title"><header class="pga-section-head"><div><span>01 · Journey conversion</span><h2 id="pga-funnel-title">Milestone truth, person by person</h2></div><p>Step conversion compares adjacent milestones. Entry conversion keeps the original captured cohort as the denominator. Contradictory sequences fail visibly.</p></header><div class="pga-funnel">${stages || '<p>No funnel evidence is available.</p>'}</div></section>
    <div class="pga-grid"><main class="pga-main">
      <section class="pga-panel" aria-labelledby="pga-content-title"><header class="pga-panel-head"><div><h2 id="pga-content-title">Content → revenue attribution</h2><p>Exact approved version, influence model, booked conversions and revenue contribution.</p></div><span class="pga-count">${safeCount(view.content.length)} versions</span></header><div class="pga-table-wrap"><table class="pga-table"><thead><tr><th>Content version</th><th>Model</th><th>Influenced</th><th>Bookings</th><th>Attributed revenue</th><th>Truth</th></tr></thead><tbody>${content || '<tr><td colspan="6">No content attribution rows.</td></tr>'}</tbody></table></div></section>
      <section class="pga-panel" aria-labelledby="pga-source-title"><header class="pga-panel-head"><div><h2 id="pga-source-title">Channel, source &amp; affiliate truth</h2><p>Affiliate provenance stays attached instead of being flattened into “other”.</p></div><span class="pga-count">${safeCount(view.sources.length)} sources</span></header><div class="pga-table-wrap"><table class="pga-table"><thead><tr><th>Acquisition truth</th><th>Leads</th><th>Qualified</th><th>Bookings</th><th>Revenue</th><th>Identity</th><th>Truth</th></tr></thead><tbody>${sources || '<tr><td colspan="7">No source attribution rows.</td></tr>'}</tbody></table></div></section>
      <section class="pga-panel" aria-labelledby="pga-webinar-title"><header class="pga-panel-head"><div><h2 id="pga-webinar-title">Webinar contribution</h2><p>Registration, live attendance and replay consumption stay separate.</p></div><span class="pga-count">${safeCount(view.webinars.length)} rooms</span></header><div class="pga-webinars">${webinars || '<p>No webinar evidence is available.</p>'}</div></section>
      <section class="pga-panel" aria-labelledby="pga-cohort-title"><header class="pga-panel-head"><div><h2 id="pga-cohort-title">Cohort trend</h2><p>Bookings and attributed value by entry cohort; planned cohorts remain simulated.</p></div><span class="pga-count">${safeCount(view.cohorts.length)} cohorts</span></header><div class="pga-cohorts">${cohorts || '<p>No cohort evidence is available.</p>'}</div></section>
    </main><aside class="pga-side">
      <section class="pga-panel" aria-labelledby="pga-identity-title"><header class="pga-panel-head"><div><h2 id="pga-identity-title">Identity confidence</h2><p>How much of the journey genuinely resolves to people.</p></div>${truthBadge(view.identity)}</header><div class="pga-identity"><div class="pga-identity-main"><div class="pga-identity-ring" style="--score:${degrees(view.identity.resolutionPercent ?? 0)}" role="img" aria-label="${escapeHtml(view.identity.resolutionLabel)} identity resolution"><strong>${escapeHtml(view.identity.resolutionLabel)}</strong></div><div class="pga-identity-copy"><span>${escapeHtml(view.identity.confidenceLabel)}</span><h3>${escapeHtml(view.identity.resolvedPeopleLabel)} resolved people</h3><p>Resolution is computed from stable people over total profiles in this evidence snapshot.</p></div></div><div class="pga-identity-grid"><span><small>Total profiles</small><b>${escapeHtml(view.identity.totalProfilesLabel)}</b></span><span><small>Unresolved touches</small><b>${escapeHtml(view.identity.unresolvedTouchesLabel)}</b></span><span><small>Duplicate candidates</small><b>${escapeHtml(view.identity.duplicateCandidatesLabel)}</b></span></div></div></section>
      <section class="pga-panel" aria-labelledby="pga-quality-title"><header class="pga-panel-head"><div><h2 id="pga-quality-title">Data quality watch</h2><p>Coverage scores explain where attribution can be trusted.</p></div><span class="pga-count">${safeCount(view.qualitySignals.length)}</span></header><ul class="pga-quality">${quality || '<li><div><strong>No quality signals</strong><p>Confidence remains unknown.</p></div></li>'}</ul></section>
      <section class="pga-panel" aria-labelledby="pga-ledger-title"><header class="pga-panel-head"><div><h2 id="pga-ledger-title">Truth ledger</h2><p>Every analytic row is classified before display.</p></div><span class="pga-count">${safeCount(view.truthLedger.invalidMeasured)} rejected claims</span></header><div class="pga-ledger"><span class="measured"><small>Measured</small><b>${safeCount(view.truthLedger.measured)}</b></span><span class="simulated"><small>Simulated</small><b>${safeCount(view.truthLedger.simulated)}</b></span><span class="unavailable"><small>Unavailable</small><b>${safeCount(view.truthLedger.unavailable)}</b></span></div><p class="pga-ledger-note">A measured row without an evidence reference and credible observation time is reclassified as unavailable. Simulated values never enter measured headline totals.</p></section>
    </aside></div>${truncation}<footer class="pga-footer"><span><strong>Attribution is a decision model, not causal proof.</strong> Compare first-touch, last-touch, linear and assisted views before moving budget.</span><span>${escapeHtml(view.environmentLabel)} · read-only · zero provider effects</span></footer>
  </article>`;
}
