import { escapeHtml } from './ui.js';
import {
  MIGRATION_CENTRE_CLIENT_ROUTE,
  MIGRATION_CENTRE_PREVIEW_ROUTE,
  PORTAL_MIGRATION_PREVIEW_LIMITS,
  type PortalMigrationRole,
} from './migration-centre-service.js';

const MIGRATION_CENTRE_STYLE = `
  .mig{--mig-bg:#050608;--mig-panel:#0b0e11;--mig-raised:#11161a;--mig-line:#293238;--mig-ink:#f4f7f7;--mig-muted:#a8b3b6;--mig-faint:#718086;--mig-teal:#00e5cc;--mig-teal-soft:#062c28;--mig-amber:#f2b84a;--mig-red:#ff756d;min-width:0;overflow:hidden;border:1px solid #010203;background:var(--mig-bg);color:var(--mig-ink);font-family:var(--sans,ui-sans-serif,system-ui,sans-serif)}
  .mig *{box-sizing:border-box}.mig h1,.mig h2,.mig h3,.mig h4,.mig p{margin-top:0}.mig code{font-family:var(--mono,ui-monospace,monospace);overflow-wrap:anywhere}.mig button,.mig input,.mig select{font:inherit}
  .mig-hero{position:relative;display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,350px);gap:28px;align-items:end;padding:30px;border-bottom:1px solid var(--mig-line);background:radial-gradient(circle at 80% -30%,rgba(0,229,204,.2),transparent 38%),linear-gradient(135deg,#12191c,#07090a 68%);overflow:hidden}.mig-hero::after{content:"";position:absolute;right:18%;top:-165px;width:255px;height:255px;border:1px solid rgba(0,229,204,.2);transform:rotate(30deg)}.mig-kicker{position:relative;color:var(--mig-teal);font:850 12px var(--mono,monospace);letter-spacing:.14em;text-transform:uppercase}.mig-hero h1{position:relative;margin:9px 0 10px;font-family:var(--display,var(--sans));font-size:clamp(2.4rem,5vw,5.2rem);font-weight:600;line-height:.9;letter-spacing:-.055em}.mig-hero h1 em{color:var(--mig-teal);font-style:normal}.mig-hero p{position:relative;max-width:760px;margin:0;color:var(--mig-muted);font-size:14px;line-height:1.7}.mig-lock-card{position:relative;z-index:1;border:1px solid #57602e;background:rgba(23,22,8,.78);padding:16px}.mig-lock-card strong{display:block;color:var(--mig-amber);font:900 12px var(--mono,monospace);letter-spacing:.1em;text-transform:uppercase}.mig-lock-card span{display:block;margin-top:8px;font-size:14px;font-weight:850}.mig-lock-card small{display:block;margin-top:6px;color:var(--mig-muted);font-size:12px;line-height:1.5}
  .mig-safety{display:grid;grid-template-columns:auto 1fr auto;gap:14px;align-items:center;padding:12px 30px;border-bottom:1px solid var(--mig-line);background:#080c0e}.mig-safety-mark{color:var(--mig-teal);font:900 11px var(--mono,monospace);letter-spacing:.08em;text-transform:uppercase}.mig-safety p{margin:0;color:var(--mig-muted);font-size:12px;line-height:1.5}.mig-safety-badge{border:1px solid #2b6f67;background:var(--mig-teal-soft);padding:5px 8px;color:var(--mig-teal);font:850 11px var(--mono,monospace);text-transform:uppercase;white-space:nowrap}
  .mig-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-bottom:1px solid var(--mig-line);background:var(--mig-panel)}.mig-step{display:grid;grid-template-columns:36px 1fr;gap:10px;padding:16px 18px;border-right:1px solid var(--mig-line)}.mig-step:last-child{border-right:0}.mig-step-number{width:32px;height:32px;display:grid;place-items:center;border:1px solid #2f756d;background:var(--mig-teal-soft);color:var(--mig-teal);font:900 12px var(--mono,monospace)}.mig-step strong{display:block;font-size:13px}.mig-step span{display:block;margin-top:4px;color:var(--mig-faint);font-size:11px;line-height:1.45}
  .mig-workspace{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(270px,.65fr);gap:12px;padding:12px}.mig-panel{min-width:0;border:1px solid var(--mig-line);background:var(--mig-panel)}.mig-panel-head{padding:16px 18px;border-bottom:1px solid var(--mig-line)}.mig-panel-head h2{margin:0;font-size:16px}.mig-panel-head p{margin:5px 0 0;color:var(--mig-muted);font-size:12px;line-height:1.55}.mig-panel-body{display:grid;gap:16px;padding:18px}.mig-field{display:grid;gap:6px}.mig-field label{color:var(--mig-muted);font-size:11px;font-weight:850}.mig-field input,.mig-field select{width:100%;min-height:46px;border:1px solid #39464c;border-radius:6px;background:#080b0d;color:var(--mig-ink);padding:9px 10px}.mig-field input:focus,.mig-field select:focus{outline:0;border-color:var(--mig-teal);box-shadow:0 0 0 3px rgba(0,229,204,.13)}.mig-field input[type=file]{padding:8px}.mig-file-note{margin:0;color:var(--mig-faint);font-size:11px;line-height:1.5}.mig-source-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mig-source-proof{border:1px solid var(--mig-line);background:#090d0f;padding:12px;color:var(--mig-muted);font-size:11px;line-height:1.55}.mig-source-proof strong{color:var(--mig-teal)}
  .mig-mapping[hidden],.mig-results[hidden]{display:none}.mig-mapping{border-top:1px solid var(--mig-line);padding-top:16px}.mig-mapping h3{font-size:14px;margin:0 0 5px}.mig-mapping>p{margin:0 0 12px;color:var(--mig-muted);font-size:11px;line-height:1.5}.mig-table-wrap{max-width:100%;overflow:auto;border:1px solid var(--mig-line)}.mig-table{width:100%;border-collapse:collapse;min-width:650px}.mig-table th,.mig-table td{padding:9px 10px;border-bottom:1px solid var(--mig-line);text-align:left;font-size:11px}.mig-table thead th{position:sticky;top:0;background:#0d1215;color:var(--mig-faint);font:850 10px var(--mono,monospace);text-transform:uppercase}.mig-table tbody th{max-width:210px;color:var(--mig-ink);font-weight:800;overflow-wrap:anywhere}.mig-table input[type=checkbox]{width:20px;height:20px;accent-color:var(--mig-teal)}.mig-table select{min-width:205px}.mig-preview-action{min-height:48px;border:1px solid #2d776e;border-radius:6px;background:#072720;color:var(--mig-teal);font-size:12px;font-weight:900;cursor:pointer}.mig-preview-action:hover{background:#09342d}.mig-preview-action[disabled],.mig[aria-busy=true] .mig-preview-action{opacity:.55;cursor:wait}.mig-status{min-height:1.5em;margin:0;color:var(--mig-faint);font-size:11px;line-height:1.5}.mig-status[data-kind=error]{color:var(--mig-red)}
  .mig-side-stack{display:grid;gap:12px;align-content:start}.mig-rule-list{list-style:none;margin:0;padding:0}.mig-rule-list li{padding:11px 0;border-top:1px solid var(--mig-line);color:var(--mig-muted);font-size:11px;line-height:1.5}.mig-rule-list li:first-child{border-top:0;padding-top:0}.mig-rule-list strong{display:block;margin-bottom:3px;color:var(--mig-ink);font-size:12px}.mig-rule-list .ready{color:var(--mig-teal)}.mig-rule-list .locked{color:var(--mig-amber)}
  .mig-results{margin:0 12px 12px;border:1px solid #2c7169;background:#09110f;padding:18px;outline:0}.mig-results h2{font-size:18px}.mig-results h3{margin:20px 0 9px;font-size:14px}.mig-result-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid var(--mig-line)}.mig-result-metric{padding:12px;border-right:1px solid var(--mig-line)}.mig-result-metric:last-child{border-right:0}.mig-result-metric span{display:block;color:var(--mig-faint);font:800 10px var(--mono,monospace);text-transform:uppercase}.mig-result-metric strong{display:block;margin-top:6px;color:var(--mig-teal);font:900 19px var(--mono,monospace)}.mig-record-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.mig-record-card{min-width:0;border:1px solid var(--mig-line);background:#0d1315;padding:12px}.mig-record-card h4{margin:0 0 9px;font-size:12px}.mig-record-section{padding-top:8px;margin-top:8px;border-top:1px solid var(--mig-line)}.mig-record-section>strong{color:var(--mig-muted);font-size:10px;text-transform:uppercase}.mig-record-section dl,.mig-receipt dl{display:grid;gap:6px;margin:8px 0 0}.mig-definition{display:grid;grid-template-columns:minmax(95px,.4fr) minmax(0,1fr);gap:8px}.mig-definition dt{color:var(--mig-faint);font-size:10px;text-transform:capitalize}.mig-definition dd{margin:0;color:var(--mig-ink);font-size:11px;overflow-wrap:anywhere}.mig-result-note{margin:9px 0;color:var(--mig-faint);font-size:11px}.mig-quarantine-list{display:grid;gap:6px;margin:0;padding-left:20px;color:var(--mig-muted);font-size:11px}.mig-receipt{margin-top:18px;border:1px solid var(--mig-line);background:#080c0d;padding:10px}.mig-receipt summary{color:var(--mig-teal);font:850 11px var(--mono,monospace);cursor:pointer;text-transform:uppercase}
  .mig-foot{display:flex;justify-content:space-between;gap:20px;padding:13px 18px;border-top:1px solid var(--mig-line);color:var(--mig-faint);font-size:11px;line-height:1.5}.mig-foot strong{color:var(--mig-muted)}
  @media(max-width:980px){.mig-workspace{grid-template-columns:1fr}.mig-side-stack{grid-template-columns:repeat(2,minmax(0,1fr))}.mig-record-grid{grid-template-columns:1fr}}
  @media(max-width:720px){.mig-hero{grid-template-columns:1fr;padding:23px 20px}.mig-safety{grid-template-columns:1fr;padding:12px 20px}.mig-safety-badge{justify-self:start}.mig-steps{grid-template-columns:1fr}.mig-step{border-right:0;border-bottom:1px solid var(--mig-line)}.mig-step:last-child{border-bottom:0}.mig-workspace{padding:8px}.mig-source-grid,.mig-side-stack{grid-template-columns:1fr}.mig-result-metrics{grid-template-columns:repeat(2,1fr)}.mig-result-metric:nth-child(2){border-right:0}.mig-result-metric:nth-child(n+3){border-top:1px solid var(--mig-line)}.mig-foot{flex-direction:column}}
  @media(max-width:460px){.mig-hero h1{font-size:2.55rem}.mig-result-metrics{grid-template-columns:1fr}.mig-result-metric{border-right:0}.mig-result-metric:nth-child(n+2){border-top:1px solid var(--mig-line)}.mig-definition{grid-template-columns:1fr}.mig-table{min-width:590px}}
  @media(forced-colors:active){.mig,.mig-panel,.mig-preview-action,.mig-lock-card,.mig-record-card{forced-color-adjust:auto}.mig-preview-action{border:2px solid ButtonText}}
  @media(prefers-reduced-motion:reduce){.mig *{scroll-behavior:auto!important;transition:none!important}}
`;

export interface MigrationCentrePageView {
  readonly workspaceName: string;
  readonly role: PortalMigrationRole;
  readonly csrfToken: string;
}
export function renderMigrationCentreBody(view: MigrationCentrePageView): string {
  const maxMegabytes = PORTAL_MIGRATION_PREVIEW_LIMITS.maxBytes / (1024 * 1024);
  return `<style>${MIGRATION_CENTRE_STYLE}</style><section class="mig" data-migration-centre data-preview-url="${MIGRATION_CENTRE_PREVIEW_ROUTE}" data-csrf="${escapeHtml(view.csrfToken)}">
    <header class="mig-hero"><div><div class="mig-kicker">Property Predator · controlled migration</div><h1>Bring your data.<br><em>Keep its truth.</em></h1><p>Map a real legacy CSV into the Growth HQ contact and lead shape, preserve its affiliate source, then inspect accepted and quarantined rows before anything is allowed near customer records.</p></div><aside class="mig-lock-card"><strong>Execution locked</strong><span>Preview is operational. Import is not.</span><small>No contact, opportunity, journey or provider record can be created from this screen. A separately reviewed executor is still required.</small></aside></header>
    <div class="mig-safety"><div class="mig-safety-mark">Effects-free boundary</div><p><strong>Raw rows exist only in request memory and this bounded response.</strong> Receipts contain hashes, provenance and counts—not CSV bodies or file names.</p><div class="mig-safety-badge">Founder / admin</div></div>
    <div class="mig-steps" aria-label="Migration preview stages"><div class="mig-step"><div class="mig-step-number">01</div><div><strong>Choose locally</strong><span>Your browser reads only the header until you explicitly request a preview.</span></div></div><div class="mig-step"><div class="mig-step-number">02</div><div><strong>Map deliberately</strong><span>Every destination and affiliate-source column is selected by you.</span></div></div><div class="mig-step"><div class="mig-step-number">03</div><div><strong>Inspect evidence</strong><span>Accepted rows, quarantine reasons and a signed receipt return to this session.</span></div></div></div>
    <div class="mig-workspace"><section class="mig-panel"><header class="mig-panel-head"><h2>CSV preview control</h2><p>Workspace: ${escapeHtml(view.workspaceName)} · authority: ${escapeHtml(view.role)} · maximum ${maxMegabytes} MB / ${PORTAL_MIGRATION_PREVIEW_LIMITS.maxRows.toLocaleString('en-GB')} rows.</p></header><div class="mig-panel-body">
      <div class="mig-source-grid"><div class="mig-field"><label for="migration-file">Legacy CSV file</label><input id="migration-file" data-migration-file type="file" accept=".csv,text/csv,application/csv" required><p class="mig-file-note">The file name stays in your browser and is never sent to Growth HQ.</p></div><div class="mig-field"><label for="migration-source">Source system</label><input id="migration-source" data-migration-source type="text" value="legacy-crm" maxlength="100" pattern="[A-Za-z0-9][A-Za-z0-9._:-]{0,99}" autocomplete="off" spellcheck="false"><p class="mig-file-note">Use a non-personal label such as <code>old-ghl</code> or <code>legacy-crm</code>.</p></div></div>
      <div class="mig-source-proof"><strong>Provenance stays attached.</strong> Source bytes, header shape, mapping, accepted rows and affiliate attribution are independently hashed into the preview receipt.</div>
      <section class="mig-mapping" data-migration-mapping-panel hidden><h3>Explicit column map</h3><p>Choose one Growth HQ destination per useful column. Mark affiliate/referral columns separately so attribution survives a later approved import.</p><div class="mig-table-wrap"><table class="mig-table"><thead><tr><th scope="col">CSV column</th><th scope="col">Growth HQ destination</th><th scope="col">Affiliate source</th><th scope="col">Required</th></tr></thead><tbody data-migration-mapping-body></tbody></table></div></section>
      <button class="mig-preview-action" data-migration-preview type="button">Run secure preview</button><p class="mig-status" data-migration-status data-kind="info" role="status" aria-live="polite">Choose a CSV file to begin. Nothing uploads automatically.</p>
    </div></section><aside class="mig-side-stack"><section class="mig-panel"><header class="mig-panel-head"><h2>Boundary status</h2></header><div class="mig-panel-body"><ul class="mig-rule-list"><li><strong class="ready">Real CSV parser ready</strong>Strict UTF-8, byte, row, column and cell limits.</li><li><strong class="ready">Affiliate provenance ready</strong>Exact selected values are bound into immutable hash evidence.</li><li><strong class="ready">Idempotency ready</strong>Identical retries replay; altered commands conflict.</li><li><strong class="locked">Customer import locked</strong>No repository or execution command is mounted.</li></ul></div></section><section class="mig-panel"><header class="mig-panel-head"><h2>Wide migration path</h2></header><div class="mig-panel-body"><ul class="mig-rule-list"><li><strong>CSV today</strong>Real preview, mapping and quarantine.</li><li><strong>Public API prepared</strong>Token hashing and rate-limit contracts exist, but token issuance and live routes remain dark.</li><li><strong>Executor later</strong>A separate transaction, duplicate policy and rollback review will be required before customer writes.</li></ul></div></section></aside></div>
    <section class="mig-results" data-migration-results tabindex="-1" aria-live="polite" hidden></section>
    <footer class="mig-foot"><span><strong>Privacy:</strong> no file names, secrets or CSV bodies enter receipts.</span><span><strong>Effects:</strong> customer writes 0 · provider calls 0 · external mutations 0.</span></footer>
  </section><script src="${MIGRATION_CENTRE_CLIENT_ROUTE}" defer></script>`;
}
