/** Server-rendered, side-effect-free Provider Connections & Launch Readiness UI. */

import { escapeHtml } from './ui.js';
import type {
  ProviderAdapterView,
  ProviderConnectionsView,
  ProviderProofView,
} from './provider-connections-presenter.js';

const PROVIDER_CONNECTIONS_STYLE = `
  .pcr{--bg:#07090b;--panel:#0d1114;--lift:#12181c;--soft:#090c0e;--line:#243038;--line2:#35444d;--ink:#f2f6f4;--muted:#a5b2b5;--faint:#78878c;--teal:#00e5cc;--teal-dim:#082923;--amber:#f2b84b;--red:#ff7169;--green:#73d7a2;min-width:0;background:var(--bg);border:1px solid #020304;color:var(--ink);font-family:var(--sans,ui-sans-serif,system-ui,sans-serif);overflow:hidden}.pcr *{box-sizing:border-box}.pcr h1,.pcr h2,.pcr h3,.pcr p{margin-top:0}.pcr code{font-family:var(--mono,ui-monospace,monospace);overflow-wrap:anywhere}.pcr-visually-hidden{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
  .pcr-hero{position:relative;display:grid;grid-template-columns:minmax(0,1fr) minmax(270px,350px);gap:28px;align-items:end;padding:31px 32px 26px;border-bottom:1px solid var(--line);background:radial-gradient(circle at 84% 10%,rgba(0,229,204,.15),transparent 31%),linear-gradient(135deg,#11181b,#07090b 68%);overflow:hidden}.pcr-hero:after{content:"";position:absolute;right:30%;top:-98px;width:215px;height:215px;border:1px solid rgba(0,229,204,.12);transform:rotate(45deg);pointer-events:none}.pcr-kicker{position:relative;color:var(--teal);font:850 12px/1.2 var(--mono,monospace);letter-spacing:.14em;text-transform:uppercase}.pcr-hero h1{position:relative;margin:10px 0 11px;font-family:var(--display,var(--sans));font-size:clamp(2.2rem,4.7vw,4.7rem);font-weight:600;line-height:.91;letter-spacing:-.045em}.pcr-hero h1 em{color:var(--teal);font-style:normal}.pcr-hero-copy>p{position:relative;max-width:760px;margin:0;color:var(--muted);font-size:14px;line-height:1.65}.pcr-target{position:relative;border:1px solid var(--line2);background:rgba(4,7,8,.75);padding:15px 16px}.pcr-target span{display:block;color:var(--faint);font:800 11px var(--mono,monospace);letter-spacing:.09em;text-transform:uppercase}.pcr-target strong{display:flex;align-items:center;gap:8px;margin:8px 0 6px;font:900 17px var(--mono,monospace)}.pcr-target strong:before{content:"";width:8px;height:8px;border-radius:50%;background:var(--red);box-shadow:0 0 0 5px rgba(255,113,105,.1)}.pcr-target small{display:block;color:var(--muted);font-size:12px;line-height:1.5}
  .pcr-boundary{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:14px;align-items:center;padding:12px 32px;border-bottom:1px solid var(--line);background:#090d0f}.pcr-boundary-mark{color:var(--teal);font:850 11px var(--mono,monospace);letter-spacing:.09em;text-transform:uppercase}.pcr-boundary p{margin:0;color:var(--muted);font-size:12px;line-height:1.5}.pcr-boundary p strong{color:var(--ink)}.pcr-safety{border:1px solid var(--line2);padding:5px 9px;color:var(--faint);font:800 11px var(--mono,monospace);letter-spacing:.05em;text-transform:uppercase;white-space:nowrap}.pcr-fixture{display:grid;grid-template-columns:auto minmax(0,1fr);gap:14px;align-items:center;padding:14px 32px;border-bottom:1px solid #806834;background:#1a1408;color:var(--amber)}.pcr-fixture strong{border:1px solid currentColor;padding:6px 9px;font:900 11px var(--mono,monospace);letter-spacing:.08em}.pcr-fixture p{margin:0;color:#dccb9d;font-size:12px;line-height:1.5}
  .pcr-gate{display:grid;grid-template-columns:minmax(250px,1fr) repeat(4,minmax(110px,150px));border-bottom:1px solid var(--line);background:var(--panel)}.pcr-gate-main{position:relative;padding:19px 22px;border-right:1px solid var(--line);overflow:hidden}.pcr-gate-main:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--red)}.pcr-gate-main.open:before{background:var(--teal)}.pcr-gate-label{display:flex;align-items:center;gap:9px;color:var(--red);font:900 12px var(--mono,monospace);letter-spacing:.08em;text-transform:uppercase}.pcr-gate-main.open .pcr-gate-label{color:var(--teal)}.pcr-gate-label b{border:1px solid currentColor;padding:3px 7px;font-size:10px}.pcr-gate-main h2{margin:8px 0 5px;font-size:19px}.pcr-gate-main p{margin:0;max-width:610px;color:var(--muted);font-size:12px;line-height:1.5}.pcr-stat{display:grid;align-content:center;padding:15px;border-right:1px solid var(--line)}.pcr-stat:last-child{border-right:0}.pcr-stat span{color:var(--faint);font:800 10px var(--mono,monospace);letter-spacing:.06em;text-transform:uppercase}.pcr-stat strong{margin-top:7px;font:900 20px var(--mono,monospace)}.pcr-stat strong b{color:var(--teal);font:inherit}.pcr-stat small{margin-top:3px;color:var(--muted);font-size:11px}
  .pcr-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(275px,330px);gap:14px;padding:16px}.pcr-catalog,.pcr-blockers{min-width:0;border:1px solid var(--line);background:var(--panel)}.pcr-section-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;padding:17px 18px 14px;border-bottom:1px solid var(--line)}.pcr-section-head h2{margin:0;font-size:16px}.pcr-section-head p{margin:4px 0 0;color:var(--muted);font-size:12px;line-height:1.45}.pcr-count{border:1px solid var(--line2);padding:4px 8px;color:var(--muted);font:800 11px var(--mono,monospace);white-space:nowrap}
  .pcr-adapters{list-style:none;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin:0;padding:10px}.pcr-card{min-width:0;border:1px solid var(--line);border-top:3px solid var(--red);border-radius:7px;background:var(--lift);overflow:hidden}.pcr-card.ready{border-top-color:var(--teal)}.pcr-card.wait{border-top-color:var(--amber)}.pcr-card-head{display:grid;grid-template-columns:36px minmax(0,1fr) auto;gap:10px;align-items:start;padding:14px 14px 12px;border-bottom:1px solid var(--line)}.pcr-index{width:34px;height:34px;display:grid;place-items:center;border:1px solid var(--line2);color:var(--teal);font:900 11px var(--mono,monospace)}.pcr-identity{min-width:0}.pcr-category{display:block;color:var(--faint);font:800 10px var(--mono,monospace);letter-spacing:.07em;text-transform:uppercase}.pcr-card h3{margin:5px 0 0;font-size:15px;line-height:1.3}.pcr-env{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--line2);border-radius:999px;padding:5px 8px;color:var(--muted);font:900 10px var(--mono,monospace);letter-spacing:.05em}.pcr-env:before{content:"";width:6px;height:6px;border-radius:50%;background:#8db7ff}.pcr-env.live{border-color:#6a463f;color:#ffaca6}.pcr-env.live:before{background:var(--red)}.pcr-status{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:12px 14px;border-bottom:1px solid var(--line)}.pcr-status-copy strong{display:flex;align-items:center;gap:7px;font-size:12px}.pcr-status-copy strong:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--red)}.pcr-card.ready .pcr-status-copy strong:before{background:var(--teal)}.pcr-card.wait .pcr-status-copy strong:before{background:var(--amber)}.pcr-status-copy p{margin:5px 0 0;color:var(--muted);font-size:11px;line-height:1.5}.pcr-health{align-self:start;min-width:88px;border:1px solid var(--line2);padding:6px 7px;text-align:right}.pcr-health span{display:block;color:var(--faint);font:800 9px var(--mono,monospace);text-transform:uppercase}.pcr-health strong{display:block;margin-top:3px;color:var(--red);font:900 10px var(--mono,monospace);text-transform:uppercase}.pcr-health.ready strong{color:var(--teal)}.pcr-health.wait strong{color:var(--amber)}
  .pcr-capabilities{display:flex;gap:5px;flex-wrap:wrap;padding:10px 14px;border-bottom:1px solid var(--line)}.pcr-capability{border:1px solid var(--line2);border-radius:999px;padding:3px 7px;color:var(--muted);font-size:10px}.pcr-proof-list{list-style:none;margin:0;padding:3px 14px}.pcr-proof{display:grid;grid-template-columns:22px minmax(0,1fr) auto;gap:8px;align-items:start;padding:9px 0;border-bottom:1px solid var(--line)}.pcr-proof:last-child{border-bottom:0}.pcr-proof-mark{width:19px;height:19px;display:grid;place-items:center;border:1px solid var(--line2);border-radius:50%;color:var(--red);font:900 10px var(--mono,monospace)}.pcr-proof.pass .pcr-proof-mark{border-color:#2a7b70;color:var(--teal)}.pcr-proof.wait .pcr-proof-mark{border-color:#806834;color:var(--amber)}.pcr-proof.muted .pcr-proof-mark{color:var(--faint)}.pcr-proof-copy strong{display:block;font-size:11px}.pcr-proof-copy p{margin:3px 0 0;color:var(--faint);font-size:10px;line-height:1.4}.pcr-proof-state{color:var(--red);font:900 9px var(--mono,monospace);text-transform:uppercase}.pcr-proof.pass .pcr-proof-state{color:var(--teal)}.pcr-proof.wait .pcr-proof-state{color:var(--amber)}.pcr-proof.muted .pcr-proof-state{color:var(--faint)}.pcr-setup{border-top:1px solid var(--line);background:var(--soft)}.pcr-setup summary{min-height:46px;display:flex;align-items:center;justify-content:space-between;gap:8px;padding:0 14px;list-style:none;color:var(--teal);font:900 10px var(--mono,monospace);letter-spacing:.04em;text-transform:uppercase;cursor:pointer}.pcr-setup summary::-webkit-details-marker{display:none}.pcr-setup summary:after{content:"+";font-size:16px}.pcr-setup[open] summary:after{content:"−"}.pcr-setup div{padding:0 14px 13px}.pcr-setup p{margin:0;color:var(--muted);font-size:11px;line-height:1.5}.pcr-setup small{display:block;margin-top:7px;color:var(--faint);font-size:10px}.pcr-card-foot{display:flex;justify-content:space-between;gap:10px;padding:9px 14px;border-top:1px solid var(--line);color:var(--faint);font:800 9px var(--mono,monospace);text-transform:uppercase}
  .pcr-blockers{position:sticky;top:86px}.pcr-blocker-list{list-style:none;margin:0;padding:6px 14px}.pcr-blocker{display:grid;grid-template-columns:25px minmax(0,1fr);gap:9px;padding:11px 0;border-bottom:1px solid var(--line)}.pcr-blocker:last-child{border-bottom:0}.pcr-blocker-index{width:24px;height:24px;display:grid;place-items:center;border:1px solid #70423d;color:var(--red);font:900 9px var(--mono,monospace)}.pcr-blocker strong{display:block;font-size:11px}.pcr-blocker span{display:block;margin-top:3px;color:var(--muted);font-size:10px;line-height:1.45}.pcr-blocker-more{margin:0;padding:11px 14px;border-top:1px solid var(--line);color:var(--faint);font-size:10px}.pcr-empty{padding:27px 18px;text-align:center}.pcr-empty-mark{width:38px;height:38px;margin:0 auto 10px;display:grid;place-items:center;border:1px solid #2a7b70;color:var(--teal);font:900 15px var(--mono,monospace)}.pcr-empty strong{font-size:12px}.pcr-empty p{margin:6px 0 0;color:var(--muted);font-size:11px;line-height:1.5}.pcr-truncation{padding:10px 18px;border-top:1px solid var(--line);color:var(--amber);font-size:11px}.pcr-footer{display:flex;justify-content:space-between;gap:14px;padding:13px 18px;border-top:1px solid var(--line);background:#080a0c;color:var(--faint);font-size:11px}.pcr-footer strong{color:var(--muted)}
  @media(max-width:1100px){.pcr-gate{grid-template-columns:minmax(250px,1fr) repeat(2,minmax(110px,1fr))}.pcr-stat:nth-child(n+4){border-top:1px solid var(--line)}.pcr-layout{grid-template-columns:minmax(0,1fr) 290px}.pcr-adapters{grid-template-columns:1fr}}
  @media(max-width:820px){.pcr-hero{grid-template-columns:1fr;padding:24px 20px 21px}.pcr-boundary{grid-template-columns:1fr;padding:12px 20px}.pcr-safety{justify-self:start}.pcr-gate{grid-template-columns:repeat(2,minmax(0,1fr))}.pcr-gate-main{grid-column:1/-1;border-right:0}.pcr-stat{border-top:1px solid var(--line)}.pcr-stat:nth-child(odd){border-right:0}.pcr-layout{grid-template-columns:1fr;padding:10px}.pcr-blockers{position:static;grid-row:1}}
  @media(max-width:520px){.pcr-hero h1{font-size:2.35rem}.pcr-gate{grid-template-columns:1fr}.pcr-gate-main{grid-column:auto}.pcr-stat,.pcr-stat:nth-child(odd){border-right:0}.pcr-section-head,.pcr-footer{align-items:stretch;flex-direction:column}.pcr-card-head{grid-template-columns:36px minmax(0,1fr)}.pcr-env{grid-column:2;justify-self:start}.pcr-status{grid-template-columns:1fr}.pcr-health{width:100%;text-align:left}.pcr-proof{grid-template-columns:22px minmax(0,1fr)}.pcr-proof-state{grid-column:2}.pcr-card-foot{flex-direction:column}}
  @media(forced-colors:active){.pcr,.pcr-card,.pcr-catalog,.pcr-blockers,.pcr-target,.pcr-proof-mark{forced-color-adjust:auto}.pcr-card{border-top-width:5px}}
  @media(prefers-reduced-motion:reduce){.pcr *{scroll-behavior:auto!important;transition:none!important}}
`;

function safeCount(value: number): string {
  return String(Math.max(0, Math.min(Math.floor(value), 9_999)));
}

function time(value: string | null): string {
  return value
    ? `<time datetime="${escapeHtml(value)}">${escapeHtml(value.replace('T', ' ').replace('.000Z', ' UTC'))}</time>`
    : 'Not recorded';
}

function proofRow(proof: ProviderProofView): string {
  const mark = proof.tone === 'pass' ? '✓' : proof.tone === 'wait' ? '…' : proof.tone === 'muted' ? '–' : '!';
  const evidence = proof.evidenceRef
    ? ` Evidence <code>${escapeHtml(proof.evidenceRef)}</code>.`
    : '';
  return `<li class="pcr-proof ${escapeHtml(proof.tone)}"><span class="pcr-proof-mark" aria-hidden="true">${mark}</span><div class="pcr-proof-copy"><strong>${escapeHtml(proof.label)}${proof.required ? '' : ' · optional'}</strong><p>${escapeHtml(proof.detail)}${evidence}</p></div><span class="pcr-proof-state">${escapeHtml(proof.stateLabel)}</span></li>`;
}

function adapterCard(adapter: ProviderAdapterView): string {
  const capabilities = adapter.capabilities.map((capability) =>
    `<span class="pcr-capability">${escapeHtml(capability)}</span>`).join('');
  const proofs = adapter.proofs.map(proofRow).join('');
  const statusTone = adapter.gatePasses ? 'ready' : adapter.connectionTone;
  const healthMoment = adapter.health.checkedAt ? `Checked ${time(adapter.health.checkedAt)}` : 'No probe recorded';
  const latency = adapter.health.latencyMs === null ? '' : ` · ${safeCount(adapter.health.latencyMs)}ms`;
  return `<li><article class="pcr-card ${escapeHtml(statusTone)}" id="${escapeHtml(adapter.anchorId)}" aria-labelledby="${escapeHtml(adapter.anchorId)}-title">
    <header class="pcr-card-head"><span class="pcr-index" aria-hidden="true">${escapeHtml(adapter.categoryIndex)}</span><div class="pcr-identity"><span class="pcr-category">${escapeHtml(adapter.categoryLabel)}</span><h3 id="${escapeHtml(adapter.anchorId)}-title">${escapeHtml(adapter.providerLabel)}</h3></div><span class="pcr-env ${escapeHtml(adapter.environment)}" aria-label="Environment ${escapeHtml(adapter.environmentLabel)}">${escapeHtml(adapter.environmentLabel)}</span></header>
    <section class="pcr-status"><div class="pcr-status-copy"><strong>${escapeHtml(adapter.connectionLabel)}</strong><p>${escapeHtml(adapter.statusDetail)}</p></div><div class="pcr-health ${escapeHtml(adapter.health.tone)}"><span>Adapter health</span><strong>${escapeHtml(adapter.health.label)}</strong></div></section>
    <div class="pcr-capabilities" aria-label="Supported capability contract">${capabilities || '<span class="pcr-capability">No capability contract</span>'}</div>
    <ul class="pcr-proof-list" aria-label="Required launch proofs">${proofs || '<li class="pcr-proof fail"><span class="pcr-proof-mark" aria-hidden="true">!</span><div class="pcr-proof-copy"><strong>No proofs declared</strong><p>The launch gate fails closed when required evidence is absent.</p></div><span class="pcr-proof-state">Missing</span></li>'}</ul>
    <details class="pcr-setup"><summary>${adapter.gatePasses ? 'Review verified setup' : 'Setup required · view brief'}</summary><div><p>${escapeHtml(adapter.nextStep)}</p><small>This is guidance only. It does not start OAuth, submit credentials or contact a provider.</small></div></details>
    <footer class="pcr-card-foot"><span>${safeCount(adapter.verifiedProofCount)} / ${safeCount(adapter.requiredProofCount)} required proofs</span><span>${healthMoment}${latency}</span></footer>
  </article></li>`;
}

function blockerPanel(view: ProviderConnectionsView): string {
  const visible = view.launchGate.blockers.slice(0, 12);
  const items = visible.map((blocker, index) => `<li class="pcr-blocker"><span class="pcr-blocker-index" aria-hidden="true">${String(index + 1).padStart(2, '0')}</span><div><strong>${escapeHtml(blocker.categoryLabel)} · ${escapeHtml(blocker.providerLabel)}</strong><span>${escapeHtml(blocker.reason)}</span></div></li>`).join('');
  const body = items
    ? `<ol class="pcr-blocker-list">${items}</ol>`
    : `<div class="pcr-empty"><span class="pcr-empty-mark" aria-hidden="true">✓</span><strong>No launch blockers in this snapshot.</strong><p>The deterministic gate will open only while every required proof remains current.</p></div>`;
  const hiddenCount = view.launchGate.blockerCount - visible.length;
  const more = hiddenCount > 0
    ? `<p class="pcr-blocker-more">${safeCount(hiddenCount)} more blocking checks are held in the bounded status model.</p>`
    : '';
  return `<aside class="pcr-blockers" aria-labelledby="pcr-blockers-title"><header class="pcr-section-head"><div><h2 id="pcr-blockers-title">Launch blockers</h2><p>Exact reasons the ${escapeHtml(view.targetEnvironmentLabel)} gate cannot open.</p></div><span class="pcr-count">${safeCount(view.launchGate.blockerCount)}</span></header>${body}${more}</aside>`;
}

export function renderProviderConnectionsBody(view: ProviderConnectionsView): string {
  const cards = view.adapters.map(adapterCard).join('');
  const gateTone = view.launchGate.open ? 'open' : 'closed';
  const truncation = view.inputTruncated
    ? '<p class="pcr-truncation">The adapter catalogue exceeded its safe display bound. The launch gate remains closed until the complete required set is evaluated.</p>'
    : '';
  const fixtureBoundary = view.illustrative
    ? '<section class="pcr-fixture" role="status" aria-label="Illustrative fixture boundary"><strong>TEST FIXTURE / ILLUSTRATIVE</strong><p>Every provider status and proof on this screen is fictional demonstration data. “Simulated proof passed” is not provider verification and cannot open a live launch gate.</p></section>'
    : '';
  return `<style data-property-predator-provider-connections>${PROVIDER_CONNECTIONS_STYLE}</style><article class="pcr" aria-labelledby="pcr-title">
    <header class="pcr-hero"><div class="pcr-hero-copy"><div class="pcr-kicker">Growth HQ · Provider control plane</div><h1 id="pcr-title">Connections without <em>blind spots.</em></h1><p>One premium control room for every delivery rail: what exists, what is healthy, what evidence is missing and exactly why live launch is still locked.</p></div><aside class="pcr-target" aria-label="Target launch environment"><span>Launch target</span><strong>${escapeHtml(view.targetEnvironmentLabel)} environment</strong><small>${escapeHtml(view.workspaceName)} · snapshot ${time(view.asOf)}</small></aside></header>
    <section class="pcr-boundary" aria-label="Provider security boundary"><span class="pcr-boundary-mark">Security boundary</span><p><strong>Status only.</strong> This screen never accepts or displays API keys, access tokens, webhook secrets or OAuth codes. It cannot connect, send, publish or charge.</p><span class="pcr-safety">No secrets · no side effects</span></section>${fixtureBoundary}
    <section class="pcr-gate" aria-label="Deterministic live launch gate"><div class="pcr-gate-main ${gateTone}"><span class="pcr-gate-label">Deterministic launch gate <b>${escapeHtml(view.launchGate.label)}</b></span><h2>${escapeHtml(view.launchGate.headline)}</h2><p>${escapeHtml(view.launchGate.detail)}</p></div><div class="pcr-stat"><span>Required rails</span><strong><b>${safeCount(view.launchGate.readyAdapterCount)}</b> / ${safeCount(view.launchGate.requiredAdapterCount)}</strong><small>fully launch-ready</small></div><div class="pcr-stat"><span>Required proofs</span><strong><b>${safeCount(view.launchGate.verifiedProofCount)}</b> / ${safeCount(view.launchGate.requiredProofCount)}</strong><small>${view.illustrative ? 'evidence-backed only' : 'current and verified'}</small></div><div class="pcr-stat"><span>Healthy adapters</span><strong>${safeCount(view.healthyCount)}</strong><small>of ${safeCount(view.adapterCount)} declared</small></div><div class="pcr-stat"><span>Blocking checks</span><strong>${safeCount(view.launchGate.blockerCount)}</strong><small>must reach zero</small></div></section>
    <div class="pcr-layout"><section class="pcr-catalog" aria-labelledby="pcr-catalog-title"><header class="pcr-section-head"><div><h2 id="pcr-catalog-title">Provider readiness map</h2><p>Email, messaging, social, webinar, payments and intelligence rails.</p></div><span class="pcr-count">${safeCount(view.categoryCount)} categories</span></header>${cards ? `<ol class="pcr-adapters">${cards}</ol>` : '<div class="pcr-empty"><span class="pcr-empty-mark" aria-hidden="true">00</span><strong>No adapter statuses declared.</strong><p>The launch gate fails closed until the required provider catalogue and proofs exist.</p></div>'}${truncation}</section>${blockerPanel(view)}</div>
    <footer class="pcr-footer"><span><strong>Setup required means exactly that:</strong> no OAuth journey or provider connection is implied by this safe readiness view.</span><span>${safeCount(view.setupRequiredCount)} rail${view.setupRequiredCount === 1 ? '' : 's'} need attention</span></footer>
  </article>`;
}
