/** Side-effect-free Property Predator provider-readiness cockpit. */

import { escapeHtml } from './ui.js';
import type {
  ProviderCockpitTone,
  ProviderEvidenceView,
  ProviderReadinessCockpitView,
  ProviderReadinessRailView,
} from './provider-readiness-cockpit-presenter.js';

const STYLE = `
  .prc{--prc-bg:#060809;--prc-panel:#0c1013;--prc-lift:#12181c;--prc-line:#263038;--prc-line-2:#39474f;--prc-ink:#f3f6f5;--prc-muted:#a2aeb2;--prc-faint:#738187;--prc-teal:#00e5cc;--prc-green:#6fdaa4;--prc-amber:#f2b84b;--prc-red:#ff7169;min-width:0;overflow:hidden;border:1px solid #020304;background:var(--prc-bg);color:var(--prc-ink)}.prc *{box-sizing:border-box}.prc h1,.prc h2,.prc h3,.prc p{margin-top:0}.prc-mono{font-family:var(--mono,ui-monospace,monospace)}
  .prc-hero{position:relative;display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,360px);gap:32px;align-items:end;padding:34px 34px 29px;border-bottom:1px solid var(--prc-line);background:radial-gradient(circle at 82% 15%,rgba(0,229,204,.13),transparent 31%),linear-gradient(140deg,#12191c,#060809 67%);overflow:hidden}.prc-hero:after{content:"";position:absolute;right:28%;top:-130px;width:250px;height:250px;border:1px solid rgba(0,229,204,.11);transform:rotate(45deg);pointer-events:none}.prc-kicker{position:relative;color:var(--prc-teal);font:850 11px/1.3 var(--mono,monospace);letter-spacing:.15em;text-transform:uppercase}.prc-hero h1{position:relative;margin:10px 0 12px;font-family:var(--display,Georgia,serif);font-size:clamp(2.5rem,5.4vw,5.2rem);font-weight:600;line-height:.88;letter-spacing:-.045em}.prc-hero h1 em{color:var(--prc-teal);font-style:normal}.prc-hero-copy p{position:relative;max-width:720px;margin:0;color:var(--prc-muted);font-size:14px;line-height:1.7}.prc-lock{position:relative;display:grid;gap:10px;border:1px solid var(--prc-line-2);background:rgba(4,7,8,.78);padding:16px}.prc-lock-top{display:flex;align-items:center;justify-content:space-between;gap:12px}.prc-lock-top span{color:var(--prc-faint);font:800 10px var(--mono,monospace);letter-spacing:.09em;text-transform:uppercase}.prc-lock-top strong{border:1px solid var(--prc-red);padding:5px 8px;color:var(--prc-red);font:900 10px var(--mono,monospace);letter-spacing:.08em}.prc-lock h2{margin:0;font-size:17px}.prc-lock p{margin:0;color:var(--prc-muted);font-size:12px;line-height:1.55}
  .prc-boundary{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:14px;align-items:center;padding:13px 34px;border-bottom:1px solid #785e28;background:#181205;color:#f3ca73}.prc-boundary strong{border:1px solid currentColor;padding:5px 8px;font:900 10px var(--mono,monospace);letter-spacing:.08em;white-space:nowrap}.prc-boundary p{margin:0;color:#d7c89e;font-size:12px;line-height:1.5}.prc-boundary span{font:800 10px var(--mono,monospace);letter-spacing:.05em;white-space:nowrap}
  .prc-pulse{display:grid;grid-template-columns:minmax(250px,1.4fr) repeat(4,minmax(120px,.65fr));border-bottom:1px solid var(--prc-line);background:var(--prc-panel)}.prc-pulse-lead,.prc-pulse-stat{padding:18px 20px;border-right:1px solid var(--prc-line)}.prc-pulse-stat:last-child{border-right:0}.prc-pulse-lead span,.prc-pulse-stat span{display:block;color:var(--prc-faint);font:800 10px var(--mono,monospace);letter-spacing:.07em;text-transform:uppercase}.prc-pulse-lead strong{display:block;margin:7px 0 5px;font-size:17px}.prc-pulse-lead p{margin:0;color:var(--prc-muted);font-size:12px;line-height:1.45}.prc-pulse-stat strong{display:block;margin-top:7px;font:900 21px var(--mono,monospace)}.prc-pulse-stat small{color:var(--prc-muted);font-size:11px}
  .prc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px;padding:16px}.prc-rail{min-width:0;border:1px solid var(--prc-line);border-top:3px solid var(--prc-red);border-radius:8px;background:var(--prc-panel);overflow:hidden}.prc-rail.working{border-top-color:var(--prc-amber)}.prc-rail.ready{border-top-color:var(--prc-teal)}.prc-rail-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;padding:17px 18px 15px;border-bottom:1px solid var(--prc-line);background:linear-gradient(145deg,var(--prc-lift),var(--prc-panel))}.prc-eyebrow{color:var(--prc-faint);font:800 10px var(--mono,monospace);letter-spacing:.08em;text-transform:uppercase}.prc-rail h2{margin:5px 0 4px;font-size:19px}.prc-provider{margin:0;color:var(--prc-muted);font-size:12px;line-height:1.45}.prc-provider b{color:var(--prc-amber);font:800 9px var(--mono,monospace);letter-spacing:.05em;text-transform:uppercase}.prc-state{align-self:start;border:1px solid var(--prc-red);padding:6px 8px;color:var(--prc-red);font:900 10px var(--mono,monospace);letter-spacing:.06em;text-transform:uppercase;white-space:nowrap}.prc-state.working{border-color:var(--prc-amber);color:var(--prc-amber)}.prc-state.ready{border-color:var(--prc-teal);color:var(--prc-teal)}
  .prc-stages{list-style:none;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));margin:0;padding:0;border-bottom:1px solid var(--prc-line)}.prc-stage{position:relative;min-width:0;padding:13px 12px;border-right:1px solid var(--prc-line)}.prc-stage:last-child{border-right:0}.prc-stage span{display:block;color:var(--prc-faint);font:800 9px var(--mono,monospace)}.prc-stage strong{display:block;margin-top:5px;color:var(--prc-muted);font-size:11px;line-height:1.35}.prc-stage:after{content:"";position:absolute;left:12px;right:12px;bottom:0;height:2px;background:var(--prc-red)}.prc-stage.working:after{background:var(--prc-amber)}.prc-stage.ready:after{background:var(--prc-teal)}.prc-stage.ready strong{color:var(--prc-green)}
  .prc-next{display:grid;grid-template-columns:auto minmax(0,1fr);gap:11px;align-items:center;padding:12px 18px;border-bottom:1px solid var(--prc-line);background:#0a0e10}.prc-next span{color:var(--prc-faint);font:800 9px var(--mono,monospace);letter-spacing:.07em;text-transform:uppercase}.prc-next strong{font-size:12px}.prc-blockers{padding:14px 18px;border-bottom:1px solid var(--prc-line)}.prc-blockers h3,.prc-caps h3,.prc-switches h3{margin:0 0 9px;color:var(--prc-faint);font:800 10px var(--mono,monospace);letter-spacing:.07em;text-transform:uppercase}.prc-blockers ul{display:grid;gap:7px;margin:0;padding:0;list-style:none}.prc-blockers li{display:grid;grid-template-columns:7px minmax(0,1fr);gap:9px;color:var(--prc-muted);font-size:11px;line-height:1.5}.prc-blockers li:before{content:"";width:6px;height:6px;margin-top:5px;border-radius:50%;background:var(--prc-red)}.prc-blockers code{display:block;margin-top:2px;color:var(--prc-faint);font-size:9px}
  .prc-controls{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);border-bottom:1px solid var(--prc-line)}.prc-caps,.prc-switches{min-width:0;padding:14px 16px}.prc-caps{border-right:1px solid var(--prc-line)}.prc-cap-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.prc-cap{min-width:0;border:1px solid var(--prc-line);background:#090c0e;padding:8px}.prc-cap span{display:block;color:var(--prc-faint);font:750 8px var(--mono,monospace);letter-spacing:.04em;text-transform:uppercase}.prc-cap strong{display:block;margin-top:4px;font:800 10px var(--mono,monospace);overflow-wrap:anywhere}.prc-switch-list{display:grid;gap:5px}.prc-switch{display:flex;align-items:center;justify-content:space-between;gap:9px;border-bottom:1px solid var(--prc-line);padding:5px 0;color:var(--prc-muted);font-size:10px}.prc-switch:last-child{border-bottom:0}.prc-switch b{color:var(--prc-red);font:900 9px var(--mono,monospace);letter-spacing:.05em}
  .prc-evidence{border:0}.prc-evidence>summary{display:flex;min-height:48px;align-items:center;justify-content:space-between;gap:12px;padding:11px 18px;cursor:pointer;color:var(--prc-ink);font-size:11px;font-weight:750;list-style:none}.prc-evidence>summary::-webkit-details-marker{display:none}.prc-evidence>summary:after{content:"+";display:grid;width:25px;height:25px;place-items:center;border:1px solid var(--prc-line-2);color:var(--prc-teal);font:900 15px var(--mono,monospace)}.prc-evidence[open]>summary:after{content:"−"}.prc-evidence>summary:focus-visible{outline:3px solid var(--prc-teal);outline-offset:-3px}.prc-evidence-count{color:var(--prc-faint);font:700 9px var(--mono,monospace)}.prc-evidence-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px;padding:0 14px 14px}.prc-evidence-item{min-width:0;border:1px solid var(--prc-line);background:#090c0e;padding:8px}.prc-evidence-item span{display:block;color:var(--prc-muted);font-size:9px;line-height:1.35}.prc-evidence-item b{display:block;margin-top:4px;color:var(--prc-red);font:800 8px var(--mono,monospace);letter-spacing:.04em;text-transform:uppercase}.prc-evidence-item.ready b{color:var(--prc-green)}.prc-evidence-item.working b{color:var(--prc-amber)}.prc-evidence-item.muted b{color:var(--prc-faint)}
  .prc-footer{display:flex;justify-content:space-between;gap:16px;padding:13px 18px;border-top:1px solid var(--prc-line);background:#080b0d;color:var(--prc-faint);font-size:10px;line-height:1.5}.prc-footer strong{color:var(--prc-muted)}
  @media(max-width:1180px){.prc-pulse{grid-template-columns:repeat(4,minmax(0,1fr))}.prc-pulse-lead{grid-column:1/-1;border-right:0;border-bottom:1px solid var(--prc-line)}.prc-grid{grid-template-columns:1fr}}
  @media(max-width:760px){.prc-hero{grid-template-columns:1fr;padding:27px 20px 22px}.prc-boundary{grid-template-columns:1fr;padding:13px 20px}.prc-boundary span{white-space:normal}.prc-pulse{grid-template-columns:repeat(2,minmax(0,1fr))}.prc-pulse-stat:nth-last-child(2){border-bottom:0}.prc-grid{padding:10px}.prc-controls{grid-template-columns:1fr}.prc-caps{border-right:0;border-bottom:1px solid var(--prc-line)}.prc-evidence-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.prc-footer{display:grid}}
  @media(max-width:480px){.prc-hero h1{font-size:2.65rem}.prc-pulse-stat{padding:14px}.prc-rail-head{grid-template-columns:1fr}.prc-state{justify-self:start}.prc-stages{grid-template-columns:1fr}.prc-stage{border-right:0;border-bottom:1px solid var(--prc-line)}.prc-stage:last-child{border-bottom:0}.prc-cap-grid,.prc-evidence-grid{grid-template-columns:1fr}.prc-next{grid-template-columns:1fr}}
  @media(prefers-reduced-motion:reduce){.prc *{scroll-behavior:auto!important;transition:none!important}}
  @media(forced-colors:active){.prc-state,.prc-lock-top strong,.prc-boundary strong,.prc-evidence>summary:after{forced-color-adjust:none}.prc-evidence>summary:focus-visible{outline-color:Highlight}}
`;

function tone(value: ProviderCockpitTone): string {
  return value === 'muted' ? 'muted' : value;
}

function readableInstant(value: string | null): string {
  if (!value) return 'No dated proof';
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
    timeZone: 'Europe/London', timeZoneName: 'short',
  }).format(new Date(value));
}

function renderEvidence(item: ProviderEvidenceView): string {
  return `<div class="prc-evidence-item ${tone(item.tone)}" title="${escapeHtml(item.verifiedAt ? `Verified ${readableInstant(item.verifiedAt)}` : 'No verified evidence date')}"><span>${escapeHtml(item.label)}</span><b>${escapeHtml(item.freshnessLabel)}</b></div>`;
}

function renderRail(rail: ProviderReadinessRailView): string {
  const blockers = rail.blockers.length
    ? rail.blockers.map((blocker) => `<li><span>${escapeHtml(blocker.message)}<code>${escapeHtml(blocker.code)}${blocker.gate ? ` · ${escapeHtml(blocker.gate)}` : ''}</code></span></li>`).join('')
    : '<li><span>No blocker is recorded at the current dark-readiness stage.</span></li>';
  const caps = [
    ['Spend / operation', rail.caps.spendOperation],
    ['Spend / day', rail.caps.spendDay],
    ['Spend / month', rail.caps.spendMonth],
    ['Volume / operation', rail.caps.volumeOperation],
    ['Volume / day', rail.caps.volumeDay],
    ['Volume / month', rail.caps.volumeMonth],
  ].map(([label, value]) => `<div class="prc-cap"><span>${escapeHtml(label!)}</span><strong>${escapeHtml(value!)}</strong></div>`).join('');
  return `<article class="prc-rail ${tone(rail.readinessTone)}" id="${escapeHtml(rail.anchorId)}" aria-labelledby="${escapeHtml(rail.anchorId)}-title">
    <header class="prc-rail-head"><div><span class="prc-eyebrow">${escapeHtml(rail.eyebrow)}</span><h2 id="${escapeHtml(rail.anchorId)}-title">${escapeHtml(rail.label)}</h2><p class="prc-provider">${escapeHtml(rail.providerLabel)} ${rail.candidateOnly ? '<b>unregistered candidate</b>' : ''}</p></div><span class="prc-state ${tone(rail.readinessTone)}">${escapeHtml(rail.readinessLabel)}</span></header>
    <ol class="prc-stages" aria-label="Readiness stages">${rail.stages.map((stage) => `<li class="prc-stage ${tone(stage.tone)}"${stage.active ? ' aria-current="step"' : ''}><span>${escapeHtml(stage.index)}</span><strong>${escapeHtml(stage.label)}</strong></li>`).join('')}</ol>
    <div class="prc-next"><span>Next controlled gate</span><strong>${escapeHtml(rail.nextStageLabel)}</strong></div>
    <section class="prc-blockers" aria-label="Why blocked"><h3>Why blocked</h3><ul>${blockers}</ul></section>
    <div class="prc-controls"><section class="prc-caps" aria-label="Test cap envelope"><h3>Test cap envelope</h3><div class="prc-cap-grid">${caps}</div></section><section class="prc-switches" aria-label="Effect switches"><h3>Effect switches</h3><div class="prc-switch-list">${rail.switches.map((item) => `<div class="prc-switch"><span>${escapeHtml(item.label)}</span><b>${item.value}</b></div>`).join('')}</div></section></div>
    <details class="prc-evidence"><summary><span>Evidence freshness</span><span class="prc-evidence-count">${rail.evidenceCurrent} current · ${rail.evidenceAttention} attention</span></summary><div class="prc-evidence-grid">${rail.evidence.map(renderEvidence).join('')}</div></details>
  </article>`;
}

export function renderProviderReadinessCockpitBody(view: ProviderReadinessCockpitView): string {
  const boundary = view.illustrative
    ? '<strong>ILLUSTRATIVE TEST DATA</strong><p>Fictional evidence demonstrates the operating view. It cannot prove a provider account, satisfy a launch gate or authorise an external effect.</p>'
    : '<strong>READ-ONLY EVIDENCE</strong><p>This view reports bounded readiness metadata only. It cannot load credentials, connect an account, change a switch or create a provider operation.</p>';
  return `<style>${STYLE}</style><section class="prc" aria-labelledby="provider-readiness-title">
    <header class="prc-hero"><div class="prc-hero-copy"><span class="prc-kicker">PropertyPredator · provider control</span><h1 id="provider-readiness-title">Ready the rails.<br><em>Keep them dark.</em></h1><p>One fail-closed cockpit for email, WhatsApp, public social and social DMs. Readiness is evidence—not a button—and live activation always remains a separate decision.</p></div><aside class="prc-lock" aria-label="Global safety lock"><div class="prc-lock-top"><span>Global effects boundary</span><strong>LOCKED</strong></div><h2>Emergency pause engaged</h2><p>Runtime, database, workspace and rail effects are OFF. Zero provider operations have been created.</p></aside></header>
    <aside class="prc-boundary" role="status">${boundary}<span>EXTERNAL EFFECTS OFF</span></aside>
    <section class="prc-pulse" aria-label="Readiness summary"><div class="prc-pulse-lead"><span>Dark activation posture</span><strong>${view.blockedRailCount} of ${view.rails.length} rails remain locked</strong><p>The production provider registry is not assumed. Every candidate must be explicitly composed, contract-reviewed and re-assessed.</p></div><div class="prc-pulse-stat"><span>Rails</span><strong>${view.rails.length}</strong><small>exact controlled set</small></div><div class="prc-pulse-stat"><span>Stage reached</span><strong>${view.readyRailCount}</strong><small>still not live</small></div><div class="prc-pulse-stat"><span>Evidence current</span><strong>${view.totalEvidenceCurrent}</strong><small>or not applicable</small></div><div class="prc-pulse-stat"><span>Needs attention</span><strong>${view.totalEvidenceAttention}</strong><small>missing, failed or stale</small></div></section>
    <div class="prc-grid">${view.rails.map(renderRail).join('')}</div>
    <footer class="prc-footer"><span><strong>Snapshot</strong> · ${escapeHtml(readableInstant(view.snapshotAt))}</span><span><strong>Safety invariant</strong> · no credentials · no external calls · no sends · no posts · no DMs</span></footer>
  </section>`;
}
