import { renderContentWorkspaceNavigation } from './content-workspace-navigation.js';
import type {
  PublicSocialCampaignPostView,
  PublicSocialCampaignRevisionView,
  PublicSocialCampaignsView,
  PublicSocialCampaignTargetView,
} from './public-social-campaigns-presenter.js';
import { escapeHtml } from './ui.js';

const PUBLIC_SOCIAL_CAMPAIGNS_STYLE = `
  .psc{--psc-bg:#080b0d;--psc-panel:#0d1215;--psc-panel2:#11181c;--psc-line:#253238;--psc-line2:#35454c;--psc-text:#f2f7f6;--psc-muted:#9aaaae;--psc-faint:#718188;--psc-teal:#00e5cc;--psc-teal2:#66f4e5;--psc-orange:#ff8a3d;--psc-red:#ff6b6b;--psc-amber:#efc66b;color:var(--psc-text);border:1px solid var(--psc-line);border-radius:14px;overflow:hidden;background:var(--psc-bg);box-shadow:0 22px 60px rgba(0,0,0,.25)}
  .psc *{box-sizing:border-box}.psc a{color:inherit}.psc code{font:700 11px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere}.psc-hero{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(270px,.65fr);gap:24px;padding:30px;background:radial-gradient(circle at 82% 12%,rgba(0,229,204,.14),transparent 33%),linear-gradient(135deg,#0c1316,#080b0d 70%)}
  .psc-kicker{margin-bottom:8px;color:var(--psc-teal);font-size:11px;font-weight:950;letter-spacing:.16em;text-transform:uppercase}.psc-hero h1{max-width:880px;margin:0;font-size:clamp(2.35rem,5vw,4.8rem);line-height:.9;letter-spacing:-.055em}.psc-hero h1 em{color:var(--psc-teal2);font-style:normal}.psc-objective{max-width:780px;margin:18px 0 0;color:var(--psc-muted);font-size:15px;line-height:1.65}.psc-id{display:inline-flex;max-width:100%;margin-top:16px;border:1px solid var(--psc-line);border-radius:7px;padding:7px 9px;background:#080c0e;color:var(--psc-faint)}
  .psc-boundary{align-self:start;border:1px solid #24665f;border-radius:11px;padding:17px;background:#09201e}.psc-boundary strong{display:block;color:var(--psc-teal2);font-size:13px}.psc-boundary span,.psc-boundary small{display:block;margin-top:7px;color:#b5c7c4;line-height:1.5}.psc-boundary small{color:#7f9995;font-size:11px}.psc-safety{display:flex;align-items:center;gap:12px;padding:13px 20px;border-block:1px solid var(--psc-line);background:#0a0f11}.psc-safety strong{flex:0 0 auto;color:var(--psc-orange);font-size:11px;letter-spacing:.08em;text-transform:uppercase}.psc-safety p{margin:0;color:var(--psc-muted);font-size:12px;line-height:1.55}.psc-calendar{flex:0 0 auto;min-height:44px;display:inline-flex;align-items:center;margin-left:auto;border:1px solid var(--psc-line2);border-radius:7px;padding:0 13px;color:var(--psc-teal2);font-size:12px;font-weight:900;text-decoration:none}.psc-calendar:hover{border-color:var(--psc-teal);background:#0c2522}.psc-calendar:focus-visible{outline:3px solid rgba(0,229,204,.35);outline-offset:2px}
  .psc-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-bottom:1px solid var(--psc-line);background:#0b1012}.psc-metric{padding:15px 18px;border-right:1px solid var(--psc-line)}.psc-metric:last-child{border-right:0}.psc-metric small{display:block;color:var(--psc-faint);font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.psc-metric strong{display:block;margin-top:5px;font-size:24px;line-height:1}.psc-metric span{display:block;margin-top:5px;color:var(--psc-muted);font-size:11px}.psc-metric.attention strong{color:var(--psc-amber)}
  .psc-body{display:grid;gap:13px;padding:13px}.psc-revision{border:1px solid var(--psc-line);border-radius:10px;overflow:hidden;background:var(--psc-panel)}.psc-revision-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:15px;padding:18px;border-bottom:1px solid var(--psc-line);background:var(--psc-panel2)}.psc-revision-kicker{color:var(--psc-teal);font-size:10px;font-weight:950;letter-spacing:.1em;text-transform:uppercase}.psc-revision h2{margin:5px 0 0;font-size:21px;line-height:1.2}.psc-revision-objective{max-width:900px;margin:8px 0 0;color:var(--psc-muted);font-size:12px;line-height:1.55}.psc-revision-proof{text-align:right}.psc-revision-proof span{display:block;color:var(--psc-faint);font-size:10px}.psc-revision-proof code{display:block;max-width:360px;margin-top:5px;color:#b9cbc8}
  .psc-revision-summary{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.psc-pill{display:inline-flex;align-items:center;min-height:26px;border:1px solid var(--psc-line2);border-radius:999px;padding:0 8px;color:var(--psc-muted);font-size:10px;font-weight:850}.psc-pill.attention{border-color:#76602f;color:var(--psc-amber)}.psc-posts{display:grid;gap:10px;padding:10px}.psc-post{border:1px solid var(--psc-line);border-radius:8px;background:#0a0f11;overflow:hidden}.psc-post-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:14px 15px;border-bottom:1px solid var(--psc-line)}.psc-post-head h3{margin:0;font-size:14px}.psc-post-head p{margin:5px 0 0;color:var(--psc-muted);font-size:11px}.psc-post-time{flex:0 0 auto;color:var(--psc-teal2);font-size:11px;font-weight:850;text-align:right}
  .psc-proof{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0;border-bottom:1px solid var(--psc-line)}.psc-proof div{padding:11px 14px;border-right:1px solid var(--psc-line);border-bottom:1px solid var(--psc-line)}.psc-proof div:nth-child(2n){border-right:0}.psc-proof div:nth-last-child(-n+2){border-bottom:0}.psc-proof dt{color:var(--psc-faint);font-size:9px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.psc-proof dd{margin:4px 0 0;color:#b9c8c6}
  .psc-targets{padding:12px 14px}.psc-targets h4{margin:0 0 9px;color:var(--psc-muted);font-size:10px;letter-spacing:.08em;text-transform:uppercase}.psc-target-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.psc-target{border:1px solid var(--psc-line);border-left:4px solid #32756e;border-radius:7px;padding:12px;background:#0c1215}.psc-target.working{border-left-color:#53a6da}.psc-target.complete{border-left-color:var(--psc-teal)}.psc-target.cancelled{border-left-color:#69777c}.psc-target.attention{border-left-color:var(--psc-orange);background:#151109}.psc-target-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.psc-network{font-size:13px;font-weight:950}.psc-target-label{display:block;margin-top:3px;color:var(--psc-muted);font-size:11px}.psc-state{flex:0 0 auto;border:1px solid var(--psc-line2);border-radius:999px;padding:4px 7px;color:#aebfbc;font-size:9px;font-weight:950;text-transform:uppercase}.psc-target.attention .psc-state{border-color:#71572e;color:var(--psc-amber)}.psc-target.complete .psc-state{border-color:#266f67;color:var(--psc-teal2)}.psc-state-detail{margin:9px 0;color:var(--psc-muted);font-size:11px;line-height:1.5}.psc-target details{border-top:1px solid var(--psc-line);padding-top:8px}.psc-target summary{min-height:44px;display:flex;align-items:center;color:var(--psc-teal2);font-size:11px;font-weight:850;cursor:pointer}.psc-target summary:focus-visible{outline:3px solid rgba(0,229,204,.3);outline-offset:2px}.psc-target-proof{display:grid;gap:6px;margin:0}.psc-target-proof div{display:grid;grid-template-columns:90px minmax(0,1fr);gap:8px}.psc-target-proof dt{color:var(--psc-faint);font-size:9px;text-transform:uppercase}.psc-target-proof dd{margin:0;color:#afbfbd}.psc-no-targets,.psc-no-posts{margin:0;padding:17px;color:var(--psc-muted);font-size:12px;line-height:1.55}.psc-no-posts{border-top:1px solid var(--psc-line)}
  .psc-empty{padding:42px 24px;text-align:center}.psc-empty strong{display:block;font-size:22px}.psc-empty p{max-width:620px;margin:10px auto;color:var(--psc-muted);font-size:13px;line-height:1.6}.psc-empty a{min-height:44px;display:inline-flex;align-items:center;margin-top:9px;border:1px solid #2c716a;border-radius:7px;padding:0 15px;color:var(--psc-teal2);font-size:12px;font-weight:900;text-decoration:none}.psc-empty a:focus-visible{outline:3px solid rgba(0,229,204,.35);outline-offset:2px}.psc-truncation{margin:13px 13px 0;border:1px solid #76602f;border-radius:8px;padding:12px 14px;background:#151109;color:var(--psc-amber);font-size:12px;line-height:1.55}.psc-footer{display:flex;justify-content:space-between;gap:18px;padding:14px 18px;border-top:1px solid var(--psc-line);background:#080b0d;color:var(--psc-faint);font-size:11px;line-height:1.5}.psc-footer strong{color:var(--psc-muted)}
  @media(max-width:900px){.psc-hero{grid-template-columns:1fr}.psc-boundary{max-width:540px}.psc-target-list{grid-template-columns:1fr}.psc-revision-head{grid-template-columns:1fr}.psc-revision-proof{text-align:left}.psc-revision-proof code{max-width:none}}
  @media(max-width:680px){.psc-hero{padding:23px 18px}.psc-safety{align-items:flex-start;flex-direction:column}.psc-calendar{width:100%;justify-content:center;margin-left:0}.psc-metrics{grid-template-columns:repeat(2,1fr)}.psc-metric:nth-child(2){border-right:0}.psc-metric:nth-child(n+3){border-top:1px solid var(--psc-line)}.psc-proof{grid-template-columns:1fr}.psc-proof div,.psc-proof div:nth-child(2n),.psc-proof div:nth-last-child(-n+2){border-right:0;border-bottom:1px solid var(--psc-line)}.psc-proof div:last-child{border-bottom:0}.psc-post-head{flex-direction:column}.psc-post-time{text-align:left}.psc-footer{flex-direction:column}}
  @media(max-width:430px){.psc-metrics{grid-template-columns:1fr}.psc-metric,.psc-metric:nth-child(2){border-right:0}.psc-metric:nth-child(n+2){border-top:1px solid var(--psc-line)}.psc-target-head{flex-direction:column}.psc-state{align-self:flex-start}.psc-target-proof div{grid-template-columns:1fr}.psc-hero h1{font-size:2.35rem}}
  @media(forced-colors:active){.psc,.psc-revision,.psc-post,.psc-target,.psc-pill,.psc-state,.psc-boundary{forced-color-adjust:auto}.psc-target{border-left-width:5px}}
  @media(prefers-reduced-motion:reduce){.psc *{scroll-behavior:auto!important;transition:none!important}}
`;

function safeCount(value: number): string {
  return Number.isSafeInteger(value) && value >= 0 ? value.toLocaleString('en-GB') : '0';
}

function isoTime(value: string): string {
  const date = new Date(value);
  const label = new Intl.DateTimeFormat('en-GB', {
    dateStyle: 'medium',
    timeStyle: 'short',
    timeZone: 'UTC',
  }).format(date);
  return `<time datetime="${escapeHtml(value)}">${escapeHtml(label)} UTC</time>`;
}

function targetCard(target: PublicSocialCampaignTargetView): string {
  const receipt = target.testReferenceSha256 === null
    ? '<span>No simulator receipt recorded</span>'
    : `<code>${escapeHtml(target.testReferenceSha256)}</code>`;
  return `<article class="psc-target ${escapeHtml(target.stateTone)}" aria-label="${escapeHtml(target.networkLabel)} ${escapeHtml(target.stateLabel)}"><header class="psc-target-head"><div><strong class="psc-network">${escapeHtml(target.networkLabel)}</strong><span class="psc-target-label">${escapeHtml(target.targetLabel)}</span></div><span class="psc-state"${target.attention ? ' role="status"' : ''}>${escapeHtml(target.stateLabel)}</span></header><p class="psc-state-detail">${escapeHtml(target.stateDetail)}</p><details><summary>Exact TEST operation provenance</summary><dl class="psc-target-proof"><div><dt>Operation ID</dt><dd><code>${escapeHtml(target.operationId)}</code></dd></div><div><dt>Target ID</dt><dd><code>${escapeHtml(target.targetId)}</code></dd></div><div><dt>Durable state</dt><dd><code>${escapeHtml(target.state)}</code></dd></div><div><dt>Simulation attempts</dt><dd>${safeCount(target.simulationAttemptCount)} of ${safeCount(target.maxSimulationAttempts)}</dd></div><div><dt>Reconciliation attempts</dt><dd>${safeCount(target.reconciliationAttemptCount)} of ${safeCount(target.maxReconciliationAttempts)}</dd></div><div><dt>Receipt hash</dt><dd>${receipt}</dd></div><div><dt>Boundary</dt><dd>TEST · provider effects none</dd></div></dl></details></article>`;
}

function postCard(post: PublicSocialCampaignPostView): string {
  const targets = post.targets.map(targetCard).join('');
  return `<article class="psc-post" aria-labelledby="psc-post-${escapeHtml(post.postId)}"><header class="psc-post-head"><div><h3 id="psc-post-${escapeHtml(post.postId)}">Immutable TEST post plan</h3><p>Post <code>${escapeHtml(post.postId)}</code></p></div><div class="psc-post-time"><span>Scheduled TEST time</span><br>${isoTime(post.scheduledFor)}</div></header><dl class="psc-proof" aria-label="Exact content and plan provenance"><div><dt>Content item ID</dt><dd><code>${escapeHtml(post.contentItemId)}</code></dd></div><div><dt>Content version ID</dt><dd><code>${escapeHtml(post.contentVersionId)}</code></dd></div><div><dt>Exact content SHA-256</dt><dd><code>${escapeHtml(post.contentSha256)}</code></dd></div><div><dt>Exact sealed plan SHA-256</dt><dd><code>${escapeHtml(post.planSha256)}</code></dd></div></dl><section class="psc-targets" aria-labelledby="psc-targets-${escapeHtml(post.postId)}"><h4 id="psc-targets-${escapeHtml(post.postId)}">TEST target operations · ${safeCount(post.targets.length)}</h4>${targets ? `<div class="psc-target-list">${targets}</div>` : '<p class="psc-no-targets" role="status">This immutable post exists, but no TEST target operation is recorded.</p>'}</section></article>`;
}

function revisionCard(revision: PublicSocialCampaignRevisionView): string {
  const posts = revision.posts.map(postCard).join('');
  return `<section class="psc-revision" aria-labelledby="psc-revision-${escapeHtml(revision.revisionId)}"><header class="psc-revision-head"><div><span class="psc-revision-kicker">Immutable campaign revision ${safeCount(revision.revisionNumber)}</span><h2 id="psc-revision-${escapeHtml(revision.revisionId)}">${escapeHtml(revision.title)}</h2><p class="psc-revision-objective">${escapeHtml(revision.objective)}</p><div class="psc-revision-summary"><span class="psc-pill">${safeCount(revision.posts.length)} post plan${revision.posts.length === 1 ? '' : 's'}</span><span class="psc-pill">${safeCount(revision.targetCount)} TEST target${revision.targetCount === 1 ? '' : 's'}</span>${revision.attentionCount > 0 ? `<span class="psc-pill attention">${safeCount(revision.attentionCount)} need attention</span>` : '<span class="psc-pill">No attention states</span>'}<span class="psc-pill">${escapeHtml(revision.timezone)}</span></div></div><div class="psc-revision-proof"><span>Revision ID</span><code>${escapeHtml(revision.revisionId)}</code><span>Exact revision SHA-256</span><code>${escapeHtml(revision.revisionSha256)}</code></div></header>${posts ? `<div class="psc-posts">${posts}</div>` : '<p class="psc-no-posts" role="status">This immutable revision has no TEST post plans. Nothing has been queued or published.</p>'}</section>`;
}

export interface RenderPublicSocialCampaignsOptions {
  readonly companyAssetsAvailable?: boolean;
  readonly assetsLabel?: string;
  readonly brandBrainAvailable?: boolean;
  readonly brainLabel?: string;
}

/** Read-only rendering: this surface deliberately emits no form, button or script. */
export function renderPublicSocialCampaignsBody(
  view: PublicSocialCampaignsView,
  options: RenderPublicSocialCampaignsOptions = {},
): string {
  const revisions = view.revisions.map(revisionCard).join('');
  const campaignId = view.campaignId === null
    ? 'No campaign selected'
    : `<code>${escapeHtml(view.campaignId)}</code>`;
  const heroTitle = view.campaignTitle === null
    ? 'Campaign truth. <em>No theatre.</em>'
    : `${escapeHtml(view.campaignTitle)}. <em>Bounded evidence visible.</em>`;
  const objective = view.campaignObjective === null
    ? 'Choose an exact TEST campaign from the authenticated workspace. This page never invents campaign data and never exposes a provider action.'
    : escapeHtml(view.campaignObjective);
  const content = revisions || `<section class="psc-empty" aria-labelledby="psc-empty-title"><strong id="psc-empty-title">No exact campaign projection loaded.</strong><p>No demo campaign has been substituted. Open the calendar to find durable TEST plans, then return with one exact campaign ID.</p><a href="${escapeHtml(view.calendarHref)}">Open the TEST calendar</a></section>`;
  const truncation = view.inputTruncated
    ? '<p class="psc-truncation" role="status"><strong>Safe read boundary reached.</strong> Additional campaign evidence exists but is omitted. Counts cover only loaded complete post aggregates; no post is displayed with a silently partial target list.</p>'
    : '';
  return `${renderContentWorkspaceNavigation('campaigns', {
    companyAssetsAvailable: options.companyAssetsAvailable,
    assetsLabel: options.assetsLabel,
    brandBrainAvailable: options.brandBrainAvailable ?? false,
    brainLabel: options.brainLabel,
  })}<style data-property-predator-public-social-campaigns>${PUBLIC_SOCIAL_CAMPAIGNS_STYLE}</style><article class="psc" aria-labelledby="psc-title" data-public-social-campaigns data-environment="test" data-provider-effects="none" data-read-only="true" data-input-truncated="${view.inputTruncated ? 'true' : 'false'}"><header class="psc-hero"><div><div class="psc-kicker">Property Predator · Public-social command truth</div><h1 id="psc-title">${heroTitle}</h1><p class="psc-objective">${objective}</p><span class="psc-id">${campaignId}</span></div><aside class="psc-boundary" aria-label="Public-social safety boundary"><strong>Authenticated read model · TEST only</strong><span>${escapeHtml(view.workspaceName)}</span><small>${escapeHtml(view.workspaceTimezone)} workspace · snapshot ${isoTime(view.snapshotAt)}. Post bodies, account references, storage paths and secrets are absent by contract.</small></aside></header><section class="psc-safety" aria-label="Zero-effect campaign boundary"><strong>Zero effects</strong><p>This is durable operational evidence, not a live social console. It cannot create, edit, schedule, cancel, retry, send or publish anything.</p><a class="psc-calendar" href="${escapeHtml(view.calendarHref)}">View TEST calendar</a></section>${truncation}<section class="psc-metrics" aria-label="Loaded campaign evidence summary"><div class="psc-metric"><small>Loaded revisions</small><strong>${safeCount(view.summary.revisionCount)}</strong><span>Exact revision hashes</span></div><div class="psc-metric"><small>Loaded post plans</small><strong>${safeCount(view.summary.postCount)}</strong><span>Complete body-free aggregates</span></div><div class="psc-metric"><small>Loaded TEST targets</small><strong>${safeCount(view.summary.targetCount)}</strong><span>Durable operation states</span></div><div class="psc-metric${view.summary.attentionCount > 0 ? ' attention' : ''}"><small>Loaded attention</small><strong>${safeCount(view.summary.attentionCount)}</strong><span>Visible; never auto-advanced</span></div></section><div class="psc-body">${content}</div><footer class="psc-footer"><span><strong>Read-only throughout:</strong> environment ${escapeHtml(view.environment)} · provider effects ${escapeHtml(view.providerEffects)} · generated campaign data 0.</span><span>${safeCount(view.summary.revisionCount)} loaded revisions · ${safeCount(view.summary.targetCount)} loaded bounded TEST operations${view.inputTruncated ? ' · additional evidence omitted' : ''}</span></footer></article>`;
}
