/** Premium, server-rendered social-account control room with no command seam. */

import { renderContentWorkspaceNavigation } from './content-workspace-navigation.js';
import { escapeHtml } from './ui.js';
import type {
  SocialAccountControlView,
  SocialAccountPermissionView,
  SocialAccountView,
} from './social-account-control-presenter.js';

const SOCIAL_ACCOUNT_CONTROL_STYLE = `
  .sac{--black:#060809;--panel:#0d1113;--lift:#12181b;--soft:#090c0e;--line:#243137;--line2:#35454b;--ink:#f4f6f2;--muted:#a8b5b4;--faint:#788887;--acid:#d7ff38;--teal:#00e6cb;--amber:#ffc45c;--red:#ff6f68;--green:#75d9a6;min-width:0;overflow:hidden;border:1px solid #020303;background:var(--black);color:var(--ink);font-family:var(--sans,ui-sans-serif,system-ui,sans-serif)}.sac *{box-sizing:border-box}.sac h1,.sac h2,.sac h3,.sac p{margin-top:0}.sac code{font-family:var(--mono,ui-monospace,monospace);overflow-wrap:anywhere}.sac-visually-hidden{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
  .sac-hero{position:relative;display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:28px;align-items:end;padding:34px 34px 30px;border-bottom:1px solid var(--line);background:radial-gradient(circle at 80% 12%,rgba(215,255,56,.13),transparent 28%),radial-gradient(circle at 95% 85%,rgba(0,230,203,.1),transparent 25%),linear-gradient(135deg,#111819,#060809 70%);overflow:hidden}.sac-hero:after{position:absolute;right:31%;top:-98px;width:220px;height:220px;border:1px solid rgba(215,255,56,.11);content:"";transform:rotate(45deg);pointer-events:none}.sac-kicker{position:relative;color:var(--acid);font:900 11px/1.2 var(--mono,monospace);letter-spacing:.15em;text-transform:uppercase}.sac-hero h1{position:relative;max-width:820px;margin:10px 0 12px;font-family:var(--display,var(--sans));font-size:clamp(2.55rem,5vw,5.25rem);font-weight:650;line-height:.89;letter-spacing:-.055em}.sac-hero h1 em{color:var(--acid);font-style:normal}.sac-hero-copy>p{position:relative;max-width:720px;margin:0;color:var(--muted);font-size:14px;line-height:1.65}.sac-lock{position:relative;border:1px solid #46523a;background:rgba(7,10,8,.8);padding:18px}.sac-lock-top{display:flex;justify-content:space-between;gap:12px;color:var(--faint);font:850 10px var(--mono,monospace);letter-spacing:.08em;text-transform:uppercase}.sac-lock-top b{border:1px solid var(--acid);padding:3px 7px;color:var(--acid)}.sac-lock h2{margin:13px 0 6px;font-size:18px}.sac-lock p{margin:0;color:var(--muted);font-size:12px;line-height:1.55}
  .sac-boundary{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:14px;align-items:center;padding:12px 34px;border-bottom:1px solid var(--line);background:#0b0e0f}.sac-boundary-mark{color:var(--acid);font:900 10px var(--mono,monospace);letter-spacing:.1em;text-transform:uppercase}.sac-boundary p{margin:0;color:var(--muted);font-size:12px;line-height:1.5}.sac-boundary p strong{color:var(--ink)}.sac-boundary-badge{border:1px solid #52603d;padding:6px 9px;color:var(--acid);font:850 9px var(--mono,monospace);letter-spacing:.06em;text-transform:uppercase;white-space:nowrap}.sac-fixture{display:grid;grid-template-columns:auto minmax(0,1fr);gap:14px;align-items:center;padding:13px 34px;border-bottom:1px solid #806834;background:#191408;color:var(--amber)}.sac-fixture strong{border:1px solid currentColor;padding:5px 8px;font:900 10px var(--mono,monospace);letter-spacing:.08em}.sac-fixture p{margin:0;color:#ddcca1;font-size:11px;line-height:1.5}
  .sac-metrics{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));border-bottom:1px solid var(--line);background:var(--panel)}.sac-metric{min-width:0;padding:15px 17px;border-right:1px solid var(--line)}.sac-metric:last-child{border-right:0}.sac-metric small{display:block;color:var(--faint);font:850 9px var(--mono,monospace);letter-spacing:.07em;text-transform:uppercase}.sac-metric strong{display:block;margin-top:7px;font:900 21px var(--mono,monospace)}.sac-metric span{display:block;margin-top:3px;color:var(--muted);font-size:10px;line-height:1.35}.sac-metric.ready strong{color:var(--teal)}.sac-metric.locked strong{color:var(--red)}
  .sac-layout{display:grid;grid-template-columns:minmax(260px,330px) minmax(0,1fr);gap:14px;padding:16px}.sac-sidebar{display:grid;align-content:start;gap:12px}.sac-provider,.sac-ladder,.sac-catalog{min-width:0;border:1px solid var(--line);background:var(--panel)}.sac-section-head{display:flex;justify-content:space-between;gap:14px;align-items:start;padding:17px 18px 14px;border-bottom:1px solid var(--line)}.sac-section-head h2{margin:0;font-size:16px}.sac-section-head p{margin:5px 0 0;color:var(--muted);font-size:11px;line-height:1.5}.sac-count{border:1px solid var(--line2);padding:4px 8px;color:var(--muted);font:850 10px var(--mono,monospace);white-space:nowrap}
  .sac-provider-hero{padding:18px}.sac-provider-brand{display:flex;align-items:center;gap:12px}.sac-provider-mark{width:43px;height:43px;display:grid;place-items:center;border:1px solid #50603a;background:#141a0d;color:var(--acid);font:950 13px var(--mono,monospace)}.sac-provider-brand span{display:block;color:var(--faint);font:850 9px var(--mono,monospace);letter-spacing:.07em;text-transform:uppercase}.sac-provider-brand strong{display:block;margin-top:4px;font-size:13px}.sac-provider-status{display:flex;align-items:center;gap:7px;margin:16px 0 0;color:var(--amber);font:900 10px var(--mono,monospace);text-transform:uppercase}.sac-provider-status:before{width:7px;height:7px;border-radius:50%;background:var(--amber);content:""}.sac-contract{list-style:none;margin:0;padding:0 18px 12px}.sac-contract li{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-top:1px solid var(--line);font-size:10px}.sac-contract span{color:var(--faint)}.sac-contract strong{max-width:60%;text-align:right;color:var(--muted);font-weight:750}.sac-provider-note{margin:0;padding:13px 18px;border-top:1px solid var(--line);background:var(--soft);color:var(--muted);font-size:10px;line-height:1.55}.sac-provider-note strong{color:var(--ink)}
  .sac-ladder ol{list-style:none;margin:0;padding:7px 18px 14px;counter-reset:ladder}.sac-ladder li{position:relative;display:grid;grid-template-columns:25px minmax(0,1fr);gap:9px;padding:9px 0;border-bottom:1px solid var(--line);counter-increment:ladder}.sac-ladder li:last-child{border-bottom:0}.sac-ladder li:before{width:24px;height:24px;display:grid;place-items:center;border:1px solid var(--line2);color:var(--acid);content:counter(ladder,decimal-leading-zero);font:900 8px var(--mono,monospace)}.sac-ladder strong{display:block;font-size:10px}.sac-ladder span{display:block;margin-top:3px;color:var(--faint);font-size:9px;line-height:1.45}
  .sac-accounts{list-style:none;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:0;padding:10px}.sac-account{min-width:0;border:1px solid var(--line);border-top:3px solid var(--red);border-radius:8px;background:var(--lift);overflow:hidden}.sac-account.ready{border-top-color:var(--teal)}.sac-account.wait{border-top-color:var(--amber)}.sac-account.muted{border-top-color:var(--faint);opacity:.88}.sac-account-head{display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:11px;align-items:start;padding:14px;border-bottom:1px solid var(--line)}.sac-network-mark{width:40px;height:40px;display:grid;place-items:center;border:1px solid var(--line2);border-radius:11px;background:#090c0d;color:var(--acid);font:950 12px var(--mono,monospace)}.sac-account-identity{min-width:0}.sac-network{display:block;color:var(--faint);font:850 9px var(--mono,monospace);letter-spacing:.08em;text-transform:uppercase}.sac-account h3{margin:5px 0 2px;font-size:14px;line-height:1.25}.sac-handle{display:block;color:var(--muted);font:650 10px var(--mono,monospace);overflow-wrap:anywhere}.sac-connection{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--line2);border-radius:999px;padding:5px 8px;color:var(--red);font:900 8px var(--mono,monospace);letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}.sac-connection:before{width:6px;height:6px;border-radius:50%;background:currentColor;content:""}.sac-connection.ready{color:var(--teal)}.sac-connection.wait{color:var(--amber)}.sac-connection.muted{color:var(--faint)}
  .sac-account-strip{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-bottom:1px solid var(--line)}.sac-mini{min-width:0;padding:10px;border-right:1px solid var(--line)}.sac-mini:last-child{border-right:0}.sac-mini span{display:block;color:var(--faint);font:800 8px var(--mono,monospace);letter-spacing:.05em;text-transform:uppercase}.sac-mini strong{display:block;margin-top:5px;color:var(--muted);font-size:9px;line-height:1.35;overflow-wrap:anywhere}.sac-mini strong.ready{color:var(--teal)}.sac-mini strong.wait{color:var(--amber)}.sac-mini strong.blocked{color:var(--red)}.sac-mini strong.muted{color:var(--faint)}
  .sac-health{padding:12px 14px;border-bottom:1px solid var(--line)}.sac-health-top{display:flex;justify-content:space-between;gap:10px}.sac-health-top strong{display:flex;align-items:center;gap:7px;font-size:10px}.sac-health-top strong:before{width:7px;height:7px;border-radius:50%;background:var(--red);content:""}.sac-health.ready .sac-health-top strong:before{background:var(--teal)}.sac-health.wait .sac-health-top strong:before{background:var(--amber)}.sac-health.muted .sac-health-top strong:before{background:var(--faint)}.sac-health-top span{color:var(--faint);font:800 8px var(--mono,monospace)}.sac-health p{margin:6px 0 0;color:var(--muted);font-size:10px;line-height:1.5}
  .sac-permissions{padding:12px 14px;border-bottom:1px solid var(--line)}.sac-subhead{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:7px}.sac-subhead strong{font-size:10px}.sac-subhead span{color:var(--faint);font:800 8px var(--mono,monospace)}.sac-permission-list{list-style:none;margin:0;padding:0}.sac-permission{display:grid;grid-template-columns:18px minmax(0,1fr) auto;gap:7px;align-items:start;padding:7px 0;border-top:1px solid var(--line)}.sac-permission-mark{width:17px;height:17px;display:grid;place-items:center;border:1px solid var(--line2);border-radius:50%;color:var(--faint);font:900 8px var(--mono,monospace)}.sac-permission.ready .sac-permission-mark{border-color:#2b756b;color:var(--teal)}.sac-permission.wait .sac-permission-mark{border-color:#8a6e33;color:var(--amber)}.sac-permission-copy strong{display:block;font-size:9px}.sac-permission-copy p{margin:2px 0 0;color:var(--faint);font-size:8px;line-height:1.4}.sac-permission-state{color:var(--faint);font:850 7px var(--mono,monospace);text-transform:uppercase}.sac-permission.ready .sac-permission-state{color:var(--teal)}.sac-permission.wait .sac-permission-state{color:var(--amber)}
  .sac-blockers{padding:12px 14px;border-bottom:1px solid var(--line);background:var(--soft)}.sac-blockers strong{display:block;color:var(--red);font:900 9px var(--mono,monospace);letter-spacing:.05em;text-transform:uppercase}.sac-blockers.ready strong{color:var(--teal)}.sac-blockers ul{margin:7px 0 0;padding-left:16px;color:var(--muted);font-size:9px;line-height:1.5}.sac-blockers.ready p{margin:6px 0 0;color:var(--muted);font-size:9px;line-height:1.45}.sac-actions{display:grid;grid-template-columns:1fr auto;gap:8px;padding:12px 14px;border-bottom:1px solid var(--line)}.sac-action{min-height:46px;border:1px solid #59633f;border-radius:6px;background:#171d11;color:var(--acid);padding:0 12px;font:900 9px var(--mono,monospace);letter-spacing:.04em;text-align:left}.sac-action[disabled]{border-color:var(--line2);background:#0b0f10;color:#7b8682;cursor:not-allowed;opacity:1}.sac-action-icon{width:46px;text-align:center!important}.sac-action:focus-visible,.sac-disconnect summary:focus-visible{outline:3px solid var(--acid);outline-offset:3px}.sac-disconnect{background:#090c0d}.sac-disconnect summary{min-height:48px;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:0 14px;list-style:none;color:var(--muted);font:850 9px var(--mono,monospace);letter-spacing:.04em;text-transform:uppercase;cursor:pointer}.sac-disconnect summary::-webkit-details-marker{display:none}.sac-disconnect summary:after{color:var(--red);font-size:17px;content:"+"}.sac-disconnect[open] summary:after{content:"−"}.sac-disconnect-body{padding:0 14px 14px}.sac-disconnect-body p{margin:0 0 9px;color:var(--muted);font-size:9px;line-height:1.5}.sac-danger{width:100%;min-height:46px;border:1px solid #633e3b;border-radius:6px;background:#170d0c;color:var(--red);font:900 9px var(--mono,monospace);text-transform:uppercase}.sac-danger[disabled]{border-color:#473332;color:#85615e;cursor:not-allowed}.sac-account-foot{display:flex;justify-content:space-between;gap:10px;padding:9px 14px;color:var(--faint);font:750 8px var(--mono,monospace);text-transform:uppercase}.sac-truncated{margin:0;padding:11px 18px;border-top:1px solid var(--line);color:var(--amber);font-size:10px}.sac-footer{display:flex;justify-content:space-between;gap:14px;padding:14px 18px;border-top:1px solid var(--line);background:#07090a;color:var(--faint);font-size:10px}.sac-footer strong{color:var(--muted)}
  @media(max-width:1180px){.sac-metrics{grid-template-columns:repeat(3,1fr)}.sac-metric:nth-child(3){border-right:0}.sac-metric:nth-child(n+4){border-top:1px solid var(--line)}.sac-layout{grid-template-columns:280px minmax(0,1fr)}.sac-accounts{grid-template-columns:1fr}}
  @media(max-width:840px){.sac-hero{grid-template-columns:1fr;padding:26px 20px 23px}.sac-boundary{grid-template-columns:1fr;padding:12px 20px}.sac-boundary-badge{justify-self:start}.sac-fixture{grid-template-columns:1fr;padding:13px 20px}.sac-fixture strong{justify-self:start}.sac-layout{grid-template-columns:1fr;padding:10px}.sac-sidebar{grid-template-columns:repeat(2,minmax(0,1fr))}.sac-catalog{grid-column:1/-1;grid-row:1}.sac-accounts{grid-template-columns:repeat(2,minmax(0,1fr))}}
  @media(max-width:620px){.sac-hero h1{font-size:2.75rem}.sac-metrics{grid-template-columns:repeat(2,1fr)}.sac-metric:nth-child(3){border-right:1px solid var(--line)}.sac-metric:nth-child(even){border-right:0}.sac-metric:nth-child(n+3){border-top:1px solid var(--line)}.sac-sidebar,.sac-accounts{grid-template-columns:1fr}.sac-account-head{grid-template-columns:42px minmax(0,1fr)}.sac-connection{grid-column:2;justify-self:start}.sac-account-strip{grid-template-columns:1fr}.sac-mini{border-right:0;border-bottom:1px solid var(--line)}.sac-mini:last-child{border-bottom:0}.sac-permission{grid-template-columns:18px minmax(0,1fr)}.sac-permission-state{grid-column:2}.sac-footer{flex-direction:column}.sac-actions{grid-template-columns:1fr auto}}
  @media(forced-colors:active){.sac,.sac-account,.sac-provider,.sac-ladder,.sac-catalog,.sac-action,.sac-danger{forced-color-adjust:auto}.sac-account{border-top-width:5px}}
  @media(prefers-reduced-motion:reduce){.sac *{scroll-behavior:auto!important;transition:none!important}}
`;

function count(value: number): string {
  return String(Math.max(0, Math.min(Math.floor(value), 9_999)));
}

function moment(value: string | null): string {
  return value === null
    ? 'Not recorded'
    : `<time datetime="${escapeHtml(value)}">${escapeHtml(value.replace('T', ' ').replace('.000Z', ' UTC'))}</time>`;
}

function permissionRow(permission: SocialAccountPermissionView): string {
  const mark = permission.tone === 'ready' ? '✓' : permission.tone === 'wait' ? '!' : '–';
  return `<li class="sac-permission ${escapeHtml(permission.tone)}"><span class="sac-permission-mark" aria-hidden="true">${mark}</span><div class="sac-permission-copy"><strong>${escapeHtml(permission.label)}${permission.required ? '' : ' · optional'}</strong><p>${escapeHtml(permission.purpose)}</p></div><span class="sac-permission-state">${escapeHtml(permission.stateLabel)}</span></li>`;
}

function blockers(account: SocialAccountView): string {
  if (account.rehearsalReady) {
    return '<section class="sac-blockers ready" aria-label="Rehearsal readiness"><strong>Rehearsal checks complete</strong><p>The fictional X account fits the current contract. Live activation still stays locked by the global effects boundary.</p></section>';
  }
  const rows = account.blockers.slice(0, 8).map((blocker) => `<li>${escapeHtml(blocker)}</li>`).join('');
  return `<section class="sac-blockers" aria-label="Why this account is blocked"><strong>Why blocked</strong><ul>${rows || '<li>No complete readiness evidence exists.</li>'}</ul></section>`;
}

function accountCard(account: SocialAccountView): string {
  const cardTone = account.rehearsalReady ? 'ready' : account.connectionTone;
  const permissions = account.permissions.map(permissionRow).join('');
  const profile = account.providerProfileRef ?? 'No binding';
  const latency = account.health.latencyMs === null ? '' : ` · ${count(account.health.latencyMs)}ms`;
  const revoked = account.revokedAt === null ? '' : `<span>Revoked ${moment(account.revokedAt)}</span>`;
  return `<li><article class="sac-account ${escapeHtml(cardTone)}" id="${escapeHtml(account.anchorId)}" aria-labelledby="${escapeHtml(account.anchorId)}-title">
    <header class="sac-account-head"><span class="sac-network-mark" aria-hidden="true">${escapeHtml(account.networkMark)}</span><div class="sac-account-identity"><span class="sac-network">${escapeHtml(account.networkLabel)} · ${escapeHtml(account.accountKind)}</span><h3 id="${escapeHtml(account.anchorId)}-title">${escapeHtml(account.accountLabel)}</h3><span class="sac-handle">${escapeHtml(account.accountHandle)}</span></div><span class="sac-connection ${escapeHtml(account.connectionTone)}">${escapeHtml(account.connectionLabel)}</span></header>
    <section class="sac-account-strip" aria-label="Account readiness summary"><div class="sac-mini"><span>Dispatch seam</span><strong class="${escapeHtml(account.contractTone)}">${escapeHtml(account.contractLabel)}</strong></div><div class="sac-mini"><span>Profile binding</span><strong>${escapeHtml(profile)}</strong></div><div class="sac-mini"><span>Required scopes</span><strong class="${account.grantedPermissionCount === account.requiredPermissionCount && account.requiredPermissionCount > 0 ? 'ready' : 'wait'}">${count(account.grantedPermissionCount)} / ${count(account.requiredPermissionCount)}</strong></div></section>
    <section class="sac-health ${escapeHtml(account.health.tone)}" aria-label="Connection health"><div class="sac-health-top"><strong>${escapeHtml(account.health.label)}</strong><span>${account.health.checkedAt === null ? 'No probe' : `Checked ${moment(account.health.checkedAt)}${latency}`}</span></div><p>${escapeHtml(account.health.summary)}</p></section>
    <section class="sac-permissions" aria-label="Requested account permissions"><div class="sac-subhead"><strong>Permission ledger</strong><span>Least privilege · rehearsal</span></div><ul class="sac-permission-list">${permissions || '<li class="sac-permission wait"><span class="sac-permission-mark">!</span><div class="sac-permission-copy"><strong>No permissions declared</strong><p>The account fails closed.</p></div><span class="sac-permission-state">Missing</span></li>'}</ul></section>
    ${blockers(account)}
    <div class="sac-actions"><button class="sac-action" type="button" disabled aria-disabled="true" title="Account linking is disabled while the dark runtime boundary is engaged">${escapeHtml(account.linkActionLabel)} · unavailable</button><button class="sac-action sac-action-icon" type="button" disabled aria-disabled="true" title="Health probes are disabled" aria-label="Refresh ${escapeHtml(account.networkLabel)} health">↻</button></div>
    <details class="sac-disconnect"><summary>Disconnect &amp; revoke controls</summary><div class="sac-disconnect-body"><p>A live command would revoke the workspace-qualified provider link, invalidate future dispatch selection and preserve the non-secret audit record. No such command exists on this screen.</p><button class="sac-danger" type="button" disabled aria-disabled="true">${escapeHtml(account.disconnectActionLabel)} · effects off</button></div></details>
    <footer class="sac-account-foot"><span>Linked ${moment(account.linkedAt)}</span>${revoked || '<span>Illustrative account</span>'}</footer>
  </article></li>`;
}

function providerPanel(view: SocialAccountControlView): string {
  return `<section class="sac-provider" aria-labelledby="sac-provider-title"><header class="sac-section-head"><div><h2 id="sac-provider-title">Provider bridge</h2><p>The exact public-social contract this control room is designed around.</p></div><span class="sac-count">v1</span></header><div class="sac-provider-hero"><div class="sac-provider-brand"><span class="sac-provider-mark" aria-hidden="true">AY</span><div><span>${escapeHtml(view.provider.providerId)}</span><strong>${escapeHtml(view.provider.providerLabel)}</strong></div></div><p class="sac-provider-status">${escapeHtml(view.provider.configurationLabel)}</p></div><ul class="sac-contract"><li><span>Contract</span><strong>${escapeHtml(view.provider.contractVersion)}</strong></li><li><span>Proven launch network</span><strong>${escapeHtml(view.provider.readyNetworks.join(', ').toUpperCase())}</strong></li><li><span>X BYO link evidence</span><strong>${view.provider.xByoLinkEvidenceRequired ? 'REQUIRED' : 'NOT DECLARED'}</strong></li><li><span>Origin boundary</span><strong>${escapeHtml(view.provider.contractOrigin)}</strong></li><li><span>Redirects</span><strong>${escapeHtml(view.provider.redirectPolicy.toUpperCase())}</strong></li><li><span>Response ceiling</span><strong>${count(view.provider.maximumResponseKilobytes)} KiB</strong></li><li><span>Durable single caller</span><strong>${view.provider.durableCallerRequired ? 'REQUIRED' : 'NOT DECLARED'}</strong></li><li><span>Live client</span><strong>${view.provider.liveClientAvailable ? 'AVAILABLE' : 'NOT WIRED'}</strong></li></ul><p class="sac-provider-note"><strong>Honest boundary:</strong> X is the only publication payload proven by the current contract. Other account cards map the future connection experience; they do not imply dispatch support.</p></section>`;
}

function ladderPanel(): string {
  return `<section class="sac-ladder" aria-labelledby="sac-ladder-title"><header class="sac-section-head"><div><h2 id="sac-ladder-title">Activation ladder</h2><p>Every rung must be evidenced in order.</p></div></header><ol><li><div><strong>Workspace profile</strong><span>One isolated provider profile per Growth HQ workspace.</span></div></li><li><div><strong>Account authorisation</strong><span>Platform-native consent with exact least-privilege scopes.</span></div></li><li><div><strong>Identity &amp; health</strong><span>Bounded, current evidence for the intended page or profile.</span></div></li><li><div><strong>Dispatch contract</strong><span>Network-specific payload, idempotency and reconciliation proof.</span></div></li><li><div><strong>Founder activation</strong><span>A separate decision after every effects switch is reviewed.</span></div></li></ol></section>`;
}

export function renderSocialAccountControlBody(view: SocialAccountControlView): string {
  const cards = view.accounts.map(accountCard).join('');
  const fixture = view.illustrative
    ? '<section class="sac-fixture" role="status" aria-label="Illustrative data boundary"><strong>FICTIONAL ACCOUNT REHEARSAL</strong><p>Every handle, profile binding, permission and health observation below is invented test data. Nothing was read from Ayrshare or any social network.</p></section>'
    : '';
  const truncation = view.inputTruncated
    ? '<p class="sac-truncated">The account catalogue exceeded its safe display bound. Extra accounts are hidden and cannot qualify as ready.</p>'
    : '';
  return `${renderContentWorkspaceNavigation('connections', { companyAssetsAvailable: true, composerAvailable: true, brandBrainAvailable: true })}<style data-property-predator-social-account-control>${SOCIAL_ACCOUNT_CONTROL_STYLE}</style><article class="sac" aria-labelledby="sac-title" data-provider-effects="off" data-account-linking-effects="off" data-publishing-effects="off" data-revocation-effects="off" data-command-boundary="absent">
    <header class="sac-hero"><div class="sac-hero-copy"><span class="sac-kicker">Property Predator · Social command</span><h1 id="sac-title">Plug in the audience.<br><em>Keep the power off.</em></h1><p>A Hootsuite-class account control room for linking identities, reading health, proving permissions and revoking access—without hiding what is real, what is missing or what is still deliberately dark.</p></div><aside class="sac-lock" aria-label="Global social effects lock"><div class="sac-lock-top"><span>Global social boundary</span><b>${view.runtimeLocked ? 'LOCKED' : 'INVALID'}</b></div><h2>Emergency pause engaged</h2><p>Account linking, health probes, publishing and revocation commands are all unavailable. Live connections: ${count(view.metrics.liveConnections)}.</p></aside></header>
    <section class="sac-boundary" aria-label="Dark runtime boundary"><span class="sac-boundary-mark">Dark runtime</span><p><strong>Control surface only.</strong> Buttons demonstrate the intended workflow but cannot open OAuth, call Ayrshare, publish content or revoke an account.</p><span class="sac-boundary-badge">4 effects switches OFF</span></section>${fixture}
    <section class="sac-metrics" aria-label="Social account readiness"><article class="sac-metric"><small>Account slots</small><strong>${count(view.metrics.accounts)}</strong><span>Fictional identities</span></article><article class="sac-metric"><small>Rehearsal linked</small><strong>${count(view.metrics.rehearsalLinked)}</strong><span>Local status only</span></article><article class="sac-metric ready"><small>Healthy evidence</small><strong>${count(view.metrics.healthy)}</strong><span>Current observations</span></article><article class="sac-metric ready"><small>Contract ready</small><strong>${count(view.metrics.rehearsalReady)}</strong><span>X-only v1 seam</span></article><article class="sac-metric locked"><small>Blocked</small><strong>${count(view.metrics.blocked)}</strong><span>Exact reasons below</span></article><article class="sac-metric locked"><small>Live connections</small><strong>${count(view.metrics.liveConnections)}</strong><span>Deliberately zero</span></article></section>
    <div class="sac-layout"><aside class="sac-sidebar">${providerPanel(view)}${ladderPanel()}</aside><section class="sac-catalog" aria-labelledby="sac-catalog-title"><header class="sac-section-head"><div><h2 id="sac-catalog-title">Social accounts</h2><p>Linking, permission, health and revocation states in one operator view.</p></div><span class="sac-count">${count(view.metrics.accounts)} slots</span></header><ul class="sac-accounts">${cards || '<li><p class="sac-truncated">No account slots exist. The social rail remains closed.</p></li>'}</ul>${truncation}</section></div>
    <footer class="sac-footer"><span><strong>${escapeHtml(view.workspaceName)}</strong> · snapshot ${moment(view.asOf)}</span><span>Dataset ${escapeHtml(view.dataset)} · no network or command boundary</span></footer>
  </article>`;
}
