/** Server-rendered, side-effect-free Property Predator Webinar Studio UI. */

import { escapeHtml } from './ui.js';
import type {
  WebinarEngagementSignalView,
  WebinarGateCheckView,
  WebinarProofView,
  WebinarRegistrationStageView,
  WebinarReplayStepView,
  WebinarRunSegmentView,
  WebinarSpeakerView,
  WebinarStudioView,
} from './webinar-studio-presenter.js';

const WEBINAR_STUDIO_STYLE = `
  .wbs{--bg:#07090b;--panel:#0d1114;--lift:#12181c;--soft:#090c0e;--line:#253138;--line2:#394850;--ink:#f4f7f5;--muted:#a8b4b7;--faint:#758489;--teal:#00e5cc;--teal2:#67f1df;--teal-dim:#082923;--amber:#f2b84b;--red:#ff7169;--green:#73d7a2;min-width:0;background:var(--bg);border:1px solid #020304;color:var(--ink);font-family:var(--sans,ui-sans-serif,system-ui,sans-serif);overflow:hidden}.wbs *{box-sizing:border-box}.wbs h1,.wbs h2,.wbs h3,.wbs p{margin-top:0}.wbs code{font-family:var(--mono,ui-monospace,monospace);overflow-wrap:anywhere}.wbs ol,.wbs ul{list-style:none;margin:0;padding:0}
  .wbs-hero{position:relative;display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,370px);gap:28px;align-items:end;padding:33px 34px 28px;border-bottom:1px solid var(--line);background:radial-gradient(circle at 84% 8%,rgba(0,229,204,.17),transparent 32%),linear-gradient(135deg,#11191c,#07090b 69%);overflow:hidden}.wbs-hero:after{content:"";position:absolute;right:31%;top:-94px;width:214px;height:214px;border:1px solid rgba(0,229,204,.13);transform:rotate(45deg);pointer-events:none}.wbs-kicker{position:relative;color:var(--teal);font:850 12px/1.2 var(--mono,monospace);letter-spacing:.14em;text-transform:uppercase}.wbs-hero h1{position:relative;margin:10px 0 12px;font-family:var(--display,var(--sans));font-size:clamp(2.35rem,5vw,5rem);font-weight:600;line-height:.89;letter-spacing:-.052em}.wbs-hero h1 em{color:var(--teal);font-style:normal}.wbs-hero-copy>p{position:relative;max-width:760px;margin:0;color:var(--muted);font-size:14px;line-height:1.65}.wbs-event-ticket{position:relative;border:1px solid var(--line2);background:rgba(4,7,8,.78);padding:16px 17px}.wbs-event-ticket>span{display:block;color:var(--faint);font:800 10px var(--mono,monospace);letter-spacing:.09em;text-transform:uppercase}.wbs-event-ticket h2{margin:8px 0 8px;font-size:18px;line-height:1.28}.wbs-ticket-time{display:grid;grid-template-columns:1fr auto;gap:10px;padding:10px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line);color:var(--muted);font-size:11px}.wbs-ticket-time strong{color:var(--ink)}.wbs-ticket-foot{display:flex;justify-content:space-between;gap:10px;margin-top:10px;color:var(--faint);font:800 10px var(--mono,monospace);text-transform:uppercase}
  .wbs-boundary{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:14px;align-items:center;padding:12px 34px;border-bottom:1px solid var(--line);background:#090d0f}.wbs-boundary-mark{color:var(--teal);font:850 11px var(--mono,monospace);letter-spacing:.09em;text-transform:uppercase}.wbs-boundary p{margin:0;color:var(--muted);font-size:12px;line-height:1.5}.wbs-boundary p strong{color:var(--ink)}.wbs-safety{border:1px solid var(--line2);padding:5px 9px;color:var(--faint);font:800 10px var(--mono,monospace);letter-spacing:.05em;text-transform:uppercase;white-space:nowrap}
  .wbs-gate{display:grid;grid-template-columns:minmax(310px,1fr) repeat(4,minmax(110px,150px));border-bottom:1px solid var(--line);background:var(--panel)}.wbs-gate-main{position:relative;display:grid;grid-template-columns:64px minmax(0,1fr);gap:14px;align-items:center;padding:19px 22px;border-right:1px solid var(--line);overflow:hidden}.wbs-gate-main:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--red)}.wbs-gate-main.open:before{background:var(--teal)}.wbs-gate-score{width:58px;height:58px;display:grid;place-items:center;border:1px solid var(--line2);border-radius:50%;color:var(--red);font:900 13px var(--mono,monospace)}.wbs-gate-main.open .wbs-gate-score{border-color:#28776d;color:var(--teal)}.wbs-gate-copy span{color:var(--red);font:900 10px var(--mono,monospace);letter-spacing:.08em;text-transform:uppercase}.wbs-gate-main.open .wbs-gate-copy span{color:var(--teal)}.wbs-gate-copy h2{margin:6px 0 4px;font-size:17px}.wbs-gate-copy p{margin:0;color:var(--muted);font-size:11px;line-height:1.5}.wbs-stat{display:grid;align-content:center;padding:15px;border-right:1px solid var(--line)}.wbs-stat:last-child{border-right:0}.wbs-stat span{color:var(--faint);font:800 9px var(--mono,monospace);letter-spacing:.06em;text-transform:uppercase}.wbs-stat strong{margin-top:7px;font:900 20px var(--mono,monospace)}.wbs-stat strong b{color:var(--teal);font:inherit}.wbs-stat small{margin-top:3px;color:var(--muted);font-size:10px}
  .wbs-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,340px);gap:14px;padding:16px}.wbs-main,.wbs-side{display:grid;align-content:start;gap:14px;min-width:0}.wbs-panel{min-width:0;border:1px solid var(--line);background:var(--panel)}.wbs-panel-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;padding:17px 18px 14px;border-bottom:1px solid var(--line)}.wbs-panel-head h2{margin:0;font-size:16px}.wbs-panel-head p{margin:4px 0 0;color:var(--muted);font-size:11px;line-height:1.45}.wbs-count,.wbs-pill{border:1px solid var(--line2);padding:4px 8px;color:var(--muted);font:800 10px var(--mono,monospace);white-space:nowrap}.wbs-pill.good{border-color:#2b766e;color:var(--teal)}.wbs-pill.warn{border-color:#745f34;color:var(--amber)}.wbs-pill.bad{border-color:#75413d;color:var(--red)}
  .wbs-blueprint{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(230px,.8fr);gap:0}.wbs-blueprint-copy{padding:18px;border-right:1px solid var(--line)}.wbs-blueprint-copy>span{color:var(--teal);font:850 10px var(--mono,monospace);letter-spacing:.08em;text-transform:uppercase}.wbs-blueprint-copy h3{margin:8px 0 7px;font-size:21px}.wbs-blueprint-copy p{margin:0;color:var(--muted);font-size:12px;line-height:1.6}.wbs-blueprint-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:15px}.wbs-blueprint-meta div{border:1px solid var(--line);background:var(--soft);padding:9px}.wbs-blueprint-meta span{display:block;color:var(--faint);font:800 9px var(--mono,monospace);text-transform:uppercase}.wbs-blueprint-meta strong{display:block;margin-top:5px;font-size:11px}.wbs-proof-list{padding:6px 14px}.wbs-proof{display:grid;grid-template-columns:21px minmax(0,1fr) auto;gap:8px;align-items:start;padding:9px 0;border-bottom:1px solid var(--line)}.wbs-proof:last-child{border-bottom:0}.wbs-proof-mark{width:19px;height:19px;display:grid;place-items:center;border:1px solid var(--line2);border-radius:50%;color:var(--red);font:900 10px var(--mono,monospace)}.wbs-proof.pass .wbs-proof-mark{border-color:#28776d;color:var(--teal)}.wbs-proof-copy strong{display:block;font-size:10px}.wbs-proof-copy p{margin:3px 0 0;color:var(--faint);font-size:9px;line-height:1.4}.wbs-proof-state{color:var(--red);font:900 9px var(--mono,monospace);text-transform:uppercase}.wbs-proof.pass .wbs-proof-state{color:var(--teal)}
  .wbs-funnel{display:grid;gap:8px;padding:13px}.wbs-funnel-stage{display:grid;grid-template-columns:28px minmax(120px,.65fr) minmax(140px,1fr) 86px;gap:10px;align-items:center}.wbs-index{width:27px;height:27px;display:grid;place-items:center;border:1px solid var(--line2);color:var(--teal);font:900 9px var(--mono,monospace)}.wbs-stage-copy strong{display:block;font-size:11px}.wbs-stage-copy span{display:block;margin-top:3px;color:var(--faint);font-size:9px;line-height:1.35}.wbs-funnel-track{height:25px;border:1px solid var(--line);background:#080b0d;padding:4px;overflow:hidden}.wbs-funnel-fill{height:100%;min-width:4px;background:linear-gradient(90deg,#12675e,var(--teal));opacity:.86}.wbs-stage-number{text-align:right}.wbs-stage-number strong{display:block;font:900 14px var(--mono,monospace)}.wbs-stage-number span{color:var(--faint);font:800 8px var(--mono,monospace);text-transform:uppercase}
  .wbs-speakers{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:12px;border-bottom:1px solid var(--line)}.wbs-speaker{display:grid;grid-template-columns:38px minmax(0,1fr);gap:9px;border:1px solid var(--line);background:var(--lift);padding:10px}.wbs-avatar{width:36px;height:36px;display:grid;place-items:center;border:1px solid #28776d;border-radius:50%;color:var(--teal);font:900 10px var(--mono,monospace)}.wbs-speaker strong{display:block;font-size:11px}.wbs-speaker b{display:block;margin-top:2px;color:var(--teal);font:800 9px var(--mono,monospace);text-transform:uppercase}.wbs-speaker p{margin:5px 0 0;color:var(--faint);font-size:9px;line-height:1.4}.wbs-speaker small{display:block;margin-top:6px;color:var(--muted);font-size:9px}.wbs-timeline{padding:3px 14px 7px}.wbs-segment{display:grid;grid-template-columns:62px 11px minmax(0,1fr) auto;gap:9px;align-items:stretch}.wbs-segment-time{padding:12px 0;text-align:right;color:var(--muted);font:850 9px var(--mono,monospace)}.wbs-segment-spine{position:relative}.wbs-segment-spine:before{content:"";position:absolute;left:5px;top:0;bottom:0;width:1px;background:var(--line2)}.wbs-segment-dot{position:absolute;left:1px;top:15px;width:9px;height:9px;border:2px solid var(--panel);border-radius:50%;background:var(--teal);box-shadow:0 0 0 1px #28776d}.wbs-segment-copy{padding:10px 0;border-bottom:1px solid var(--line)}.wbs-segment-copy>span{color:var(--teal);font:850 8px var(--mono,monospace);text-transform:uppercase}.wbs-segment-copy h3{margin:4px 0 3px;font-size:11px}.wbs-segment-copy p{margin:0;color:var(--faint);font-size:9px;line-height:1.45}.wbs-segment-meta{min-width:115px;padding:11px 0 10px 8px;border-bottom:1px solid var(--line);text-align:right}.wbs-segment-meta strong{display:block;font-size:9px}.wbs-segment-meta span{display:block;margin-top:4px;color:var(--faint);font:800 8px var(--mono,monospace)}
  .wbs-signals{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:11px}.wbs-signal{border:1px solid var(--line);background:var(--lift);padding:11px}.wbs-signal-head{display:flex;justify-content:space-between;gap:8px;color:var(--teal);font:850 8px var(--mono,monospace);text-transform:uppercase}.wbs-signal h3{margin:7px 0 4px;font-size:11px}.wbs-signal p{margin:0;color:var(--faint);font-size:9px;line-height:1.4}.wbs-signal-foot{display:flex;justify-content:space-between;gap:8px;margin-top:9px;padding-top:8px;border-top:1px solid var(--line);font:800 9px var(--mono,monospace)}.wbs-signal-foot b{color:var(--teal)}
  .wbs-replay{padding:5px 14px}.wbs-replay-step{display:grid;grid-template-columns:31px minmax(0,1fr) auto;gap:9px;align-items:center;padding:10px 0;border-bottom:1px solid var(--line)}.wbs-replay-step:last-child{border-bottom:0}.wbs-replay-code{width:29px;height:29px;display:grid;place-items:center;border:1px solid #28776d;color:var(--teal);font:900 9px var(--mono,monospace)}.wbs-replay-copy strong{display:block;font-size:10px}.wbs-replay-copy span{display:block;margin-top:3px;color:var(--faint);font-size:9px}.wbs-replay-meta{text-align:right}.wbs-replay-meta strong{display:block;color:var(--teal);font:850 9px var(--mono,monospace)}.wbs-replay-meta span{display:block;margin-top:4px;color:var(--faint);font:800 8px var(--mono,monospace);text-transform:uppercase}
  .wbs-adapter{padding:15px}.wbs-adapter-status{display:flex;align-items:center;justify-content:space-between;gap:12px;padding-bottom:12px;border-bottom:1px solid var(--line)}.wbs-adapter-status strong{display:flex;align-items:center;gap:8px;font-size:11px}.wbs-adapter-status strong:before{content:"";width:8px;height:8px;border-radius:50%;background:var(--teal);box-shadow:0 0 0 5px rgba(0,229,204,.09)}.wbs-adapter-status span{color:var(--teal);font:900 9px var(--mono,monospace);text-transform:uppercase}.wbs-capabilities{display:flex;flex-wrap:wrap;gap:5px;padding:11px 0}.wbs-capabilities span{border:1px solid var(--line2);border-radius:999px;padding:4px 7px;color:var(--muted);font-size:9px}.wbs-adapter dl{display:grid;grid-template-columns:auto 1fr;gap:7px 10px;margin:0;padding-top:10px;border-top:1px solid var(--line);font-size:9px}.wbs-adapter dt{color:var(--faint)}.wbs-adapter dd{margin:0;text-align:right;color:var(--muted);overflow-wrap:anywhere}
  .wbs-ledger{padding:5px 14px}.wbs-check{display:grid;grid-template-columns:20px minmax(0,1fr) auto;gap:8px;align-items:start;padding:9px 0;border-bottom:1px solid var(--line)}.wbs-check:last-child{border-bottom:0}.wbs-check-mark{width:18px;height:18px;display:grid;place-items:center;border:1px solid #75413d;color:var(--red);font:900 9px var(--mono,monospace)}.wbs-check.pass .wbs-check-mark{border-color:#28776d;color:var(--teal)}.wbs-check strong{display:block;font-size:9px}.wbs-check p{margin:3px 0 0;color:var(--faint);font-size:8px;line-height:1.4}.wbs-check-state{color:var(--red);font:900 8px var(--mono,monospace);text-transform:uppercase}.wbs-check.pass .wbs-check-state{color:var(--teal)}
  .wbs-controls{padding:14px;border-top:1px solid var(--line);background:var(--soft)}.wbs-control-row{display:grid;grid-template-columns:1fr 1fr;gap:7px}.wbs-control{min-height:46px;border:1px solid var(--line2);background:#101519;color:var(--faint);padding:9px;font:900 9px var(--mono,monospace);text-transform:uppercase;cursor:not-allowed}.wbs-control.live{border-color:#6b3e3a;color:#c37e78}.wbs-controls p{margin:9px 0 0;color:var(--faint);font-size:9px;line-height:1.45}.wbs-controls p strong{color:var(--muted)}.wbs-truncation{margin:0;padding:11px 18px;border-top:1px solid var(--line);color:var(--amber);font-size:10px}.wbs-footer{display:flex;justify-content:space-between;gap:14px;padding:13px 18px;border-top:1px solid var(--line);background:#080a0c;color:var(--faint);font-size:10px}.wbs-footer strong{color:var(--muted)}
  @media(max-width:1120px){.wbs-gate{grid-template-columns:minmax(310px,1fr) repeat(2,minmax(110px,1fr))}.wbs-stat:nth-child(n+4){border-top:1px solid var(--line)}.wbs-layout{grid-template-columns:minmax(0,1fr) 300px}.wbs-blueprint{grid-template-columns:1fr}.wbs-blueprint-copy{border-right:0;border-bottom:1px solid var(--line)}}
  @media(max-width:850px){.wbs-hero{grid-template-columns:1fr;padding:25px 20px 22px}.wbs-boundary{grid-template-columns:1fr;padding:12px 20px}.wbs-safety{justify-self:start}.wbs-gate{grid-template-columns:repeat(2,minmax(0,1fr))}.wbs-gate-main{grid-column:1/-1;border-right:0}.wbs-stat{border-top:1px solid var(--line)}.wbs-stat:nth-child(odd){border-right:0}.wbs-layout{grid-template-columns:1fr;padding:10px}.wbs-side{grid-row:1}.wbs-speakers,.wbs-signals{grid-template-columns:1fr}}
  @media(max-width:540px){.wbs-hero h1{font-size:2.45rem}.wbs-gate{grid-template-columns:1fr}.wbs-gate-main{grid-column:auto;grid-template-columns:52px 1fr}.wbs-gate-score{width:48px;height:48px}.wbs-stat,.wbs-stat:nth-child(odd){border-right:0}.wbs-panel-head,.wbs-footer{align-items:stretch;flex-direction:column}.wbs-blueprint-meta{grid-template-columns:1fr}.wbs-funnel-stage{grid-template-columns:28px minmax(0,1fr) 72px}.wbs-funnel-track{grid-column:2/-1}.wbs-segment{grid-template-columns:50px 11px minmax(0,1fr)}.wbs-segment-meta{grid-column:3;min-width:0;padding:0 0 10px;text-align:left}.wbs-replay-step{grid-template-columns:31px minmax(0,1fr)}.wbs-replay-meta{grid-column:2;text-align:left}.wbs-control-row{grid-template-columns:1fr}}
  @media(forced-colors:active){.wbs,.wbs-panel,.wbs-event-ticket,.wbs-speaker,.wbs-signal,.wbs-control{forced-color-adjust:auto}.wbs-gate-main:before{width:6px}}
  @media(prefers-reduced-motion:reduce){.wbs *{scroll-behavior:auto!important;transition:none!important}}
`;

function safeNumber(value: number | null): string {
  return value === null ? '—' : String(Math.max(0, Math.min(Math.floor(value), 1_000_000_000)));
}

function time(value: string | null): string {
  return value
    ? `<time datetime="${escapeHtml(value)}">${escapeHtml(value.replace('T', ' ').replace('.000Z', ' UTC'))}</time>`
    : 'Not recorded';
}

function proofRow(proof: WebinarProofView): string {
  return `<li class="wbs-proof ${proof.passes ? 'pass' : 'fail'}"><span class="wbs-proof-mark" aria-hidden="true">${proof.passes ? '✓' : '!'}</span><div class="wbs-proof-copy"><strong>${escapeHtml(proof.label)}${proof.required ? '' : ' · optional'}</strong><p>${escapeHtml(proof.detail)}${proof.evidenceRef ? ` · <code>${escapeHtml(proof.evidenceRef)}</code>` : ''}</p></div><span class="wbs-proof-state">${escapeHtml(proof.stateLabel)}</span></li>`;
}

function funnelStage(stage: WebinarRegistrationStageView): string {
  return `<li class="wbs-funnel-stage"><span class="wbs-index" aria-hidden="true">${escapeHtml(stage.indexLabel)}</span><div class="wbs-stage-copy"><strong>${escapeHtml(stage.label)}</strong><span>${escapeHtml(stage.detail)}</span></div><div class="wbs-funnel-track" aria-hidden="true"><div class="wbs-funnel-fill" style="width:${safeNumber(stage.widthPercent)}%"></div></div><div class="wbs-stage-number"><strong>${escapeHtml(stage.countLabel)}</strong><span>${escapeHtml(stage.truthLabel)}</span></div></li>`;
}

function speakerCard(speaker: WebinarSpeakerView): string {
  return `<li class="wbs-speaker"><span class="wbs-avatar" aria-hidden="true">${escapeHtml(speaker.initials)}</span><div><strong>${escapeHtml(speaker.name)}</strong><b>${escapeHtml(speaker.role)}</b><p>${escapeHtml(speaker.promise)}</p><small>${safeNumber(speaker.segmentCount)} run-of-show segment${speaker.segmentCount === 1 ? '' : 's'} · ${escapeHtml(speaker.readiness)}</small></div></li>`;
}

function segmentRow(segment: WebinarRunSegmentView): string {
  return `<li class="wbs-segment"><span class="wbs-segment-time">${escapeHtml(segment.timeLabel)}</span><span class="wbs-segment-spine" aria-hidden="true"><i class="wbs-segment-dot"></i></span><div class="wbs-segment-copy"><span>${escapeHtml(segment.indexLabel)} · ${escapeHtml(segment.kindLabel)}</span><h3>${escapeHtml(segment.title)}</h3><p>${escapeHtml(segment.operatorCue)}</p></div><div class="wbs-segment-meta"><strong>${escapeHtml(segment.speakerName)}</strong><span>${escapeHtml(segment.audienceLabel)} · ${escapeHtml(segment.attendanceTruth.toUpperCase())}</span></div></li>`;
}

function signalCard(signal: WebinarEngagementSignalView): string {
  const score = signal.leadScoreDelta >= 0 ? `+${signal.leadScoreDelta}` : String(signal.leadScoreDelta);
  return `<li class="wbs-signal"><div class="wbs-signal-head"><span>${escapeHtml(signal.kindLabel)}</span><span>${escapeHtml(signal.timeLabel)}</span></div><h3>${escapeHtml(signal.label)}</h3><p>${escapeHtml(signal.detail)}</p><div class="wbs-signal-foot"><span>${escapeHtml(signal.peopleLabel)} · ${escapeHtml(signal.truthLabel)}</span><b>${escapeHtml(score)} lead score</b></div></li>`;
}

function replayRow(step: WebinarReplayStepView): string {
  return `<li class="wbs-replay-step"><span class="wbs-replay-code" aria-hidden="true">${escapeHtml(step.indexLabel)}</span><div class="wbs-replay-copy"><strong>${escapeHtml(step.channelLabel)} · ${escapeHtml(step.scheduleLabel)}</strong><span>${escapeHtml(step.audienceLabel)} · template <code>${escapeHtml(step.templateVersionId)}</code></span></div><div class="wbs-replay-meta"><strong>${step.gatePasses ? 'TEST ready' : 'Blocked'}</strong><span>${step.exactApproval ? 'exact approval' : 'approval mismatch'} · consent required</span></div></li>`;
}

function checkRow(check: WebinarGateCheckView): string {
  return `<li class="wbs-check ${check.passed ? 'pass' : 'fail'}"><span class="wbs-check-mark" aria-hidden="true">${check.passed ? '✓' : '!'}</span><div><strong>${escapeHtml(check.label)}</strong><p>${escapeHtml(check.detail)}</p></div><span class="wbs-check-state">${check.passed ? 'Pass' : 'Block'}</span></li>`;
}

function blueprintPanel(view: WebinarStudioView): string {
  return `<section class="wbs-panel" aria-labelledby="wbs-blueprint-title"><header class="wbs-panel-head"><div><h2 id="wbs-blueprint-title">Event blueprint &amp; readiness</h2><p>The exact event contract that would be used to create a provider event after a separately authorised connection.</p></div><span class="wbs-pill good">immutable v${safeNumber(view.event.revisionNumber)}</span></header><div class="wbs-blueprint"><div class="wbs-blueprint-copy"><span>${escapeHtml(view.event.lifecycle.replace('_', ' '))} · ${escapeHtml(view.event.environment.toUpperCase())}</span><h3>${escapeHtml(view.event.title)}</h3><p>${escapeHtml(view.event.promise)}</p><div class="wbs-blueprint-meta"><div><span>Host</span><strong>${escapeHtml(view.event.hostLabel)}</strong></div><div><span>Runtime</span><strong>${safeNumber(view.event.durationMinutes)} minutes</strong></div><div><span>Revision proof</span><strong><code>${escapeHtml(view.event.shortHash)}…</code></strong></div></div></div><ul class="wbs-proof-list" aria-label="Webinar readiness proofs">${view.proofs.map(proofRow).join('')}</ul></div></section>`;
}

function providerPanel(view: WebinarStudioView): string {
  const capabilities = view.adapter.capabilities.map((capability) => `<span>${escapeHtml(capability)}</span>`).join('');
  return `<section class="wbs-panel" aria-labelledby="wbs-provider-title"><header class="wbs-panel-head"><div><h2 id="wbs-provider-title">Provider adapter readiness</h2><p>Contract status only. No credentials or provider controls exist here.</p></div><span class="wbs-pill ${view.adapter.safeForTest ? 'good' : 'bad'}">${escapeHtml(view.adapter.stateLabel)}</span></header><div class="wbs-adapter"><div class="wbs-adapter-status"><strong>${escapeHtml(view.adapter.providerLabel)}</strong><span>zero effects</span></div><div class="wbs-capabilities">${capabilities}</div><dl><dt>Environment</dt><dd>${escapeHtml(view.adapter.environment.toUpperCase())}</dd><dt>Webhook contract</dt><dd><code>${escapeHtml(view.adapter.webhookContractVersion)}</code></dd><dt>Health proof</dt><dd>${escapeHtml(view.adapter.checkedLabel)}</dd><dt>Provider effects</dt><dd>${escapeHtml(String(view.adapter.providerEffects))}</dd></dl></div></section>`;
}

function ledgerPanel(view: WebinarStudioView): string {
  return `<section class="wbs-panel" aria-labelledby="wbs-ledger-title"><header class="wbs-panel-head"><div><h2 id="wbs-ledger-title">Rehearsal ledger</h2><p>Same immutable facts in, same gate result out.</p></div><span class="wbs-count">${safeNumber(view.rehearsalGate.passed)}/${safeNumber(view.rehearsalGate.total)}</span></header><ul class="wbs-ledger">${view.rehearsalGate.checks.map(checkRow).join('')}</ul><div class="wbs-controls" aria-label="Disabled webinar controls"><div class="wbs-control-row"><button class="wbs-control" type="button" disabled aria-disabled="true">Create TEST provider event · unavailable</button><button class="wbs-control live" type="button" disabled aria-disabled="true">Go live · locked</button></div><p><strong>No command boundary.</strong> This view cannot create registrations, open a room, broadcast, send reminders or call a provider.</p></div></section>`;
}

export function renderWebinarStudioBody(view: WebinarStudioView): string {
  const gateTone = view.rehearsalGate.open ? 'open' : 'closed';
  const registered = view.registrationSummary.registeredCount === null ? '—' : view.registrationSummary.registeredCount.toLocaleString('en-GB');
  const showUp = view.registrationSummary.showUpRate === null ? '—' : `${view.registrationSummary.showUpRate}%`;
  const truncation = view.inputTruncated
    ? '<p class="wbs-truncation">The webinar snapshot exceeded a safe evaluation bound. TEST rehearsal fails closed until the complete event is evaluated.</p>'
    : '';
  return `<style data-property-predator-webinar-studio>${WEBINAR_STUDIO_STYLE}</style><article class="wbs" aria-labelledby="wbs-title" data-environment="test" data-provider-effects="none" data-command-boundary="absent" data-live-broadcast="unavailable">
    <header class="wbs-hero"><div class="wbs-hero-copy"><div class="wbs-kicker">Property Predator · Webinar Studio</div><h1 id="wbs-title">Build the room.<br><em>Engineer the decision.</em></h1><p>One sharp control room for the event, registration journey, live teaching rhythm, engagement evidence and consent-gated replay follow-up.</p></div><aside class="wbs-event-ticket" aria-label="Selected TEST webinar"><span>Selected TEST event</span><h2>${escapeHtml(view.event.title)}</h2><div class="wbs-ticket-time"><strong>${escapeHtml(view.event.scheduledLabel)} UTC</strong><span>${safeNumber(view.event.durationMinutes)} min</span></div><div class="wbs-ticket-foot"><span>${escapeHtml(view.event.timezoneLabel)}</span><span>rev ${safeNumber(view.event.revisionNumber)} · ${escapeHtml(view.event.shortHash)}…</span></div></aside></header>
    <section class="wbs-boundary" aria-label="Webinar safety boundary"><span class="wbs-boundary-mark">TEST-only studio</span><p><strong>Nothing can leave this room.</strong> Fictional registrations, simulated attendance and disabled provider controls only. No live account, person, reminder, webinar room or broadcast is connected.</p><span class="wbs-safety">No register · no send · no broadcast</span></section>
    <section class="wbs-gate" aria-label="Deterministic webinar rehearsal gate"><div class="wbs-gate-main ${gateTone}"><div class="wbs-gate-score" aria-label="${safeNumber(view.rehearsalGate.passed)} of ${safeNumber(view.rehearsalGate.total)} checks pass">${safeNumber(view.rehearsalGate.passed)}/${safeNumber(view.rehearsalGate.total)}</div><div class="wbs-gate-copy"><span>${escapeHtml(view.rehearsalGate.label)}</span><h2>${escapeHtml(view.rehearsalGate.headline)}</h2><p>${escapeHtml(view.rehearsalGate.detail)}</p></div></div><div class="wbs-stat"><span>Planned registrations</span><strong><b>${escapeHtml(registered)}</b></strong><small>${escapeHtml(view.registrationSummary.truthLabel)}</small></div><div class="wbs-stat"><span>Show-up plan</span><strong>${escapeHtml(showUp)}</strong><small>not observed performance</small></div><div class="wbs-stat"><span>Room segments</span><strong>${safeNumber(view.runOfShow.length)}</strong><small>${safeNumber(view.event.durationMinutes)} minute arc</small></div><div class="wbs-stat"><span>Replay rails</span><strong>${safeNumber(view.replay.length)}</strong><small>simulated + consent-gated</small></div></section>
    <div class="wbs-layout"><main class="wbs-main">${blueprintPanel(view)}<section class="wbs-panel" aria-labelledby="wbs-funnel-title"><header class="wbs-panel-head"><div><h2 id="wbs-funnel-title">Registration funnel</h2><p>A visible conversion plan whose SIMULATED labels cannot be mistaken for measured performance.</p></div><span class="wbs-count">${safeNumber(view.registration.length)} stages</span></header><ol class="wbs-funnel">${view.registration.map(funnelStage).join('')}</ol></section><section class="wbs-panel" aria-labelledby="wbs-run-title"><header class="wbs-panel-head"><div><h2 id="wbs-run-title">Attendance timeline &amp; run of show</h2><p>The operational minute-by-minute spine: speaker, cue, asset and planned audience truth.</p></div><span class="wbs-count">${safeNumber(view.event.durationMinutes)} min</span></header><ul class="wbs-speakers" aria-label="Speaker desk">${view.speakers.map(speakerCard).join('')}</ul><ol class="wbs-timeline">${view.runOfShow.map(segmentRow).join('')}</ol></section><section class="wbs-panel" aria-labelledby="wbs-signals-title"><header class="wbs-panel-head"><div><h2 id="wbs-signals-title">Engagement &amp; Lead 360 signals</h2><p>Every meaningful room behaviour becomes an explainable scoring event.</p></div><span class="wbs-count">${safeNumber(view.engagementSignals.length)} signals</span></header><ul class="wbs-signals">${view.engagementSignals.map(signalCard).join('')}</ul></section><section class="wbs-panel" aria-labelledby="wbs-replay-title"><header class="wbs-panel-head"><div><h2 id="wbs-replay-title">Replay follow-up journey</h2><p>Exactly approved versions, audience segments and a consent check before every simulated delivery.</p></div><span class="wbs-pill warn">TEST queue only</span></header><ol class="wbs-replay">${view.replay.map(replayRow).join('')}</ol></section></main><aside class="wbs-side">${providerPanel(view)}${ledgerPanel(view)}<section class="wbs-panel" aria-labelledby="wbs-truth-title"><header class="wbs-panel-head"><div><h2 id="wbs-truth-title">Evidence truth</h2><p>The studio never paints planning assumptions as results.</p></div><span class="wbs-count">labelled</span></header><div class="wbs-adapter"><dl><dt>SIMULATED values</dt><dd>${safeNumber(view.truthSummary.simulated)}</dd><dt>MEASURED values</dt><dd>${safeNumber(view.truthSummary.measured)}</dd><dt>UNAVAILABLE values</dt><dd>${safeNumber(view.truthSummary.unavailable)}</dd><dt>Snapshot</dt><dd>${time(view.asOf)}</dd></dl></div></section></aside></div>${truncation}
    <footer class="wbs-footer"><span><strong>${escapeHtml(view.workspaceName)}</strong> · event <code>${escapeHtml(view.event.eventId)}</code></span><span>Provider effects ${escapeHtml(view.providerEffects)} · live broadcast ${view.liveBroadcastAvailable ? 'available' : 'unavailable'}</span></footer>
  </article>`;
}
