import type { PortalZernioMessagingSnapshot } from './zernio-messaging-service.js';
import { ZERNIO_MESSAGING_ROUTE } from './zernio-messaging-service.js';
import { escapeHtml } from './ui.js';

function time(value: string): string {
  return new Intl.DateTimeFormat('en-GB', {
    day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: 'Europe/London',
  }).format(new Date(value));
}

function style(): string {
  return `<style>
.zmsg{max-width:1480px;margin:0 auto;padding:24px}.zmsg *{box-sizing:border-box}.zmsg-head{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:18px}.zmsg-head h1{margin:4px 0 7px;font-size:clamp(30px,4vw,58px);letter-spacing:-.045em}.zmsg-kicker{color:#10d5d2;font-size:12px;font-weight:900;letter-spacing:.16em;text-transform:uppercase}.zmsg-sub{max-width:780px;color:#9ba5b4}.zmsg-badge{border:1px solid #1d3740;border-radius:999px;padding:9px 13px;color:#8ff6eb;font-size:12px;font-weight:800}.zmsg-tabs{display:flex;gap:8px;margin:0 0 16px}.zmsg-tabs a{border:1px solid #27303d;border-radius:9px;padding:9px 13px;color:#cdd6e4;text-decoration:none}.zmsg-tabs a[aria-current]{border-color:#10d5d2;color:#10d5d2}.zmsg-grid{display:grid;grid-template-columns:minmax(280px,370px) minmax(0,1fr);gap:14px;min-height:620px}.zmsg-panel{background:#0b1017;border:1px solid #222c39;border-radius:16px;overflow:hidden}.zmsg-panel h2{font-size:15px;margin:0;padding:16px;border-bottom:1px solid #222c39}.zmsg-list{list-style:none;margin:0;padding:0}.zmsg-list a{display:block;padding:15px;border-bottom:1px solid #18202b;text-decoration:none;color:#dfe8f3}.zmsg-list a[aria-current]{background:#0d292d}.zmsg-row{display:flex;justify-content:space-between;gap:10px}.zmsg-row strong{overflow-wrap:anywhere}.zmsg-preview{display:block;color:#8793a3;margin-top:7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.zmsg-count{background:#10d5d2;color:#031011;border-radius:99px;min-width:22px;height:22px;text-align:center;padding:2px 6px;font-size:12px;font-weight:900}.zmsg-thread{padding:18px}.zmsg-thread-head{padding-bottom:14px;border-bottom:1px solid #222c39}.zmsg-thread-head h2{padding:0;border:0;font-size:24px;margin:0 0 5px}.zmsg-transcript{list-style:none;padding:14px 0;margin:0;display:flex;flex-direction:column;gap:10px}.zmsg-bubble{max-width:78%;padding:11px 13px;border-radius:13px;background:#151e2a;color:#e6edf5;white-space:pre-wrap;overflow-wrap:anywhere}.zmsg-bubble.out{align-self:flex-end;background:#0b4b50}.zmsg-meta{display:block;color:#8b98a8;font-size:11px;margin-top:6px}.zmsg-compose{border-top:1px solid #222c39;padding-top:14px}.zmsg-compose textarea{width:100%;min-height:105px;background:#080c12;color:#e9f2f5;border:1px solid #2c3848;border-radius:10px;padding:12px}.zmsg-compose button{margin-top:9px;background:#26303b;color:#8994a2;border:0;border-radius:9px;padding:10px 14px;font-weight:800}.zmsg-note{font-size:12px;color:#8e9baa;margin-top:8px}.zmsg-empty{padding:28px;color:#9da8b6}@media(max-width:820px){.zmsg-grid{grid-template-columns:1fr}.zmsg-head{align-items:start;flex-direction:column}.zmsg-bubble{max-width:92%}}
</style>`;
}

export function renderZernioMessagingBody(snapshot: PortalZernioMessagingSnapshot): string {
  if (!snapshot.ok) {
    return `${style()}<section class="zmsg"><nav class="zmsg-tabs"><a href="/portal/inbox">Email &amp; rails</a><a href="${ZERNIO_MESSAGING_ROUTE}" aria-current="page">Social messages</a></nav><div class="zmsg-panel zmsg-empty"><h1>Social messages are temporarily unavailable</h1><p>The signed-in workspace is safe and no provider action ran. Refresh shortly.</p></div></section>`;
  }
  const selected = snapshot.selectedConversation;
  const queue = snapshot.conversations.map((item) => {
    const href = `${ZERNIO_MESSAGING_ROUTE}?conversation=${encodeURIComponent(item.providerConversationId)}`;
    return `<li><a href="${escapeHtml(href)}"${selected?.providerConversationId === item.providerConversationId ? ' aria-current="page"' : ''}><span class="zmsg-row"><strong>${escapeHtml(item.participantName)}</strong>${item.unreadCount > 0 ? `<span class="zmsg-count">${item.unreadCount}</span>` : ''}</span><span class="zmsg-preview">${escapeHtml(item.lastMessage || 'No text preview')}</span><span class="zmsg-meta">Instagram · ${escapeHtml(time(item.updatedAt))}</span></a></li>`;
  }).join('');
  const transcript = snapshot.messages.map((item) => `<li class="zmsg-bubble${item.direction === 'outgoing' ? ' out' : ''}">${escapeHtml(item.body)}<span class="zmsg-meta">${item.direction === 'outgoing' ? 'Property Predator' : escapeHtml(item.senderName)} · ${escapeHtml(time(item.occurredAt))}</span></li>`).join('');
  return `${style()}<section class="zmsg"><header class="zmsg-head"><div><div class="zmsg-kicker">Growth HQ · Zernio live inbox</div><h1>Social messages</h1><p class="zmsg-sub">Read Instagram conversations without marking them read. Replies use a separate immutable draft and approval boundary before any message can leave Growth HQ.</p></div><span class="zmsg-badge">LIVE READ · PROVIDER EFFECTS OFF</span></header><nav class="zmsg-tabs"><a href="/portal/inbox">Email &amp; rails</a><a href="${ZERNIO_MESSAGING_ROUTE}" aria-current="page">Social messages</a></nav><div class="zmsg-grid"><section class="zmsg-panel"><h2>Instagram queue · ${snapshot.conversations.length}${snapshot.queueTruncated ? '+' : ''}</h2>${queue ? `<ul class="zmsg-list">${queue}</ul>` : '<div class="zmsg-empty">No Instagram conversations are available yet.</div>'}</section><section class="zmsg-panel zmsg-thread">${selected ? `<div class="zmsg-thread-head"><h2>${escapeHtml(selected.participantName)}</h2><div class="zmsg-meta">@${escapeHtml(selected.accountUsername)} · ${selected.unreadCount} unread · checked ${escapeHtml(time(snapshot.checkedAt))}</div></div><ol class="zmsg-transcript">${transcript || '<li class="zmsg-empty">No messages returned for this conversation.</li>'}</ol><form class="zmsg-compose"><label for="zmsg-reply"><strong>Reply draft</strong></label><textarea id="zmsg-reply" disabled placeholder="Approval-gated reply authoring is being connected to this live target."></textarea><button type="button" disabled>Create immutable draft</button><p class="zmsg-note">Nothing can be sent from this read-only release. LinkedIn exposes comments through Zernio, but not personal DMs.</p></form>` : '<div class="zmsg-empty">Choose a conversation to view its messages.</div>'}</section></div></section>`;
}
