import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';
import {
  createPropertyPredatorGeneratedSourceRevalidator,
  PropertyPredatorGeneratedSourceError,
} from '../src/company-content-adapter/property-predator-generated-source.js';
import { canonicalCompanyContentJson } from '../src/company-content-pg/validation.js';

const ITEM_ID = 'd1000000-0000-4000-8000-000000000001';
const VERSION_ID = 'd2000000-0000-4000-8000-000000000001';
const BRAND = 'b'.repeat(64);
const TOKEN = 'read-token-0000000000000000000000000001';
const digest = (value: string): string => createHash('sha256').update(value).digest('hex');

function fixture() {
  const payload = {
    body: 'Inspect the evidence before the viewing.',
    contextSha256: 'c'.repeat(64),
    cta_url: 'https://propertypredator.com/learn',
    kind: 'post', platform: 'linkedin',
    schema: 'propertypredator.company-content/v1',
    title: 'Check the evidence', type: 'generated',
  };
  const usage = {
    accountingState: 'provider_tokens_unpriced', inputTokens: 10, outputTokens: 20,
    model: 'test-model', providerRequestId: 'request-000000000001',
  };
  const contentSha256 = digest(canonicalCompanyContentJson(payload));
  return { contentSha256, body: { schemaVersion: 1, item: {
    brandSha256: BRAND, contentSha256, contextSha256: payload.contextSha256,
    draftId: ITEM_ID, itemVersion: 1, payload, status: 'source_review_required', usage,
    usageSha256: digest(canonicalCompanyContentJson(usage)), versionId: VERSION_ID,
  } } };
}

test('revalidates exact immutable generated bytes with the separate read credential', async () => {
  const source = fixture();
  let calls = 0;
  const service = createPropertyPredatorGeneratedSourceRevalidator({
    baseUrl: 'https://propertypredator.com', clientId: 'relaunch72-test', readToken: TOKEN,
    fetchImpl: async (url, init) => {
      calls += 1;
      assert.equal(String(url), `https://propertypredator.com/api/internal/company-content/generated/${VERSION_ID}`);
      assert.equal((init?.headers as Record<string, string>).authorization, `Bearer ${TOKEN}`);
      return new Response(JSON.stringify(source.body), { status: 200, headers: {
        'content-type': 'application/json', 'cache-control': 'no-store',
        'x-company-content-version': VERSION_ID,
        'x-content-sha256': source.contentSha256, 'x-brand-sha256': BRAND,
      } });
    },
  });
  const result = await service.verify({
    sourceItemId: ITEM_ID, sourceVersionId: VERSION_ID, sourceItemVersion: 1,
    contentSha256: source.contentSha256, brandSha256: BRAND,
  });
  assert.match(result.catalogSha256, /^[0-9a-f]{64}$/u);
  assert.equal(calls, 1);
});

test('fails closed when the source version or content hash differs', async () => {
  const source = fixture();
  const service = createPropertyPredatorGeneratedSourceRevalidator({
    baseUrl: 'https://propertypredator.com', clientId: 'relaunch72-test', readToken: TOKEN,
    fetchImpl: async () => new Response(JSON.stringify({
      ...source.body, item: { ...source.body.item, contentSha256: 'f'.repeat(64) },
    }), { status: 200, headers: {
      'content-type': 'application/json', 'cache-control': 'no-store',
      'x-company-content-version': VERSION_ID,
      'x-content-sha256': 'f'.repeat(64), 'x-brand-sha256': BRAND,
    } }),
  });
  await assert.rejects(service.verify({
    sourceItemId: ITEM_ID, sourceVersionId: VERSION_ID, sourceItemVersion: 1,
    contentSha256: source.contentSha256, brandSha256: BRAND,
  }), PropertyPredatorGeneratedSourceError);
});
